import type { IRComponent } from '@dashbuilder/core';
import { AngularExportError } from './types';
import { joinLines, selectorFromClass } from './utils';

const SUPPORTED_TYPES = new Set([
  'visual.input.text',
  'visual.input.select',
  'visual.input.date-range',
  'domain.time-preset',
  'visual.table',
  'visual.detail',
  'visual.skeleton',
  'visual.kpi',
  'visual.chart.line',
  'visual.chart.bar',
  'visual.chart.pie',
]);

export function generateComponentFile(component: IRComponent, className: string): string {
  if (!SUPPORTED_TYPES.has(component.type)) {
    throw new AngularExportError(`Unsupported Angular export component type: ${component.type}`);
  }

  switch (component.type) {
    case 'visual.input.text':
      return generateTextInput(className);
    case 'visual.input.select':
      return generateSelectInput(className);
    case 'visual.input.date-range':
      return generateDateRangeFilter(className);
    case 'domain.time-preset':
      return generateTimePreset(className);
    case 'visual.table':
      return generateDataTable(className);
    case 'visual.detail':
      return generateDetailPanel(className);
    case 'visual.skeleton':
      return generateSkeleton(className);
    case 'visual.kpi':
      return generateKpiCard(className);
    case 'visual.chart.line':
      return generateLineChart(className);
    case 'visual.chart.bar':
      return generateBarChart(className);
    case 'visual.chart.pie':
      return generatePieChart(className);
    default:
      throw new AngularExportError(`Missing Angular template for ${component.type}`);
  }
}

function generateTextInput(className: string): string {
  const selector = selectorFromClass(className);
  return joinLines([
    `import { Component, input, output } from '@angular/core';`,
    ``,
    `@Component({`,
    `  selector: '${selector}',`,
    `  standalone: true,`,
    `  template: \``,
    `    <label class="field" [attr.for]="id()">`,
    `      <input`,
    `        class="input"`,
    `        type="text"`,
    `        [id]="id()"`,
    `        [placeholder]="placeholder()"`,
    `        [required]="required()"`,
    `        [value]="value() ?? ''"`,
    `        (input)="valueChange.emit($any($event.target).value)"`,
    `      />`,
    `    </label>`,
    `  \`,`,
    `})`,
    `export class ${className} {`,
    `  id = input<string>();`,
    `  placeholder = input('');`,
    `  required = input(false);`,
    `  value = input<string>();`,
    `  valueChange = output<string>();`,
    `}`,
    ``,
  ]);
}

function generateSelectInput(className: string): string {
  const selector = selectorFromClass(className);
  return joinLines([
    `import { Component, input, output } from '@angular/core';`,
    `import type { Row } from '../types';`,
    ``,
    `@Component({`,
    `  selector: '${selector}',`,
    `  standalone: true,`,
    `  template: \``,
    `    <label class="field" [attr.for]="id()">`,
    `      <select`,
    `        class="select"`,
    `        [id]="id()"`,
    `        [value]="value() ?? ''"`,
    `        (change)="valueChange.emit($any($event.target).value)"`,
    `      >`,
    `        <option value="">{{ placeholder() }}</option>`,
    `        @for (option of options(); track option.id ?? $index) {`,
    `          <option [value]="option.id ?? option.label ?? $index">`,
    `            {{ option.label ?? option.id ?? $index }}`,
    `          </option>`,
    `        }`,
    `      </select>`,
    `    </label>`,
    `  \`,`,
    `})`,
    `export class ${className} {`,
    `  id = input<string>();`,
    `  placeholder = input('Select…');`,
    `  options = input<Row[]>([]);`,
    `  value = input<string>();`,
    `  valueChange = output<string>();`,
    `}`,
    ``,
  ]);
}

function generateDateRangeFilter(className: string): string {
  const selector = selectorFromClass(className);
  return joinLines([
    `import { Component, input, output } from '@angular/core';`,
    `import type { DateRange } from '../types';`,
    ``,
    `@Component({`,
    `  selector: '${selector}',`,
    `  standalone: true,`,
    `  template: \``,
    `    <div class="date-range" [id]="id()">`,
    `      <label class="field">`,
    `        <span>Start</span>`,
    `        <input`,
    `          class="input"`,
    `          type="date"`,
    `          [value]="current().start"`,
    `          (input)="onStartChange($any($event.target).value)"`,
    `        />`,
    `      </label>`,
    `      <label class="field">`,
    `        <span>End</span>`,
    `        <input`,
    `          class="input"`,
    `          type="date"`,
    `          [value]="current().end"`,
    `          (input)="onEndChange($any($event.target).value)"`,
    `        />`,
    `      </label>`,
    `    </div>`,
    `  \`,`,
    `})`,
    `export class ${className} {`,
    `  id = input<string>();`,
    `  preset = input('last-7-days');`,
    `  value = input<DateRange>();`,
    `  valueChange = output<DateRange>();`,
    ``,
    `  current(): DateRange {`,
    `    return this.value() ?? defaultRangeForPreset(this.preset());`,
    `  }`,
    ``,
    `  onStartChange(start: string): void {`,
    `    this.valueChange.emit({ ...this.current(), start });`,
    `  }`,
    ``,
    `  onEndChange(end: string): void {`,
    `    this.valueChange.emit({ ...this.current(), end });`,
    `  }`,
    `}`,
    ``,
    `function defaultRangeForPreset(preset: string): DateRange {`,
    `  const end = new Date();`,
    `  const start = new Date(end);`,
    `  if (preset === 'last-30-days') {`,
    `    start.setDate(end.getDate() - 30);`,
    `  } else if (preset === 'qtd') {`,
    `    start.setMonth(Math.floor(end.getMonth() / 3) * 3, 1);`,
    `  } else {`,
    `    start.setDate(end.getDate() - 7);`,
    `  }`,
    `  return { start: formatDate(start), end: formatDate(end) };`,
    `}`,
    ``,
    `function formatDate(date: Date): string {`,
    `  return date.toISOString().slice(0, 10);`,
    `}`,
    ``,
  ]);
}

function generateTimePreset(className: string): string {
  const selector = selectorFromClass(className);
  return joinLines([
    `import { Component, input, output, signal } from '@angular/core';`,
    `import type { DateRange } from '../types';`,
    ``,
    `const PRESET_OPTIONS = [`,
    `  { id: 'last-7-days', label: 'Last 7 days' },`,
    `  { id: 'last-30-days', label: 'Last 30 days' },`,
    `  { id: 'qtd', label: 'Quarter to date' },`,
    `] as const;`,
    ``,
    `@Component({`,
    `  selector: '${selector}',`,
    `  standalone: true,`,
    `  template: \``,
    `    <div class="time-preset" [id]="id()">`,
    `      <span class="time-preset__label">{{ label() }}</span>`,
    `      <div class="time-preset__buttons">`,
    `        @for (preset of presets; track preset.id) {`,
    `          <button`,
    `            type="button"`,
    `            class="time-preset__button"`,
    `            [class.time-preset__button--active]="isActive(preset.id)"`,
    `            (click)="selectPreset(preset.id)"`,
    `          >`,
    `            {{ preset.label }}`,
    `          </button>`,
    `        }`,
    `      </div>`,
    `    </div>`,
    `  \`,`,
    `})`,
    `export class ${className} {`,
    `  id = input<string>();`,
    `  label = input('Period');`,
    `  defaultPreset = input('last-7-days');`,
    `  value = input<DateRange>();`,
    `  valueChange = output<DateRange>();`,
    ``,
    `  protected readonly presets = PRESET_OPTIONS;`,
    `  protected readonly activePreset = signal<string | null>(null);`,
    ``,
    `  protected isActive(preset: string): boolean {`,
    `    return (this.activePreset() ?? this.defaultPreset()) === preset;`,
    `  }`,
    ``,
    `  selectPreset(preset: string): void {`,
    `    this.activePreset.set(preset);`,
    `    this.valueChange.emit(defaultRangeForPreset(preset));`,
    `  }`,
    `}`,
    ``,
    `function defaultRangeForPreset(preset: string): DateRange {`,
    `  const end = new Date();`,
    `  const start = new Date(end);`,
    `  if (preset === 'last-30-days') {`,
    `    start.setDate(end.getDate() - 30);`,
    `  } else if (preset === 'qtd') {`,
    `    start.setMonth(Math.floor(end.getMonth() / 3) * 3, 1);`,
    `  } else {`,
    `    start.setDate(end.getDate() - 7);`,
    `  }`,
    `  return { start: formatDate(start), end: formatDate(end) };`,
    `}`,
    ``,
    `function formatDate(date: Date): string {`,
    `  return date.toISOString().slice(0, 10);`,
    `}`,
    ``,
  ]);
}

function generateDataTable(className: string): string {
  const selector = selectorFromClass(className);
  return joinLines([
    `import { Component, computed, input } from '@angular/core';`,
    `import type { DateRange, Row } from '../types';`,
    ``,
    `@Component({`,
    `  selector: '${selector}',`,
    `  standalone: true,`,
    `  template: \``,
    `    <section class="table-card" [id]="id()" [attr.data-sortable]="sortable()" [attr.data-filterable]="filterable()">`,
    `      <table class="table">`,
    `        <thead>`,
    `          <tr>`,
    `            @for (column of columns(); track column) {`,
    `              <th>{{ column }}</th>`,
    `            }`,
    `          </tr>`,
    `        </thead>`,
    `        <tbody>`,
    `          @for (row of rows(); track row.id ?? $index) {`,
    `            <tr`,
    `              class="table-row"`,
    `              [class.table-row--selected]="selectedRow()?.id === row.id"`,
    `              (click)="handleRowSelect(row)"`,
    `            >`,
    `              @for (column of columns(); track column) {`,
    `                <td>{{ row[column] ?? '' }}</td>`,
    `              }`,
    `            </tr>`,
    `          }`,
    `        </tbody>`,
    `      </table>`,
    `    </section>`,
    `  \`,`,
    `})`,
    `export class ${className} {`,
    `  id = input<string>();`,
    `  data = input<Row[]>([]);`,
    `  filter = input<DateRange>();`,
    `  pageSize = input(25);`,
    `  sortable = input(true);`,
    `  filterable = input(true);`,
    `  selectedRow = input<Row>();`,
    `  onSelectRow = input<(row: Row) => void>();`,
    ``,
    `  rows = computed(() => filterRows(this.data(), this.filter()).slice(0, this.pageSize()));`,
    `  columns = computed(() => {`,
    `    const first = this.rows()[0];`,
    `    return first ? Object.keys(first) : ['id', 'label', 'value'];`,
    `  });`,
    ``,
    `  protected handleRowSelect(row: Row): void {`,
    `    this.onSelectRow()?.(row);`,
    `  }`,
    `}`,
    ``,
    `function filterRows(data: Row[], filter?: DateRange): Row[] {`,
    `  if (!filter) {`,
    `    return data;`,
    `  }`,
    `  return data.filter((row) => {`,
    `    const value = String(row['date'] ?? row['createdAt'] ?? '');`,
    `    if (!value) {`,
    `      return true;`,
    `    }`,
    `    return value >= filter.start && value <= filter.end;`,
    `  });`,
    `}`,
    ``,
  ]);
}

function generateDetailPanel(className: string): string {
  const selector = selectorFromClass(className);
  return joinLines([
    `import { Component, computed, input } from '@angular/core';`,
    `import type { Row } from '../types';`,
    ``,
    `@Component({`,
    `  selector: '${selector}',`,
    `  standalone: true,`,
    `  template: \``,
    `    <section class="detail-panel" [id]="id()">`,
    `      <h3>{{ title() }}</h3>`,
    `      @if (fields().length === 0) {`,
    `        <p class="detail-panel__empty">{{ emptyMessage() }}</p>`,
    `      } @else {`,
    `        <dl class="detail-panel__fields">`,
    `          @for (field of fields(); track field.key) {`,
    `            <div class="detail-panel__field">`,
    `              <dt>{{ field.key }}</dt>`,
    `              <dd>{{ field.value }}</dd>`,
    `            </div>`,
    `          }`,
    `        </dl>`,
    `      }`,
    `    </section>`,
    `  \`,`,
    `})`,
    `export class ${className} {`,
    `  id = input<string>();`,
    `  title = input('Details');`,
    `  emptyMessage = input('Select a row to view details');`,
    `  row = input<Row>();`,
    ``,
    `  fields = computed(() => {`,
    `    const current = this.row();`,
    `    if (!current) {`,
    `      return [] as Array<{ key: string; value: string }>;`,
    `    }`,
    `    return Object.entries(current).map(([key, value]) => ({`,
    `      key,`,
    `      value: String(value ?? ''),`,
    `    }));`,
    `  });`,
    `}`,
    ``,
  ]);
}

function generateSkeleton(className: string): string {
  const selector = selectorFromClass(className);
  return joinLines([
    `import { Component, computed, input } from '@angular/core';`,
    ``,
    `@Component({`,
    `  selector: '${selector}',`,
    `  standalone: true,`,
    `  template: \``,
    `    @if (loading()) {`,
    `      <div class="skeleton skeleton--{{ variant() }}" [id]="id()" aria-busy="true">`,
    `        @if (variant() === 'chart') {`,
    `          <div class="skeleton__chart-block"></div>`,
    `          <div class="skeleton__legend">`,
    `            @for (line of lineIndexes(); track line) {`,
    `              <span class="skeleton__line skeleton__line--short"></span>`,
    `            }`,
    `          </div>`,
    `        } @else if (variant() === 'kpi') {`,
    `          <span class="skeleton__line skeleton__line--title"></span>`,
    `          <span class="skeleton__line skeleton__line--value"></span>`,
    `        } @else {`,
    `          @for (line of lineIndexes(); track line) {`,
    `            <span class="skeleton__line"></span>`,
    `          }`,
    `        }`,
    `      </div>`,
    `    }`,
    `  \`,`,
    `})`,
    `export class ${className} {`,
    `  id = input<string>();`,
    `  loading = input(true);`,
    `  variant = input<'table' | 'chart' | 'kpi' | 'card'>('table');`,
    `  lines = input(4);`,
    ``,
    `  lineIndexes = computed(() => {`,
    `    const count = Math.max(1, Math.min(this.lines(), 8));`,
    `    return Array.from({ length: count }, (_, index) => index);`,
    `  });`,
    `}`,
    ``,
  ]);
}

function generateKpiCard(className: string): string {
  const selector = selectorFromClass(className);
  return joinLines([
    `import { Component, input } from '@angular/core';`,
    ``,
    `@Component({`,
    `  selector: '${selector}',`,
    `  standalone: true,`,
    `  template: \``,
    `    <article class="kpi-card" [id]="id()">`,
    `      <h3>{{ title() }}</h3>`,
    `      <p class="kpi-value">{{ formatValue(value(), format()) }}</p>`,
    `    </article>`,
    `  \`,`,
    `})`,
    `export class ${className} {`,
    `  id = input<string>();`,
    `  title = input('Metric');`,
    `  format = input<'number' | 'currency' | 'percent'>('number');`,
    `  value = input(0);`,
    `}`,
    ``,
    `function formatValue(value: number, format: 'number' | 'currency' | 'percent'): string {`,
    `  if (format === 'currency') {`,
    `    return new Intl.NumberFormat(undefined, { style: 'currency', currency: 'USD' }).format(value);`,
    `  }`,
    `  if (format === 'percent') {`,
    `    return new Intl.NumberFormat(undefined, { style: 'percent', maximumFractionDigits: 1 }).format(value / 100);`,
    `  }`,
    `  return new Intl.NumberFormat().format(value);`,
    `}`,
    ``,
  ]);
}

function generateLineChart(className: string): string {
  const selector = selectorFromClass(className);
  return joinLines([
    `import { Component, computed, input } from '@angular/core';`,
    `import type { DateRange, Row } from '../types';`,
    ``,
    `@Component({`,
    `  selector: '${selector}',`,
    `  standalone: true,`,
    `  template: \``,
    `    <section class="chart-card" [id]="id()">`,
    `      <h3>{{ title() }}</h3>`,
    `      <svg class="line-chart" viewBox="0 0 320 120" role="img" [attr.aria-label]="title()">`,
    `        <polyline fill="none" stroke="currentColor" stroke-width="2" [attr.points]="points()" />`,
    `      </svg>`,
    `      <p class="chart-meta">{{ filtered().length }} points · x={{ xField() }} · y={{ yField() }}</p>`,
    `    </section>`,
    `  \`,`,
    `})`,
    `export class ${className} {`,
    `  id = input<string>();`,
    `  title = input('Chart');`,
    `  xField = input('date');`,
    `  yField = input('value');`,
    `  data = input<Row[]>([]);`,
    `  range = input<DateRange>();`,
    ``,
    `  filtered = computed(() => filterByRange(this.data(), this.range()));`,
    `  points = computed(() => {`,
    `    const rows = this.filtered();`,
    `    const max = Math.max(...rows.map((row) => Number(row[this.yField()] ?? 0)), 1);`,
    `    return rows`,
    `      .map((row, index) => {`,
    `        const x = (index / Math.max(rows.length - 1, 1)) * 300 + 10;`,
    `        const y = 110 - (Number(row[this.yField()] ?? 0) / max) * 90;`,
    `        return \`\${x},\${y}\`;`,
    `      })`,
    `      .join(' ');`,
    `  });`,
    `}`,
    ``,
    `function filterByRange(data: Row[], range?: DateRange): Row[] {`,
    `  if (!range) {`,
    `    return data;`,
    `  }`,
    `  return data.filter((row) => {`,
    `    const value = String(row['date'] ?? row['createdAt'] ?? '');`,
    `    if (!value) {`,
    `      return true;`,
    `    }`,
    `    return value >= range.start && value <= range.end;`,
    `  });`,
    `}`,
    ``,
  ]);
}

function generateBarChart(className: string): string {
  const selector = selectorFromClass(className);
  return joinLines([
    `import { Component, computed, input } from '@angular/core';`,
    `import type { DateRange, Row } from '../types';`,
    ``,
    `@Component({`,
    `  selector: '${selector}',`,
    `  standalone: true,`,
    `  template: \``,
    `    <section class="chart-card" [id]="id()">`,
    `      <h3>{{ title() }}</h3>`,
    `      <div class="bar-chart">`,
    `        @for (row of filtered(); track row.id ?? $index) {`,
    `          <div`,
    `            class="bar"`,
    `            [style.height.%]="barHeight(row)"`,
    `            [title]="String(row.label ?? row.id ?? $index)"`,
    `          ></div>`,
    `        }`,
    `      </div>`,
    `    </section>`,
    `  \`,`,
    `})`,
    `export class ${className} {`,
    `  id = input<string>();`,
    `  title = input('Chart');`,
    `  data = input<Row[]>([]);`,
    `  range = input<DateRange>();`,
    ``,
    `  filtered = computed(() => filterByRange(this.data(), this.range()));`,
    ``,
    `  barHeight(row: Row): number {`,
    `    const max = Math.max(...this.filtered().map((entry) => Number(entry['value'] ?? 0)), 1);`,
    `    return (Number(row['value'] ?? 0) / max) * 100;`,
    `  }`,
    `}`,
    ``,
    `function filterByRange(data: Row[], range?: DateRange): Row[] {`,
    `  if (!range) {`,
    `    return data;`,
    `  }`,
    `  return data.filter((row) => {`,
    `    const value = String(row['date'] ?? row['createdAt'] ?? '');`,
    `    if (!value) {`,
    `      return true;`,
    `    }`,
    `    return value >= range.start && value <= range.end;`,
    `  });`,
    `}`,
    ``,
  ]);
}

function generatePieChart(className: string): string {
  const selector = selectorFromClass(className);
  return joinLines([
    `import { Component, computed, input } from '@angular/core';`,
    `import type { DateRange, Row } from '../types';`,
    ``,
    `@Component({`,
    `  selector: '${selector}',`,
    `  standalone: true,`,
    `  template: \``,
    `    <section class="chart-card" [id]="id()">`,
    `      <h3>{{ title() }}</h3>`,
    `      <div`,
    `        class="pie-chart"`,
    `        [class.pie-chart--donut]="donut()"`,
    `        [style.background]="gradient()"`,
    `      ></div>`,
    `      <ul class="pie-chart__legend">`,
    `        @for (row of filtered(); track row.id ?? $index) {`,
    `          <li>`,
    `            <span [style.background]="color($index)"></span>`,
    `            {{ String(row[labelField()] ?? row.id ?? $index) }}`,
    `          </li>`,
    `        }`,
    `      </ul>`,
    `    </section>`,
    `  \`,`,
    `})`,
    `export class ${className} {`,
    `  id = input<string>();`,
    `  title = input('Chart');`,
    `  labelField = input('label');`,
    `  valueField = input('value');`,
    `  donut = input(false);`,
    `  data = input<Row[]>([]);`,
    `  range = input<DateRange>();`,
    ``,
    `  filtered = computed(() => filterByRange(this.data(), this.range()));`,
    ``,
    `  gradient = computed(() => {`,
    `    const colors = ['#3b82f6', '#10b981', '#f59e0b', '#ef4444', '#8b5cf6'];`,
    `    const total = this.filtered().reduce((sum, row) => sum + Number(row[this.valueField()] ?? 0), 0) || 1;`,
    `    let cumulative = 0;`,
    `    const stops = this.filtered().map((row, index) => {`,
    `      const value = Number(row[this.valueField()] ?? 0);`,
    `      const percent = (value / total) * 100;`,
    `      const start = cumulative;`,
    `      cumulative += percent;`,
    `      return \`\${colors[index % colors.length]} \${start}% \${cumulative}%\`;`,
    `    });`,
    `    return \`conic-gradient(\${stops.join(', ') || '#d1d5db 0 100%'})\`;`,
    `  });`,
    ``,
    `  color(index: number): string {`,
    `    const colors = ['#3b82f6', '#10b981', '#f59e0b', '#ef4444', '#8b5cf6'];`,
    `    return colors[index % colors.length] ?? colors[0];`,
    `  }`,
    `}`,
    ``,
    `function filterByRange(data: Row[], range?: DateRange): Row[] {`,
    `  if (!range) {`,
    `    return data;`,
    `  }`,
    `  return data.filter((row) => {`,
    `    const value = String(row['date'] ?? row['createdAt'] ?? '');`,
    `    if (!value) {`,
    `      return true;`,
    `    }`,
    `    return value >= range.start && value <= range.end;`,
    `  });`,
    `}`,
    ``,
  ]);
}
