import { joinLines, selectorFromClass } from './utils';

function threeVisualHelpers(): string[] {
  return [
    `const BAR_COLORS = ['#38bdf8', '#818cf8', '#34d399', '#fbbf24', '#f472b6', '#fb7185'];`,
    ``,
    `interface ScatterPoint {`,
    `  x: number;`,
    `  y: number;`,
    `  z: number;`,
    `  label?: string;`,
    `}`,
    ``,
    `function filterByRange(data: Row[], range?: DateRange): Row[] {`,
    `  if (!range) {`,
    `    return data;`,
    `  }`,
    `  return data.filter((row) => {`,
    `    const value = String(row.date ?? row.createdAt ?? '');`,
    `    if (!value) {`,
    `      return true;`,
    `    }`,
    `    return value >= range.start && value <= range.end;`,
    `  });`,
    `}`,
    ``,
    `function mapScatterPoints(`,
    `  rows: Row[],`,
    `  fields: { xField: string; yField: string; zField: string },`,
    `): ScatterPoint[] {`,
    `  if (rows.length === 0) {`,
    `    return [`,
    `      { x: -2, y: 1.2, z: -2, label: 'A' },`,
    `      { x: 0, y: 2.4, z: 1, label: 'B' },`,
    `      { x: 2, y: 0.8, z: 2, label: 'C' },`,
    `    ];`,
    `  }`,
    ``,
    `  const raw = rows.slice(0, 48).map((row, index) => ({`,
    `    x: readNumericField(row, fields.xField, index),`,
    `    y: readNumericField(row, fields.yField, index + 1),`,
    `    z: readNumericField(row, fields.zField, index * 0.75 + 1),`,
    `    label: String(row.name ?? row.id ?? index + 1),`,
    `  }));`,
    ``,
    `  return normalizeScatterPoints(raw);`,
    `}`,
    ``,
    `function readNumericField(row: Row, field: string, fallback: number): number {`,
    `  const value = row[field];`,
    `  if (typeof value === 'number' && Number.isFinite(value)) {`,
    `    return value;`,
    `  }`,
    `  if (typeof value === 'string') {`,
    `    const parsed = Number(value);`,
    `    if (Number.isFinite(parsed)) {`,
    `      return parsed;`,
    `    }`,
    `    const timestamp = Date.parse(value);`,
    `    if (Number.isFinite(timestamp)) {`,
    `      return timestamp / 86400000;`,
    `    }`,
    `  }`,
    `  return fallback;`,
    `}`,
    ``,
    `function normalizeScatterPoints(points: ScatterPoint[]): ScatterPoint[] {`,
    `  const normalizeAxis = (values: number[], spread = 8, floor = 0.2) => {`,
    `    const min = Math.min(...values);`,
    `    const max = Math.max(...values);`,
    `    const span = max - min || 1;`,
    `    return values.map((value) => ((value - min) / span) * spread + floor);`,
    `  };`,
    ``,
    `  const xs = normalizeAxis(`,
    `    points.map((point) => point.x),`,
    `    8,`,
    `    -4,`,
    `  );`,
    `  const ys = normalizeAxis(points.map((point) => point.y));`,
    `  const zs = normalizeAxis(`,
    `    points.map((point) => point.z),`,
    `    8,`,
    `    -4,`,
    `  );`,
    ``,
    `  return points.map((point, index) => ({`,
    `    ...point,`,
    `    x: xs[index] ?? point.x,`,
    `    y: ys[index] ?? point.y,`,
    `    z: zs[index] ?? point.z,`,
    `  }));`,
    `}`,
    ``,
  ];
}

function threeRuntimeTail(rebuildBody: string[]): string[] {
  return [
    `  private mount(): void {`,
    `    const host = this.host?.nativeElement;`,
    `    if (!host) {`,
    `      return;`,
    `    }`,
    `    this.renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true });`,
    `    host.appendChild(this.renderer.domElement);`,
    `    this.camera = new THREE.PerspectiveCamera(45, 1, 0.1, 200);`,
    `    this.camera.position.set(8, 6, 8);`,
    `    this.camera.lookAt(0, 1.5, 0);`,
    `    this.controls = new OrbitControls(this.camera, this.renderer.domElement);`,
    `    this.controls.enableDamping = true;`,
    `    this.controls.minDistance = 4;`,
    `    this.controls.maxDistance = 40;`,
    `    this.scene.add(new THREE.AmbientLight(0xffffff, 0.65));`,
    `    const keyLight = new THREE.DirectionalLight(0xffffff, 1.1);`,
    `    keyLight.position.set(6, 10, 4);`,
    `    this.scene.add(keyLight);`,
    `    this.resize();`,
    `    this.startLoop();`,
    `  }`,
    ``,
    `  private rebuild(): void {`,
    `    if (!this.renderer || !this.camera) {`,
    `      return;`,
    `    }`,
    `    this.clearContent();`,
    `    this.scene.background = new THREE.Color(this.backgroundColor());`,
    `    if (this.controls) {`,
    `      this.controls.autoRotate = this.autoRotate();`,
    `    }`,
    ...rebuildBody,
    `    this.resize();`,
    `  }`,
    ``,
    `  private clearContent(): void {`,
    `    for (const child of [...this.contentGroup.children]) {`,
    `      this.contentGroup.remove(child);`,
    `      if (child instanceof THREE.Mesh) {`,
    `        child.geometry.dispose();`,
    `        if (Array.isArray(child.material)) {`,
    `          child.material.forEach((material) => material.dispose());`,
    `        } else {`,
    `          child.material.dispose();`,
    `        }`,
    `      }`,
    `    }`,
    `    if (this.gridHelper) {`,
    `      this.scene.remove(this.gridHelper);`,
    `      this.gridHelper.dispose();`,
    `      this.gridHelper = undefined;`,
    `    }`,
    `  }`,
    ``,
    `  private resize(): void {`,
    `    const host = this.host?.nativeElement;`,
    `    if (!host || !this.renderer || !this.camera) {`,
    `      return;`,
    `    }`,
    `    const width = Math.max(host.clientWidth, 1);`,
    `    const height = Math.max(host.clientHeight, 1);`,
    `    this.camera.aspect = width / height;`,
    `    this.camera.updateProjectionMatrix();`,
    `    this.renderer.setSize(width, height, false);`,
    `  }`,
    ``,
    `  private startLoop(): void {`,
    `    const tick = () => {`,
    `      this.controls?.update();`,
    `      if (this.renderer && this.camera) {`,
    `        this.renderer.render(this.scene, this.camera);`,
    `      }`,
    `      this.animationId = requestAnimationFrame(tick);`,
    `    };`,
    `    tick();`,
    `  }`,
    ``,
    `  private disposeRuntime(): void {`,
    `    if (this.animationId !== undefined) {`,
    `      cancelAnimationFrame(this.animationId);`,
    `      this.animationId = undefined;`,
    `    }`,
    `    this.clearContent();`,
    `    this.controls?.dispose();`,
    `    this.renderer?.dispose();`,
    `    this.renderer?.domElement.remove();`,
    `    this.renderer = undefined;`,
    `    this.controls = undefined;`,
    `    this.camera = undefined;`,
    `  }`,
  ];
}

export function generateThreeBarChart(className: string): string {
  const selector = selectorFromClass(className);
  return joinLines([
    `/** Requires: npm install three */`,
    `import {`,
    `  AfterViewInit,`,
    `  Component,`,
    `  ElementRef,`,
    `  OnDestroy,`,
    `  ViewChild,`,
    `  effect,`,
    `  input,`,
    `} from '@angular/core';`,
    `import * as THREE from 'three';`,
    `import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';`,
    `import type { DateRange, Row } from '../types';`,
    ``,
    `@Component({`,
    `  selector: '${selector}',`,
    `  standalone: true,`,
    `  template: \``,
    `    <section class="chart-card chart-card--3d" [id]="id()">`,
    `      <h3>{{ title() }}</h3>`,
    `      <div class="three-chart" [style.background]="backgroundColor()" #host></div>`,
    `    </section>`,
    `  \`,`,
    `})`,
    `export class ${className} implements AfterViewInit, OnDestroy {`,
    `  @ViewChild('host') host!: ElementRef<HTMLDivElement>;`,
    ``,
    `  id = input<string>();`,
    `  title = input('3D Bar Chart');`,
    `  yField = input('value');`,
    `  backgroundColor = input('#0f172a');`,
    `  autoRotate = input(false);`,
    `  data = input.required<Row[]>();`,
    `  range = input<DateRange>();`,
    ``,
    `  private readonly scene = new THREE.Scene();`,
    `  private readonly contentGroup = new THREE.Group();`,
    `  private camera?: THREE.PerspectiveCamera;`,
    `  private renderer?: THREE.WebGLRenderer;`,
    `  private controls?: OrbitControls;`,
    `  private gridHelper?: THREE.GridHelper;`,
    `  private animationId?: number;`,
    ``,
    `  constructor() {`,
    `    this.scene.add(this.contentGroup);`,
    `    effect(() => {`,
    `      this.data();`,
    `      this.range();`,
    `      this.yField();`,
    `      this.backgroundColor();`,
    `      this.autoRotate();`,
    `      this.rebuild();`,
    `    });`,
    `  }`,
    ``,
    `  ngAfterViewInit(): void {`,
    `    this.mount();`,
    `    this.rebuild();`,
    `  }`,
    ``,
    `  ngOnDestroy(): void {`,
    `    this.disposeRuntime();`,
    `  }`,
    ``,
    ...threeRuntimeTail([
      `    const rows = filterByRange(this.data(), this.range());`,
      `    const field = this.yField();`,
      `    const max = Math.max(...rows.map((row) => Number(row[field] ?? 0)), 1);`,
      `    const spacing = 1.4;`,
      `    const offset = ((rows.length - 1) * spacing) / 2;`,
      `    rows.forEach((row, index) => {`,
      `      const value = Number(row[field] ?? 0);`,
      `      const height = Math.max(0.2, (value / max) * 4);`,
      `      const geometry = new THREE.BoxGeometry(0.9, height, 0.9);`,
      `      const material = new THREE.MeshStandardMaterial({`,
      `        color: BAR_COLORS[index % BAR_COLORS.length],`,
      `      });`,
      `      const mesh = new THREE.Mesh(geometry, material);`,
      `      mesh.position.set(index * spacing - offset, height / 2, 0);`,
      `      this.contentGroup.add(mesh);`,
      `    });`,
    ]),
    `}`,
    ``,
    ...threeVisualHelpers(),
  ]);
}

export function generateThreeScatterPlot(className: string): string {
  const selector = selectorFromClass(className);
  return joinLines([
    `/** Requires: npm install three */`,
    `import {`,
    `  AfterViewInit,`,
    `  Component,`,
    `  ElementRef,`,
    `  OnDestroy,`,
    `  ViewChild,`,
    `  effect,`,
    `  input,`,
    `} from '@angular/core';`,
    `import * as THREE from 'three';`,
    `import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';`,
    `import type { DateRange, Row } from '../types';`,
    ``,
    `@Component({`,
    `  selector: '${selector}',`,
    `  standalone: true,`,
    `  template: \``,
    `    <section class="chart-card chart-card--3d" [id]="id()">`,
    `      <h3>{{ title() }}</h3>`,
    `      <div class="three-chart" [style.background]="backgroundColor()" #host></div>`,
    `    </section>`,
    `  \`,`,
    `})`,
    `export class ${className} implements AfterViewInit, OnDestroy {`,
    `  @ViewChild('host') host!: ElementRef<HTMLDivElement>;`,
    ``,
    `  id = input<string>();`,
    `  title = input('3D Scatter Plot');`,
    `  xField = input('date');`,
    `  yField = input('amount');`,
    `  zField = input('id');`,
    `  backgroundColor = input('#0f172a');`,
    `  autoRotate = input(false);`,
    `  data = input.required<Row[]>();`,
    `  range = input<DateRange>();`,
    ``,
    `  private readonly scene = new THREE.Scene();`,
    `  private readonly contentGroup = new THREE.Group();`,
    `  private camera?: THREE.PerspectiveCamera;`,
    `  private renderer?: THREE.WebGLRenderer;`,
    `  private controls?: OrbitControls;`,
    `  private gridHelper?: THREE.GridHelper;`,
    `  private animationId?: number;`,
    ``,
    `  constructor() {`,
    `    this.scene.add(this.contentGroup);`,
    `    effect(() => {`,
    `      this.data();`,
    `      this.range();`,
    `      this.xField();`,
    `      this.yField();`,
    `      this.zField();`,
    `      this.backgroundColor();`,
    `      this.autoRotate();`,
    `      this.rebuild();`,
    `    });`,
    `  }`,
    ``,
    `  ngAfterViewInit(): void {`,
    `    this.mount();`,
    `    this.rebuild();`,
    `  }`,
    ``,
    `  ngOnDestroy(): void {`,
    `    this.disposeRuntime();`,
    `  }`,
    ``,
    ...threeRuntimeTail([
      `    const points = mapScatterPoints(filterByRange(this.data(), this.range()), {`,
      `      xField: this.xField(),`,
      `      yField: this.yField(),`,
      `      zField: this.zField(),`,
      `    });`,
      `    const geometry = new THREE.SphereGeometry(0.18, 16, 16);`,
      `    points.forEach((point, index) => {`,
      `      const material = new THREE.MeshStandardMaterial({`,
      `        color: BAR_COLORS[index % BAR_COLORS.length],`,
      `      });`,
      `      const mesh = new THREE.Mesh(geometry, material);`,
      `      mesh.position.set(point.x, point.y, point.z);`,
      `      this.contentGroup.add(mesh);`,
      `    });`,
    ]),
    `}`,
    ``,
    ...threeVisualHelpers(),
  ]);
}

export function generateThreeScenePointCloud(className: string): string {
  const selector = selectorFromClass(className);
  return joinLines([
    `/** Requires: npm install three */`,
    `import {`,
    `  AfterViewInit,`,
    `  Component,`,
    `  ElementRef,`,
    `  OnDestroy,`,
    `  ViewChild,`,
    `  effect,`,
    `  input,`,
    `} from '@angular/core';`,
    `import * as THREE from 'three';`,
    `import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';`,
    `import type { DateRange, Row } from '../types';`,
    ``,
    `@Component({`,
    `  selector: '${selector}',`,
    `  standalone: true,`,
    `  template: \``,
    `    <section class="chart-card chart-card--3d" [id]="id()">`,
    `      <h3>{{ title() }}</h3>`,
    `      <div class="three-chart" [style.background]="backgroundColor()" #host></div>`,
    `    </section>`,
    `  \`,`,
    `})`,
    `export class ${className} implements AfterViewInit, OnDestroy {`,
    `  @ViewChild('host') host!: ElementRef<HTMLDivElement>;`,
    ``,
    `  id = input<string>();`,
    `  title = input('3D Scene');`,
    `  xField = input('date');`,
    `  yField = input('amount');`,
    `  zField = input('id');`,
    `  backgroundColor = input('#0f172a');`,
    `  autoRotate = input(false);`,
    `  showGrid = input(true);`,
    `  data = input.required<Row[]>();`,
    `  range = input<DateRange>();`,
    ``,
    `  private readonly scene = new THREE.Scene();`,
    `  private readonly contentGroup = new THREE.Group();`,
    `  private camera?: THREE.PerspectiveCamera;`,
    `  private renderer?: THREE.WebGLRenderer;`,
    `  private controls?: OrbitControls;`,
    `  private gridHelper?: THREE.GridHelper;`,
    `  private animationId?: number;`,
    ``,
    `  constructor() {`,
    `    this.scene.add(this.contentGroup);`,
    `    effect(() => {`,
    `      this.data();`,
    `      this.range();`,
    `      this.xField();`,
    `      this.yField();`,
    `      this.zField();`,
    `      this.backgroundColor();`,
    `      this.autoRotate();`,
    `      this.showGrid();`,
    `      this.rebuild();`,
    `    });`,
    `  }`,
    ``,
    `  ngAfterViewInit(): void {`,
    `    this.mount();`,
    `    this.rebuild();`,
    `  }`,
    ``,
    `  ngOnDestroy(): void {`,
    `    this.disposeRuntime();`,
    `  }`,
    ``,
    ...threeRuntimeTail([
      `    if (this.showGrid()) {`,
      `      this.gridHelper = new THREE.GridHelper(12, 12, 0x475569, 0x334155);`,
      `      this.gridHelper.position.y = -0.01;`,
      `      this.scene.add(this.gridHelper);`,
      `    }`,
      `    const points = mapScatterPoints(filterByRange(this.data(), this.range()), {`,
      `      xField: this.xField(),`,
      `      yField: this.yField(),`,
      `      zField: this.zField(),`,
      `    });`,
      `    const geometry = new THREE.SphereGeometry(0.1, 10, 10);`,
      `    points.forEach((point, index) => {`,
      `      const material = new THREE.MeshStandardMaterial({`,
      `        color: BAR_COLORS[index % BAR_COLORS.length],`,
      `      });`,
      `      const mesh = new THREE.Mesh(geometry, material);`,
      `      mesh.position.set(point.x, point.y, point.z);`,
      `      this.contentGroup.add(mesh);`,
      `    });`,
    ]),
    `}`,
    ``,
    ...threeVisualHelpers(),
  ]);
}
