import { joinLines, selectorFromClass } from './utils';

function threeVisualHelpers(): string[] {
  return [
    `const BAR_COLORS = ['#38bdf8', '#818cf8', '#34d399', '#fbbf24', '#f472b6', '#fb7185'];`,
    ``,
    `interface ScatterPoint {`,
    `  x: number;`,
    `  y: number;`,
    `  z: number;`,
    `  label?: string;`,
    `}`,
    ``,
    `function filterByRange(data: Row[], range?: DateRange): Row[] {`,
    `  if (!range) {`,
    `    return data;`,
    `  }`,
    `  return data.filter((row) => {`,
    `    const value = String(row.date ?? row.createdAt ?? '');`,
    `    if (!value) {`,
    `      return true;`,
    `    }`,
    `    return value >= range.start && value <= range.end;`,
    `  });`,
    `}`,
    ``,
    `function mapScatterPoints(`,
    `  rows: Row[],`,
    `  fields: { xField: string; yField: string; zField: string },`,
    `): ScatterPoint[] {`,
    `  if (rows.length === 0) {`,
    `    return [`,
    `      { x: -2, y: 1.2, z: -2, label: 'A' },`,
    `      { x: 0, y: 2.4, z: 1, label: 'B' },`,
    `      { x: 2, y: 0.8, z: 2, label: 'C' },`,
    `    ];`,
    `  }`,
    ``,
    `  const raw = rows.slice(0, 48).map((row, index) => ({`,
    `    x: readNumericField(row, fields.xField, index),`,
    `    y: readNumericField(row, fields.yField, index + 1),`,
    `    z: readNumericField(row, fields.zField, index * 0.75 + 1),`,
    `    label: String(row.name ?? row.id ?? index + 1),`,
    `  }));`,
    ``,
    `  return normalizeScatterPoints(raw);`,
    `}`,
    ``,
    `function readNumericField(row: Row, field: string, fallback: number): number {`,
    `  const value = row[field];`,
    `  if (typeof value === 'number' && Number.isFinite(value)) {`,
    `    return value;`,
    `  }`,
    `  if (typeof value === 'string') {`,
    `    const parsed = Number(value);`,
    `    if (Number.isFinite(parsed)) {`,
    `      return parsed;`,
    `    }`,
    `    const timestamp = Date.parse(value);`,
    `    if (Number.isFinite(timestamp)) {`,
    `      return timestamp / 86400000;`,
    `    }`,
    `  }`,
    `  return fallback;`,
    `}`,
    ``,
    `function normalizeScatterPoints(points: ScatterPoint[]): ScatterPoint[] {`,
    `  const normalizeAxis = (values: number[], spread = 8, floor = 0.2) => {`,
    `    const min = Math.min(...values);`,
    `    const max = Math.max(...values);`,
    `    const span = max - min || 1;`,
    `    return values.map((value) => ((value - min) / span) * spread + floor);`,
    `  };`,
    ``,
    `  const xs = normalizeAxis(`,
    `    points.map((point) => point.x),`,
    `    8,`,
    `    -4,`,
    `  );`,
    `  const ys = normalizeAxis(points.map((point) => point.y));`,
    `  const zs = normalizeAxis(`,
    `    points.map((point) => point.z),`,
    `    8,`,
    `    -4,`,
    `  );`,
    ``,
    `  return points.map((point, index) => ({`,
    `    ...point,`,
    `    x: xs[index] ?? point.x,`,
    `    y: ys[index] ?? point.y,`,
    `    z: zs[index] ?? point.z,`,
    `  }));`,
    `}`,
    ``,
  ];
}

function globeVisualHelpers(): string[] {
  return [
    `interface GlobeMarker {`,
    `  lat: number;`,
    `  lng: number;`,
    `  label?: string;`,
    `}`,
    ``,
    `function latLngToGlobePosition(lat: number, lng: number, radius: number) {`,
    `  const phi = ((90 - lat) * Math.PI) / 180;`,
    `  const theta = ((lng + 180) * Math.PI) / 180;`,
    `  const surfaceRadius = radius + 0.06;`,
    `  return {`,
    `    x: -surfaceRadius * Math.sin(phi) * Math.cos(theta),`,
    `    y: surfaceRadius * Math.cos(phi),`,
    `    z: surfaceRadius * Math.sin(phi) * Math.sin(theta),`,
    `  };`,
    `}`,
    ``,
    `function mapGlobeMarkers(`,
    `  rows: Row[],`,
    `  fields: { latField: string; lngField: string; labelField: string },`,
    `): GlobeMarker[] {`,
    `  if (rows.length === 0) {`,
    `    return [`,
    `      { lat: 40.7128, lng: -74.006, label: 'New York' },`,
    `      { lat: 51.5074, lng: -0.1278, label: 'London' },`,
    `      { lat: 35.6762, lng: 139.6503, label: 'Tokyo' },`,
    `    ];`,
    `  }`,
    ``,
    `  return rows.slice(0, 48).map((row, index) => ({`,
    `    lat: Number(row[fields.latField] ?? 0),`,
    `    lng: Number(row[fields.lngField] ?? 0),`,
    `    label: String(row[fields.labelField] ?? row.id ?? index + 1),`,
    `  }));`,
    `}`,
    ``,
  ];
}

function threeRuntimeTail(rebuildBody: string[]): string[] {
  return [
    `  private mount(): void {`,
    `    const host = this.host?.nativeElement;`,
    `    if (!host) {`,
    `      return;`,
    `    }`,
    `    this.renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true });`,
    `    host.appendChild(this.renderer.domElement);`,
    `    this.camera = new THREE.PerspectiveCamera(45, 1, 0.1, 200);`,
    `    this.camera.position.set(8, 6, 8);`,
    `    this.camera.lookAt(0, 1.5, 0);`,
    `    this.controls = new OrbitControls(this.camera, this.renderer.domElement);`,
    `    this.controls.enableDamping = true;`,
    `    this.controls.minDistance = 4;`,
    `    this.controls.maxDistance = 40;`,
    `    this.scene.add(new THREE.AmbientLight(0xffffff, 0.65));`,
    `    const keyLight = new THREE.DirectionalLight(0xffffff, 1.1);`,
    `    keyLight.position.set(6, 10, 4);`,
    `    this.scene.add(keyLight);`,
    `    this.resize();`,
    `    this.startLoop();`,
    `  }`,
    ``,
    `  private rebuild(): void {`,
    `    if (!this.renderer || !this.camera) {`,
    `      return;`,
    `    }`,
    `    this.clearContent();`,
    `    this.scene.background = new THREE.Color(this.backgroundColor());`,
    `    if (this.controls) {`,
    `      this.controls.autoRotate = this.autoRotate();`,
    `    }`,
    ...rebuildBody,
    `    this.resize();`,
    `  }`,
    ``,
    `  private clearContent(): void {`,
    `    for (const child of [...this.contentGroup.children]) {`,
    `      this.contentGroup.remove(child);`,
    `      if (child instanceof THREE.Mesh) {`,
    `        child.geometry.dispose();`,
    `        if (Array.isArray(child.material)) {`,
    `          child.material.forEach((material) => material.dispose());`,
    `        } else {`,
    `          child.material.dispose();`,
    `        }`,
    `      }`,
    `    }`,
    `    if (this.gridHelper) {`,
    `      this.scene.remove(this.gridHelper);`,
    `      this.gridHelper.dispose();`,
    `      this.gridHelper = undefined;`,
    `    }`,
    `  }`,
    ``,
    `  private resize(): void {`,
    `    const host = this.host?.nativeElement;`,
    `    if (!host || !this.renderer || !this.camera) {`,
    `      return;`,
    `    }`,
    `    const width = Math.max(host.clientWidth, 1);`,
    `    const height = Math.max(host.clientHeight, 1);`,
    `    this.camera.aspect = width / height;`,
    `    this.camera.updateProjectionMatrix();`,
    `    this.renderer.setSize(width, height, false);`,
    `  }`,
    ``,
    `  private startLoop(): void {`,
    `    const tick = () => {`,
    `      this.controls?.update();`,
    `      if (this.renderer && this.camera) {`,
    `        this.renderer.render(this.scene, this.camera);`,
    `      }`,
    `      this.animationId = requestAnimationFrame(tick);`,
    `    };`,
    `    tick();`,
    `  }`,
    ``,
    `  private disposeRuntime(): void {`,
    `    if (this.animationId !== undefined) {`,
    `      cancelAnimationFrame(this.animationId);`,
    `      this.animationId = undefined;`,
    `    }`,
    `    this.clearContent();`,
    `    this.controls?.dispose();`,
    `    this.renderer?.dispose();`,
    `    this.renderer?.domElement.remove();`,
    `    this.renderer = undefined;`,
    `    this.controls = undefined;`,
    `    this.camera = undefined;`,
    `  }`,
  ];
}

export function generateThreeBarChart(className: string): string {
  const selector = selectorFromClass(className);
  return joinLines([
    `/** Requires: npm install three */`,
    `import {`,
    `  AfterViewInit,`,
    `  Component,`,
    `  ElementRef,`,
    `  OnDestroy,`,
    `  ViewChild,`,
    `  effect,`,
    `  input,`,
    `} from '@angular/core';`,
    `import * as THREE from 'three';`,
    `import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';`,
    `import type { DateRange, Row } from '../types';`,
    ``,
    `@Component({`,
    `  selector: '${selector}',`,
    `  standalone: true,`,
    `  template: \``,
    `    <section class="chart-card chart-card--3d" [id]="id()">`,
    `      <h3>{{ title() }}</h3>`,
    `      <div class="three-chart" [style.background]="backgroundColor()" #host></div>`,
    `    </section>`,
    `  \`,`,
    `})`,
    `export class ${className} implements AfterViewInit, OnDestroy {`,
    `  @ViewChild('host') host!: ElementRef<HTMLDivElement>;`,
    ``,
    `  id = input<string>();`,
    `  title = input('3D Bar Chart');`,
    `  yField = input('value');`,
    `  backgroundColor = input('#0f172a');`,
    `  autoRotate = input(false);`,
    `  data = input.required<Row[]>();`,
    `  range = input<DateRange>();`,
    ``,
    `  private readonly scene = new THREE.Scene();`,
    `  private readonly contentGroup = new THREE.Group();`,
    `  private camera?: THREE.PerspectiveCamera;`,
    `  private renderer?: THREE.WebGLRenderer;`,
    `  private controls?: OrbitControls;`,
    `  private gridHelper?: THREE.GridHelper;`,
    `  private animationId?: number;`,
    ``,
    `  constructor() {`,
    `    this.scene.add(this.contentGroup);`,
    `    effect(() => {`,
    `      this.data();`,
    `      this.range();`,
    `      this.yField();`,
    `      this.backgroundColor();`,
    `      this.autoRotate();`,
    `      this.rebuild();`,
    `    });`,
    `  }`,
    ``,
    `  ngAfterViewInit(): void {`,
    `    this.mount();`,
    `    this.rebuild();`,
    `  }`,
    ``,
    `  ngOnDestroy(): void {`,
    `    this.disposeRuntime();`,
    `  }`,
    ``,
    ...threeRuntimeTail([
      `    const rows = filterByRange(this.data(), this.range());`,
      `    const field = this.yField();`,
      `    const max = Math.max(...rows.map((row) => Number(row[field] ?? 0)), 1);`,
      `    const spacing = 1.4;`,
      `    const offset = ((rows.length - 1) * spacing) / 2;`,
      `    rows.forEach((row, index) => {`,
      `      const value = Number(row[field] ?? 0);`,
      `      const height = Math.max(0.2, (value / max) * 4);`,
      `      const geometry = new THREE.BoxGeometry(0.9, height, 0.9);`,
      `      const material = new THREE.MeshStandardMaterial({`,
      `        color: BAR_COLORS[index % BAR_COLORS.length],`,
      `      });`,
      `      const mesh = new THREE.Mesh(geometry, material);`,
      `      mesh.position.set(index * spacing - offset, height / 2, 0);`,
      `      this.contentGroup.add(mesh);`,
      `    });`,
    ]),
    `}`,
    ``,
    ...threeVisualHelpers(),
  ]);
}

export function generateThreeScatterPlot(className: string): string {
  const selector = selectorFromClass(className);
  return joinLines([
    `/** Requires: npm install three */`,
    `import {`,
    `  AfterViewInit,`,
    `  Component,`,
    `  ElementRef,`,
    `  OnDestroy,`,
    `  ViewChild,`,
    `  effect,`,
    `  input,`,
    `} from '@angular/core';`,
    `import * as THREE from 'three';`,
    `import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';`,
    `import type { DateRange, Row } from '../types';`,
    ``,
    `@Component({`,
    `  selector: '${selector}',`,
    `  standalone: true,`,
    `  template: \``,
    `    <section class="chart-card chart-card--3d" [id]="id()">`,
    `      <h3>{{ title() }}</h3>`,
    `      <div class="three-chart" [style.background]="backgroundColor()" #host></div>`,
    `    </section>`,
    `  \`,`,
    `})`,
    `export class ${className} implements AfterViewInit, OnDestroy {`,
    `  @ViewChild('host') host!: ElementRef<HTMLDivElement>;`,
    ``,
    `  id = input<string>();`,
    `  title = input('3D Scatter Plot');`,
    `  xField = input('date');`,
    `  yField = input('amount');`,
    `  zField = input('id');`,
    `  backgroundColor = input('#0f172a');`,
    `  autoRotate = input(false);`,
    `  data = input.required<Row[]>();`,
    `  range = input<DateRange>();`,
    ``,
    `  private readonly scene = new THREE.Scene();`,
    `  private readonly contentGroup = new THREE.Group();`,
    `  private camera?: THREE.PerspectiveCamera;`,
    `  private renderer?: THREE.WebGLRenderer;`,
    `  private controls?: OrbitControls;`,
    `  private gridHelper?: THREE.GridHelper;`,
    `  private animationId?: number;`,
    ``,
    `  constructor() {`,
    `    this.scene.add(this.contentGroup);`,
    `    effect(() => {`,
    `      this.data();`,
    `      this.range();`,
    `      this.xField();`,
    `      this.yField();`,
    `      this.zField();`,
    `      this.backgroundColor();`,
    `      this.autoRotate();`,
    `      this.rebuild();`,
    `    });`,
    `  }`,
    ``,
    `  ngAfterViewInit(): void {`,
    `    this.mount();`,
    `    this.rebuild();`,
    `  }`,
    ``,
    `  ngOnDestroy(): void {`,
    `    this.disposeRuntime();`,
    `  }`,
    ``,
    ...threeRuntimeTail([
      `    const points = mapScatterPoints(filterByRange(this.data(), this.range()), {`,
      `      xField: this.xField(),`,
      `      yField: this.yField(),`,
      `      zField: this.zField(),`,
      `    });`,
      `    const geometry = new THREE.SphereGeometry(0.18, 16, 16);`,
      `    points.forEach((point, index) => {`,
      `      const material = new THREE.MeshStandardMaterial({`,
      `        color: BAR_COLORS[index % BAR_COLORS.length],`,
      `      });`,
      `      const mesh = new THREE.Mesh(geometry, material);`,
      `      mesh.position.set(point.x, point.y, point.z);`,
      `      this.contentGroup.add(mesh);`,
      `    });`,
    ]),
    `}`,
    ``,
    ...threeVisualHelpers(),
  ]);
}

export function generateThreeScenePointCloud(className: string): string {
  const selector = selectorFromClass(className);
  return joinLines([
    `/** Requires: npm install three */`,
    `import {`,
    `  AfterViewInit,`,
    `  Component,`,
    `  ElementRef,`,
    `  OnDestroy,`,
    `  ViewChild,`,
    `  effect,`,
    `  input,`,
    `} from '@angular/core';`,
    `import * as THREE from 'three';`,
    `import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';`,
    `import type { DateRange, Row } from '../types';`,
    ``,
    `@Component({`,
    `  selector: '${selector}',`,
    `  standalone: true,`,
    `  template: \``,
    `    <section class="chart-card chart-card--3d" [id]="id()">`,
    `      <h3>{{ title() }}</h3>`,
    `      <div class="three-chart" [style.background]="backgroundColor()" #host></div>`,
    `    </section>`,
    `  \`,`,
    `})`,
    `export class ${className} implements AfterViewInit, OnDestroy {`,
    `  @ViewChild('host') host!: ElementRef<HTMLDivElement>;`,
    ``,
    `  id = input<string>();`,
    `  title = input('3D Scene');`,
    `  xField = input('date');`,
    `  yField = input('amount');`,
    `  zField = input('id');`,
    `  backgroundColor = input('#0f172a');`,
    `  autoRotate = input(false);`,
    `  showGrid = input(true);`,
    `  data = input.required<Row[]>();`,
    `  range = input<DateRange>();`,
    ``,
    `  private readonly scene = new THREE.Scene();`,
    `  private readonly contentGroup = new THREE.Group();`,
    `  private camera?: THREE.PerspectiveCamera;`,
    `  private renderer?: THREE.WebGLRenderer;`,
    `  private controls?: OrbitControls;`,
    `  private gridHelper?: THREE.GridHelper;`,
    `  private animationId?: number;`,
    ``,
    `  constructor() {`,
    `    this.scene.add(this.contentGroup);`,
    `    effect(() => {`,
    `      this.data();`,
    `      this.range();`,
    `      this.xField();`,
    `      this.yField();`,
    `      this.zField();`,
    `      this.backgroundColor();`,
    `      this.autoRotate();`,
    `      this.showGrid();`,
    `      this.rebuild();`,
    `    });`,
    `  }`,
    ``,
    `  ngAfterViewInit(): void {`,
    `    this.mount();`,
    `    this.rebuild();`,
    `  }`,
    ``,
    `  ngOnDestroy(): void {`,
    `    this.disposeRuntime();`,
    `  }`,
    ``,
    ...threeRuntimeTail([
      `    if (this.showGrid()) {`,
      `      this.gridHelper = new THREE.GridHelper(12, 12, 0x475569, 0x334155);`,
      `      this.gridHelper.position.y = -0.01;`,
      `      this.scene.add(this.gridHelper);`,
      `    }`,
      `    const points = mapScatterPoints(filterByRange(this.data(), this.range()), {`,
      `      xField: this.xField(),`,
      `      yField: this.yField(),`,
      `      zField: this.zField(),`,
      `    });`,
      `    const geometry = new THREE.SphereGeometry(0.1, 10, 10);`,
      `    points.forEach((point, index) => {`,
      `      const material = new THREE.MeshStandardMaterial({`,
      `        color: BAR_COLORS[index % BAR_COLORS.length],`,
      `      });`,
      `      const mesh = new THREE.Mesh(geometry, material);`,
      `      mesh.position.set(point.x, point.y, point.z);`,
      `      this.contentGroup.add(mesh);`,
      `    });`,
    ]),
    `}`,
    ``,
    ...threeVisualHelpers(),
  ]);
}

export function generateThreeGltfModel(className: string): string {
  const selector = selectorFromClass(className);
  return joinLines([
    `/** Requires: npm install three */`,
    `import { AfterViewInit, Component, ElementRef, OnDestroy, ViewChild, effect, input } from '@angular/core';`,
    `import * as THREE from 'three';`,
    `import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';`,
    `import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';`,
    ``,
    `const DEFAULT_MODEL_URL =`,
    `  'https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/Duck/glTF-Binary/Duck.glb';`,
    ``,
    `@Component({`,
    `  selector: '${selector}',`,
    `  standalone: true,`,
    `  template: \``,
    `    <section class="chart-card chart-card--3d" [id]="id()">`,
    `      <h3>{{ title() }}</h3>`,
    `      <div class="three-chart" [style.background]="backgroundColor()" #host></div>`,
    `    </section>`,
    `  \`,`,
    `})`,
    `export class ${className} implements AfterViewInit, OnDestroy {`,
    `  @ViewChild('host') host!: ElementRef<HTMLDivElement>;`,
    `  id = input<string>();`,
    `  title = input('3D Model');`,
    `  modelUrl = input(DEFAULT_MODEL_URL);`,
    `  modelScale = input(1.5);`,
    `  backgroundColor = input('#0f172a');`,
    `  autoRotate = input(false);`,
    `  showGrid = input(true);`,
    `  private readonly scene = new THREE.Scene();`,
    `  private readonly contentGroup = new THREE.Group();`,
    `  private camera?: THREE.PerspectiveCamera;`,
    `  private renderer?: THREE.WebGLRenderer;`,
    `  private controls?: OrbitControls;`,
    `  private gridHelper?: THREE.GridHelper;`,
    `  private animationId?: number;`,
    `  private gltfLoadId = 0;`,
    `  constructor() {`,
    `    this.scene.add(this.contentGroup);`,
    `    effect(() => {`,
    `      this.modelUrl();`,
    `      this.modelScale();`,
    `      this.backgroundColor();`,
    `      this.autoRotate();`,
    `      this.showGrid();`,
    `      this.syncScene();`,
    `    });`,
    `  }`,
    `  ngAfterViewInit(): void {`,
    `    this.mount();`,
    `    this.syncScene();`,
    `  }`,
    `  ngOnDestroy(): void {`,
    `    this.disposeRuntime();`,
    `  }`,
    `  private mount(): void {`,
    `    const host = this.host?.nativeElement;`,
    `    if (!host) return;`,
    `    this.renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true });`,
    `    host.appendChild(this.renderer.domElement);`,
    `    this.camera = new THREE.PerspectiveCamera(45, 1, 0.1, 200);`,
    `    this.camera.position.set(8, 6, 8);`,
    `    this.camera.lookAt(0, 1.5, 0);`,
    `    this.controls = new OrbitControls(this.camera, this.renderer.domElement);`,
    `    this.controls.enableDamping = true;`,
    `    this.controls.minDistance = 4;`,
    `    this.controls.maxDistance = 40;`,
    `    this.scene.add(new THREE.AmbientLight(0xffffff, 0.65));`,
    `    const keyLight = new THREE.DirectionalLight(0xffffff, 1.1);`,
    `    keyLight.position.set(6, 10, 4);`,
    `    this.scene.add(keyLight);`,
    `    this.resize();`,
    `    this.startLoop();`,
    `  }`,
    `  private syncScene(): void {`,
    `    if (!this.renderer || !this.camera) return;`,
    `    this.scene.background = new THREE.Color(this.backgroundColor());`,
    `    if (this.controls) this.controls.autoRotate = this.autoRotate();`,
    `    if (this.gridHelper) {`,
    `      this.scene.remove(this.gridHelper);`,
    `      this.gridHelper.dispose();`,
    `      this.gridHelper = undefined;`,
    `    }`,
    `    if (this.showGrid()) {`,
    `      this.gridHelper = new THREE.GridHelper(12, 12, 0x475569, 0x334155);`,
    `      this.gridHelper.position.y = -0.01;`,
    `      this.scene.add(this.gridHelper);`,
    `    }`,
    `    this.loadModel();`,
    `    this.resize();`,
    `  }`,
    `  private loadModel(): void {`,
    `    const url = this.modelUrl().trim();`,
    `    const scale = this.modelScale();`,
    `    const loadId = ++this.gltfLoadId;`,
    `    this.clearContentGroup();`,
    `    if (!url) { this.addFallback(); return; }`,
    `    new GLTFLoader().load(url, (gltf) => {`,
    `      if (loadId !== this.gltfLoadId) return;`,
    `      this.clearContentGroup();`,
    `      const model = gltf.scene.clone(true);`,
    `      model.scale.setScalar(scale);`,
    `      const bounds = new THREE.Box3().setFromObject(model);`,
    `      const center = bounds.getCenter(new THREE.Vector3());`,
    `      model.position.sub(center);`,
    `      model.position.y += (bounds.max.y - bounds.min.y) / 2;`,
    `      this.contentGroup.add(model);`,
    `    }, undefined, () => { if (loadId === this.gltfLoadId) this.addFallback(); });`,
    `  }`,
    `  private addFallback(): void {`,
    `    const mesh = new THREE.Mesh(`,
    `      new THREE.BoxGeometry(1.2, 1.2, 1.2),`,
    `      new THREE.MeshStandardMaterial({ color: '#64748b' }),`,
    `    );`,
    `    mesh.position.y = 0.6;`,
    `    this.contentGroup.add(mesh);`,
    `  }`,
    `  private clearContentGroup(): void {`,
    `    for (const child of [...this.contentGroup.children]) {`,
    `      this.contentGroup.remove(child);`,
    `      child.traverse((node) => {`,
    `        if (node instanceof THREE.Mesh) {`,
    `          node.geometry.dispose();`,
    `          const materials = Array.isArray(node.material) ? node.material : [node.material];`,
    `          materials.forEach((material) => material.dispose());`,
    `        }`,
    `      });`,
    `    }`,
    `  }`,
    `  private resize(): void {`,
    `    const host = this.host?.nativeElement;`,
    `    if (!host || !this.renderer || !this.camera) return;`,
    `    const width = Math.max(host.clientWidth, 1);`,
    `    const height = Math.max(host.clientHeight, 1);`,
    `    this.camera.aspect = width / height;`,
    `    this.camera.updateProjectionMatrix();`,
    `    this.renderer.setSize(width, height, false);`,
    `  }`,
    `  private startLoop(): void {`,
    `    const tick = () => {`,
    `      this.controls?.update();`,
    `      if (this.renderer && this.camera) this.renderer.render(this.scene, this.camera);`,
    `      this.animationId = requestAnimationFrame(tick);`,
    `    };`,
    `    tick();`,
    `  }`,
    `  private disposeRuntime(): void {`,
    `    this.gltfLoadId += 1;`,
    `    if (this.animationId !== undefined) cancelAnimationFrame(this.animationId);`,
    `    this.clearContentGroup();`,
    `    this.gridHelper?.dispose();`,
    `    this.controls?.dispose();`,
    `    this.renderer?.dispose();`,
    `    this.renderer?.domElement.remove();`,
    `  }`,
    `}`,
    ``,
  ]);
}

export function generateThreeGeoGlobe(className: string): string {
  const selector = selectorFromClass(className);
  return joinLines([
    `/** Requires: npm install three */`,
    `import {`,
    `  AfterViewInit,`,
    `  Component,`,
    `  ElementRef,`,
    `  OnDestroy,`,
    `  ViewChild,`,
    `  effect,`,
    `  input,`,
    `} from '@angular/core';`,
    `import * as THREE from 'three';`,
    `import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';`,
    `import type { DateRange, Row } from '../types';`,
    ``,
    `const DEFAULT_TEXTURE_URL =`,
    `  'https://unpkg.com/three-globe/example/img/earth-blue-marble.jpg';`,
    ``,
    `@Component({`,
    `  selector: '${selector}',`,
    `  standalone: true,`,
    `  template: \``,
    `    <section class="chart-card chart-card--3d" [id]="id()">`,
    `      <h3>{{ title() }}</h3>`,
    `      <div class="three-chart" [style.background]="backgroundColor()" #host></div>`,
    `    </section>`,
    `  \`,`,
    `})`,
    `export class ${className} implements AfterViewInit, OnDestroy {`,
    `  @ViewChild('host') host!: ElementRef<HTMLDivElement>;`,
    ``,
    `  id = input<string>();`,
    `  title = input('Geo Globe');`,
    `  textureUrl = input(DEFAULT_TEXTURE_URL);`,
    `  latField = input('lat');`,
    `  lngField = input('lng');`,
    `  labelField = input('name');`,
    `  globeRadius = input(2);`,
    `  backgroundColor = input('#0f172a');`,
    `  autoRotate = input(true);`,
    `  data = input.required<Row[]>();`,
    `  range = input<DateRange>();`,
    ``,
    `  private readonly scene = new THREE.Scene();`,
    `  private readonly contentGroup = new THREE.Group();`,
    `  private camera?: THREE.PerspectiveCamera;`,
    `  private renderer?: THREE.WebGLRenderer;`,
    `  private controls?: OrbitControls;`,
    `  private animationId?: number;`,
    `  private textureLoadId = 0;`,
    ``,
    `  constructor() {`,
    `    this.scene.add(this.contentGroup);`,
    `    effect(() => {`,
    `      this.data();`,
    `      this.range();`,
    `      this.textureUrl();`,
    `      this.latField();`,
    `      this.lngField();`,
    `      this.labelField();`,
    `      this.globeRadius();`,
    `      this.backgroundColor();`,
    `      this.autoRotate();`,
    `      this.rebuild();`,
    `    });`,
    `  }`,
    ``,
    `  ngAfterViewInit(): void {`,
    `    this.mount();`,
    `    this.rebuild();`,
    `  }`,
    ``,
    `  ngOnDestroy(): void {`,
    `    this.disposeRuntime();`,
    `  }`,
    ``,
    `  private mount(): void {`,
    `    const host = this.host?.nativeElement;`,
    `    if (!host) return;`,
    `    this.renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true });`,
    `    host.appendChild(this.renderer.domElement);`,
    `    this.camera = new THREE.PerspectiveCamera(45, 1, 0.1, 200);`,
    `    this.camera.position.set(0, 0, 7);`,
    `    this.camera.lookAt(0, 0, 0);`,
    `    this.controls = new OrbitControls(this.camera, this.renderer.domElement);`,
    `    this.controls.enableDamping = true;`,
    `    this.controls.minDistance = 4;`,
    `    this.controls.maxDistance = 40;`,
    `    this.scene.add(new THREE.AmbientLight(0xffffff, 0.65));`,
    `    const keyLight = new THREE.DirectionalLight(0xffffff, 1.1);`,
    `    keyLight.position.set(6, 10, 4);`,
    `    this.scene.add(keyLight);`,
    `    this.resize();`,
    `    this.startLoop();`,
    `  }`,
    ``,
    `  private rebuild(): void {`,
    `    if (!this.renderer || !this.camera) return;`,
    `    this.scene.background = new THREE.Color(this.backgroundColor());`,
    `    if (this.controls) this.controls.autoRotate = this.autoRotate();`,
    `    this.loadGlobe();`,
    `    this.resize();`,
    `  }`,
    ``,
    `  private loadGlobe(): void {`,
    `    const url = this.textureUrl().trim();`,
    `    const radius = this.globeRadius();`,
    `    const loadId = ++this.textureLoadId;`,
    `    this.clearContentGroup();`,
    `    const markers = mapGlobeMarkers(filterByRange(this.data(), this.range()), {`,
    `      latField: this.latField(),`,
    `      lngField: this.lngField(),`,
    `      labelField: this.labelField(),`,
    `    });`,
    `    const markerGeometry = new THREE.SphereGeometry(0.08, 10, 10);`,
    `    markers.forEach((marker, index) => {`,
    `      const position = latLngToGlobePosition(marker.lat, marker.lng, radius);`,
    `      const material = new THREE.MeshStandardMaterial({`,
    `        color: BAR_COLORS[index % BAR_COLORS.length],`,
    `      });`,
    `      const mesh = new THREE.Mesh(markerGeometry, material);`,
    `      mesh.position.set(position.x, position.y, position.z);`,
    `      this.contentGroup.add(mesh);`,
    `    });`,
    `    const addGlobe = (texture?: THREE.Texture) => {`,
    `      if (loadId !== this.textureLoadId) return;`,
    `      const globe = new THREE.Mesh(`,
    `        new THREE.SphereGeometry(radius, 48, 48),`,
    `        new THREE.MeshStandardMaterial({`,
    `          map: texture,`,
    `          color: texture ? '#ffffff' : '#1d4ed8',`,
    `        }),`,
    `      );`,
    `      this.contentGroup.add(globe);`,
    `    };`,
    `    if (!url) {`,
    `      addGlobe();`,
    `      return;`,
    `    }`,
    `    new THREE.TextureLoader().load(url, (texture) => addGlobe(texture), undefined, () => addGlobe());`,
    `  }`,
    ``,
    `  private clearContentGroup(): void {`,
    `    for (const child of [...this.contentGroup.children]) {`,
    `      this.contentGroup.remove(child);`,
    `      child.traverse((node) => {`,
    `        if (node instanceof THREE.Mesh) {`,
    `          node.geometry.dispose();`,
    `          const materials = Array.isArray(node.material) ? node.material : [node.material];`,
    `          materials.forEach((material) => material.dispose());`,
    `        }`,
    `      });`,
    `    }`,
    `  }`,
    ``,
    `  private resize(): void {`,
    `    const host = this.host?.nativeElement;`,
    `    if (!host || !this.renderer || !this.camera) return;`,
    `    const width = Math.max(host.clientWidth, 1);`,
    `    const height = Math.max(host.clientHeight, 1);`,
    `    this.camera.aspect = width / height;`,
    `    this.camera.updateProjectionMatrix();`,
    `    this.renderer.setSize(width, height, false);`,
    `  }`,
    ``,
    `  private startLoop(): void {`,
    `    const tick = () => {`,
    `      this.controls?.update();`,
    `      if (this.renderer && this.camera) this.renderer.render(this.scene, this.camera);`,
    `      this.animationId = requestAnimationFrame(tick);`,
    `    };`,
    `    tick();`,
    `  }`,
    ``,
    `  private disposeRuntime(): void {`,
    `    this.textureLoadId += 1;`,
    `    if (this.animationId !== undefined) cancelAnimationFrame(this.animationId);`,
    `    this.clearContentGroup();`,
    `    this.controls?.dispose();`,
    `    this.renderer?.dispose();`,
    `    this.renderer?.domElement.remove();`,
    `  }`,
    `}`,
    ``,
    ...threeVisualHelpers(),
    ...globeVisualHelpers(),
  ]);
}
