import type { ExportIR, IRDataSource, IRRoute } from '@dashbuilder/core';
import type { CollectionResource } from './types';

export function joinLines(lines: string[]): string {
  return `${lines.filter((line) => line !== undefined).join('\n')}\n`;
}

export function assertSafeCollectionName(collection: string): string {
  if (!/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(collection)) {
    throw new Error(`Unsafe MongoDB collection identifier: ${collection}`);
  }
  return collection;
}

export function resolveMongoSources(ir: ExportIR): IRDataSource[] {
  return ir.dataSources.filter((source) => source.type === 'infra.mongodb');
}

export function resolvePrimaryConnectionEnvKey(ir: ExportIR): string {
  const mongo = resolveMongoSources(ir)[0];
  return mongo?.connectionEnvKey ?? 'MONGODB_URI';
}

export function routeResourceName(route: IRRoute): string {
  const normalized = route.path.replace(/^\/+|\/+$/g, '');
  const segments = normalized.split('/').filter(Boolean);
  return segments[segments.length - 1] ?? 'records';
}

export function resolveCollectionResources(ir: ExportIR): CollectionResource[] {
  const mongoSources = resolveMongoSources(ir);
  const defaultCollection = mongoSources[0]?.collection ?? 'records';

  return ir.routes.map((route) => {
    const resourceName = routeResourceName(route);
    const collectionName = assertSafeCollectionName(
      mongoSources.find((source) => source.collection)?.collection ||
        defaultCollection ||
        'records',
    );

    return {
      routeId: route.id,
      resourceName,
      collectionName,
      method: route.method,
    };
  });
}

export function generateEnvExample(ir: ExportIR): string {
  const lines = ['# Generated by DashBuilder — fill in values before running queries', ''];

  if (ir.envVars.length === 0) {
    lines.push('MONGODB_URI=mongodb://user:password@localhost:27017/mydb');
  } else {
    for (const envVar of ir.envVars) {
      const example =
        envVar.example ??
        (envVar.key === 'MONGODB_URI'
          ? 'mongodb://user:password@localhost:27017/mydb'
          : 'your-value-here');
      lines.push(`${envVar.key}=${example}`);
    }
  }

  return joinLines(lines);
}
