import type { ExportIR, IRDataSource, IRRoute } from '@dashbuilder/core';
import type { TableResource } from './types';

export function joinLines(lines: string[]): string {
  return `${lines.filter((line) => line !== undefined).join('\n')}\n`;
}

export function assertSafeTableName(table: string): string {
  if (!/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(table)) {
    throw new Error(`Unsafe Supabase table identifier: ${table}`);
  }
  return table;
}

export function resolveSupabaseSources(ir: ExportIR): IRDataSource[] {
  return ir.dataSources.filter((source) => source.type === 'infra.supabase');
}

export function resolveUrlEnvKey(ir: ExportIR): string {
  const supabase = resolveSupabaseSources(ir)[0];
  return supabase?.connectionEnvKey ?? 'SUPABASE_URL';
}

export function resolveAnonKeyEnvKey(ir: ExportIR): string {
  const supabase = resolveSupabaseSources(ir)[0];
  return supabase?.anonKeyEnvKey ?? 'SUPABASE_ANON_KEY';
}

export function routeResourceName(route: IRRoute): string {
  const normalized = route.path.replace(/^\/+|\/+$/g, '');
  const segments = normalized.split('/').filter(Boolean);
  return segments[segments.length - 1] ?? 'records';
}

export function resolveTableResources(ir: ExportIR): TableResource[] {
  const supabaseSources = resolveSupabaseSources(ir);
  const defaultTable = supabaseSources[0]?.table ?? 'records';

  return ir.routes.map((route) => {
    const resourceName = routeResourceName(route);
    const tableName = assertSafeTableName(
      supabaseSources.find((source) => source.table)?.table || defaultTable || 'records',
    );

    return {
      routeId: route.id,
      resourceName,
      tableName,
      method: route.method,
    };
  });
}

export function generateEnvExample(ir: ExportIR, urlEnvKey: string, anonKeyEnvKey: string): string {
  const lines = ['# Generated by DashBuilder — fill in values before running queries', ''];

  if (ir.envVars.length === 0) {
    lines.push(
      `${urlEnvKey}=https://your-project.supabase.co`,
      `${anonKeyEnvKey}=your-anon-key-here`,
    );
  } else {
    for (const envVar of ir.envVars) {
      const example =
        envVar.example ??
        (envVar.key === urlEnvKey
          ? 'https://your-project.supabase.co'
          : envVar.key === anonKeyEnvKey
            ? 'your-anon-key-here'
            : 'your-value-here');
      lines.push(`${envVar.key}=${example}`);
    }
  }

  return joinLines(lines);
}
