import type { IRComponent } from '@dashbuilder/core';
import { ReactExportError } from './types';
import { joinLines } from './utils';

const SUPPORTED_TYPES = new Set([
  'visual.input.text',
  'visual.input.select',
  'visual.input.number',
  'visual.input.checkbox',
  'visual.input.textarea',
  'visual.input.date-range',
  'domain.time-preset',
  'visual.table',
  'visual.detail',
  'visual.skeleton',
  'visual.kpi',
  'visual.chart.line',
  'visual.chart.bar',
  'visual.chart.pie',
  'visual.display.3d-bar-chart',
  'visual.display.3d-scatter',
  'visual.display.3d-scene',
  'visual.display.3d-gltf-model',
  'visual.display.3d-geo-globe',
  'domain.role-gate',
  'domain.person-invite',
  'domain.role-assign',
  'logic.timer',
]);

export function generateComponentFile(component: IRComponent, exportName: string): string {
  if (!SUPPORTED_TYPES.has(component.type)) {
    throw new ReactExportError(`Unsupported React export component type: ${component.type}`);
  }

  switch (component.type) {
    case 'visual.input.text':
      return generateTextInput(exportName);
    case 'visual.input.select':
      return generateSelectInput(exportName);
    case 'visual.input.number':
      return generateNumberInput(exportName);
    case 'visual.input.checkbox':
      return generateCheckboxInput(exportName);
    case 'visual.input.textarea':
      return generateTextareaInput(exportName);
    case 'visual.input.date-range':
      return generateDateRangeFilter(exportName);
    case 'domain.time-preset':
      return generateTimePreset(exportName);
    case 'visual.table':
      return generateDataTable(exportName);
    case 'visual.detail':
      return generateDetailPanel(exportName);
    case 'visual.skeleton':
      return generateSkeleton(exportName);
    case 'visual.kpi':
      return generateKpiCard(exportName);
    case 'visual.chart.line':
      return generateLineChart(exportName);
    case 'visual.chart.bar':
      return generateBarChart(exportName);
    case 'visual.chart.pie':
      return generatePieChart(exportName);
    case 'visual.display.3d-bar-chart':
      return generateThreeBarChart(exportName);
    case 'visual.display.3d-scatter':
      return generateThreeScatterPlot(exportName);
    case 'visual.display.3d-scene':
      return generateThreeScenePointCloud(exportName);
    case 'visual.display.3d-gltf-model':
      return generateThreeGltfModel(exportName);
    case 'visual.display.3d-geo-globe':
      return generateThreeGeoGlobe(exportName);
    case 'domain.role-gate':
      return generateRoleGate(exportName);
    case 'domain.person-invite':
      return generatePersonInvite(exportName);
    case 'domain.role-assign':
      return generateRoleAssign(exportName);
    case 'logic.timer':
      return generateTimer(exportName);
    default:
      throw new ReactExportError(`Missing React template for ${component.type}`);
  }
}

function generateTextInput(name: string): string {
  return joinLines([
    `'use client';`,
    ``,
    `export interface ${name}Props {`,
    `  id?: string;`,
    `  placeholder?: string;`,
    `  required?: boolean;`,
    `  value?: string;`,
    `  onChange?: (value: string) => void;`,
    `}`,
    ``,
    `export function ${name}({ id, placeholder = '', required = false, value = '', onChange }: ${name}Props) {`,
    `  return (`,
    `    <label className="field" htmlFor={id}>`,
    `      <input`,
    `        id={id}`,
    `        className="input"`,
    `        type="text"`,
    `        placeholder={placeholder}`,
    `        required={required}`,
    `        value={value}`,
    `        onChange={(event) => onChange?.(event.target.value)}`,
    `      />`,
    `    </label>`,
    `  );`,
    `}`,
    ``,
  ]);
}

function generateSelectInput(name: string): string {
  return joinLines([
    `'use client';`,
    ``,
    `import type { Row } from '../types';`,
    ``,
    `export interface ${name}Props {`,
    `  id?: string;`,
    `  placeholder?: string;`,
    `  options?: Row[];`,
    `  value?: string;`,
    `  onChange?: (value: string) => void;`,
    `}`,
    ``,
    `export function ${name}({ id, placeholder = 'Select…', options = [], value = '', onChange }: ${name}Props) {`,
    `  return (`,
    `    <label className="field" htmlFor={id}>`,
    `      <select`,
    `        id={id}`,
    `        className="select"`,
    `        value={value}`,
    `        onChange={(event) => onChange?.(event.target.value)}`,
    `      >`,
    `        <option value="">{placeholder}</option>`,
    `        {options.map((option, index) => (`,
    `          <option key={String(option.id ?? index)} value={String(option.id ?? option.label ?? index)}>`,
    `            {String(option.label ?? option.id ?? index)}`,
    `          </option>`,
    `        ))}`,
    `      </select>`,
    `    </label>`,
    `  );`,
    `}`,
    ``,
  ]);
}

function generateNumberInput(name: string): string {
  return joinLines([
    `'use client';`,
    ``,
    `export interface ${name}Props {`,
    `  id?: string;`,
    `  placeholder?: string;`,
    `  required?: boolean;`,
    `  min?: number;`,
    `  max?: number;`,
    `  step?: number;`,
    `  value?: number;`,
    `  onChange?: (value: number) => void;`,
    `}`,
    ``,
    `export function ${name}({`,
    `  id,`,
    `  placeholder = '',`,
    `  required = false,`,
    `  min = 0,`,
    `  max = 100,`,
    `  step = 1,`,
    `  value = 0,`,
    `  onChange,`,
    `}: ${name}Props) {`,
    `  return (`,
    `    <label className="field" htmlFor={id}>`,
    `      <input`,
    `        id={id}`,
    `        className="input"`,
    `        type="number"`,
    `        placeholder={placeholder}`,
    `        required={required}`,
    `        min={min}`,
    `        max={max}`,
    `        step={step}`,
    `        value={value}`,
    `        onChange={(event) => onChange?.(Number(event.target.value))}`,
    `      />`,
    `    </label>`,
    `  );`,
    `}`,
    ``,
  ]);
}

function generateCheckboxInput(name: string): string {
  return joinLines([
    `'use client';`,
    ``,
    `export interface ${name}Props {`,
    `  id?: string;`,
    `  label?: string;`,
    `  defaultChecked?: boolean;`,
    `  value?: boolean;`,
    `  onChange?: (value: boolean) => void;`,
    `}`,
    ``,
    `export function ${name}({`,
    `  id,`,
    `  label = '',`,
    `  defaultChecked = false,`,
    `  value = defaultChecked,`,
    `  onChange,`,
    `}: ${name}Props) {`,
    `  return (`,
    `    <label className="field field--checkbox" htmlFor={id}>`,
    `      <input`,
    `        id={id}`,
    `        className="checkbox"`,
    `        type="checkbox"`,
    `        checked={value}`,
    `        onChange={(event) => onChange?.(event.target.checked)}`,
    `      />`,
    `      {label ? <span>{label}</span> : null}`,
    `    </label>`,
    `  );`,
    `}`,
    ``,
  ]);
}

function generateTextareaInput(name: string): string {
  return joinLines([
    `'use client';`,
    ``,
    `export interface ${name}Props {`,
    `  id?: string;`,
    `  placeholder?: string;`,
    `  required?: boolean;`,
    `  rows?: number;`,
    `  value?: string;`,
    `  onChange?: (value: string) => void;`,
    `}`,
    ``,
    `export function ${name}({`,
    `  id,`,
    `  placeholder = '',`,
    `  required = false,`,
    `  rows = 4,`,
    `  value = '',`,
    `  onChange,`,
    `}: ${name}Props) {`,
    `  return (`,
    `    <label className="field" htmlFor={id}>`,
    `      <textarea`,
    `        id={id}`,
    `        className="textarea"`,
    `        placeholder={placeholder}`,
    `        required={required}`,
    `        rows={rows}`,
    `        value={value}`,
    `        onChange={(event) => onChange?.(event.target.value)}`,
    `      />`,
    `    </label>`,
    `  );`,
    `}`,
    ``,
  ]);
}

function generateDateRangeFilter(name: string): string {
  return joinLines([
    `'use client';`,
    ``,
    `import type { DateRange } from '../types';`,
    ``,
    `export interface ${name}Props {`,
    `  id?: string;`,
    `  preset?: string;`,
    `  value?: DateRange;`,
    `  onChange?: (range: DateRange) => void;`,
    `}`,
    ``,
    `export function ${name}({ id, preset = 'last-7-days', value, onChange }: ${name}Props) {`,
    `  const current = value ?? defaultRangeForPreset(preset);`,
    ``,
    `  return (`,
    `    <div className="date-range" id={id}>`,
    `      <label className="field">`,
    `        <span>Start</span>`,
    `        <input`,
    `          className="input"`,
    `          type="date"`,
    `          value={current.start}`,
    `          onChange={(event) => onChange?.({ ...current, start: event.target.value })}`,
    `        />`,
    `      </label>`,
    `      <label className="field">`,
    `        <span>End</span>`,
    `        <input`,
    `          className="input"`,
    `          type="date"`,
    `          value={current.end}`,
    `          onChange={(event) => onChange?.({ ...current, end: event.target.value })}`,
    `        />`,
    `      </label>`,
    `    </div>`,
    `  );`,
    `}`,
    ``,
    `function defaultRangeForPreset(preset: string): DateRange {`,
    `  const end = new Date();`,
    `  const start = new Date(end);`,
    `  if (preset === 'last-30-days') {`,
    `    start.setDate(end.getDate() - 30);`,
    `  } else if (preset === 'qtd') {`,
    `    start.setMonth(Math.floor(end.getMonth() / 3) * 3, 1);`,
    `  } else {`,
    `    start.setDate(end.getDate() - 7);`,
    `  }`,
    `  return { start: formatDate(start), end: formatDate(end) };`,
    `}`,
    ``,
    `function formatDate(date: Date): string {`,
    `  return date.toISOString().slice(0, 10);`,
    `}`,
    ``,
  ]);
}

function generateTimePreset(name: string): string {
  return joinLines([
    `'use client';`,
    ``,
    `import { useState } from 'react';`,
    `import type { DateRange } from '../types';`,
    ``,
    `const PRESET_OPTIONS = [`,
    `  { id: 'last-7-days', label: 'Last 7 days' },`,
    `  { id: 'last-30-days', label: 'Last 30 days' },`,
    `  { id: 'qtd', label: 'Quarter to date' },`,
    `] as const;`,
    ``,
    `export interface ${name}Props {`,
    `  id?: string;`,
    `  label?: string;`,
    `  defaultPreset?: string;`,
    `  value?: DateRange;`,
    `  onChange?: (range: DateRange) => void;`,
    `}`,
    ``,
    `export function ${name}({`,
    `  id,`,
    `  label = 'Period',`,
    `  defaultPreset = 'last-7-days',`,
    `  value,`,
    `  onChange,`,
    `}: ${name}Props) {`,
    `  const [activePreset, setActivePreset] = useState(defaultPreset);`,
    ``,
    `  return (`,
    `    <div className="time-preset" id={id}>`,
    `      <span className="time-preset__label">{label}</span>`,
    `      <div className="time-preset__buttons">`,
    `        {PRESET_OPTIONS.map((preset) => (`,
    `          <button`,
    `            key={preset.id}`,
    `            type="button"`,
    `            className={`,
    `              activePreset === preset.id`,
    `                ? 'time-preset__button time-preset__button--active'`,
    `                : 'time-preset__button'`,
    `            }`,
    `            onClick={() => {`,
    `              setActivePreset(preset.id);`,
    `              onChange?.(defaultRangeForPreset(preset.id));`,
    `            }}`,
    `          >`,
    `            {preset.label}`,
    `          </button>`,
    `        ))}`,
    `      </div>`,
    `    </div>`,
    `  );`,
    `}`,
    ``,
    `function defaultRangeForPreset(preset: string): DateRange {`,
    `  const end = new Date();`,
    `  const start = new Date(end);`,
    `  if (preset === 'last-30-days') {`,
    `    start.setDate(end.getDate() - 30);`,
    `  } else if (preset === 'qtd') {`,
    `    start.setMonth(Math.floor(end.getMonth() / 3) * 3, 1);`,
    `  } else {`,
    `    start.setDate(end.getDate() - 7);`,
    `  }`,
    `  return { start: formatDate(start), end: formatDate(end) };`,
    `}`,
    ``,
    `function formatDate(date: Date): string {`,
    `  return date.toISOString().slice(0, 10);`,
    `}`,
    ``,
  ]);
}

function generateDataTable(name: string): string {
  return joinLines([
    `'use client';`,
    ``,
    `import type { DateRange, Row } from '../types';`,
    ``,
    `export interface ${name}Props {`,
    `  id?: string;`,
    `  data: Row[];`,
    `  filter?: DateRange;`,
    `  pageSize?: number;`,
    `  sortable?: boolean;`,
    `  filterable?: boolean;`,
    `  selectedRow?: Row;`,
    `  onSelectRow?: (row: Row) => void;`,
    `}`,
    ``,
    `export function ${name}({ id, data, filter, pageSize = 25, sortable = true, filterable = true, selectedRow, onSelectRow }: ${name}Props) {`,
    `  const rows = filterRows(data, filter).slice(0, pageSize);`,
    `  const columns = rows.length > 0 ? Object.keys(rows[0]) : ['id', 'label', 'value'];`,
    ``,
    `  return (`,
    `    <section className="table-card" id={id} data-sortable={sortable} data-filterable={filterable}>`,
    `      <table className="table">`,
    `        <thead>`,
    `          <tr>`,
    `            {columns.map((column) => (`,
    `              <th key={column}>{column}</th>`,
    `            ))}`,
    `          </tr>`,
    `        </thead>`,
    `        <tbody>`,
    `          {rows.map((row, index) => (`,
    `            <tr`,
    `              key={String(row.id ?? index)}`,
    `              className={selectedRow?.id === row.id ? 'table-row table-row--selected' : 'table-row'}`,
    `              onClick={() => onSelectRow?.(row)}`,
    `            >`,
    `              {columns.map((column) => (`,
    `                <td key={column}>{String(row[column] ?? '')}</td>`,
    `              ))}`,
    `            </tr>`,
    `          ))}`,
    `        </tbody>`,
    `      </table>`,
    `    </section>`,
    `  );`,
    `}`,
    ``,
    `function filterRows(data: Row[], filter?: DateRange): Row[] {`,
    `  if (!filter) {`,
    `    return data;`,
    `  }`,
    `  return data.filter((row) => {`,
    `    const value = String(row.date ?? row.createdAt ?? '');`,
    `    if (!value) {`,
    `      return true;`,
    `    }`,
    `    return value >= filter.start && value <= filter.end;`,
    `  });`,
    `}`,
    ``,
  ]);
}

function generateDetailPanel(name: string): string {
  return joinLines([
    `'use client';`,
    ``,
    `import type { Row } from '../types';`,
    ``,
    `export interface ${name}Props {`,
    `  id?: string;`,
    `  title?: string;`,
    `  emptyMessage?: string;`,
    `  row?: Row;`,
    `}`,
    ``,
    `export function ${name}({`,
    `  id,`,
    `  title = 'Details',`,
    `  emptyMessage = 'Select a row to view details',`,
    `  row,`,
    `}: ${name}Props) {`,
    `  const fields = row ? Object.entries(row) : [];`,
    ``,
    `  return (`,
    `    <section className="detail-panel" id={id}>`,
    `      <h3>{title}</h3>`,
    `      {fields.length === 0 ? (`,
    `        <p className="detail-panel__empty">{emptyMessage}</p>`,
    `      ) : (`,
    `        <dl className="detail-panel__fields">`,
    `          {fields.map(([key, value]) => (`,
    `            <div key={key} className="detail-panel__field">`,
    `              <dt>{key}</dt>`,
    `              <dd>{String(value ?? '')}</dd>`,
    `            </div>`,
    `          ))}`,
    `        </dl>`,
    `      )}`,
    `    </section>`,
    `  );`,
    `}`,
    ``,
  ]);
}

function generateSkeleton(name: string): string {
  return joinLines([
    `'use client';`,
    ``,
    `export interface ${name}Props {`,
    `  id?: string;`,
    `  loading?: boolean;`,
    `  variant?: 'table' | 'chart' | 'kpi' | 'card';`,
    `  lines?: number;`,
    `}`,
    ``,
    `export function ${name}({ id, loading = true, variant = 'table', lines = 4 }: ${name}Props) {`,
    `  if (!loading) {`,
    `    return null;`,
    `  }`,
    ``,
    `  const count = Math.max(1, Math.min(lines, 8));`,
    ``,
    `  if (variant === 'chart') {`,
    `    return (`,
    `      <div className={\`skeleton skeleton--\${variant}\`} id={id} aria-busy="true">`,
    `        <div className="skeleton__chart-block" />`,
    `        <div className="skeleton__legend">`,
    `          {Array.from({ length: count }).map((_, index) => (`,
    `            <span key={index} className="skeleton__line skeleton__line--short" />`,
    `          ))}`,
    `        </div>`,
    `      </div>`,
    `    );`,
    `  }`,
    ``,
    `  if (variant === 'kpi') {`,
    `    return (`,
    `      <div className={\`skeleton skeleton--\${variant}\`} id={id} aria-busy="true">`,
    `        <span className="skeleton__line skeleton__line--title" />`,
    `        <span className="skeleton__line skeleton__line--value" />`,
    `      </div>`,
    `    );`,
    `  }`,
    ``,
    `  return (`,
    `    <div className={\`skeleton skeleton--\${variant}\`} id={id} aria-busy="true">`,
    `      {Array.from({ length: count }).map((_, index) => (`,
    `        <span key={index} className="skeleton__line" />`,
    `      ))}`,
    `    </div>`,
    `  );`,
    `}`,
    ``,
  ]);
}

function generateKpiCard(name: string): string {
  return joinLines([
    `'use client';`,
    ``,
    `export interface ${name}Props {`,
    `  id?: string;`,
    `  title?: string;`,
    `  format?: 'number' | 'currency' | 'percent';`,
    `  value?: number;`,
    `}`,
    ``,
    `export function ${name}({ id, title = 'Metric', format = 'number', value = 0 }: ${name}Props) {`,
    `  return (`,
    `    <article className="kpi-card" id={id}>`,
    `      <h3>{title}</h3>`,
    `      <p className="kpi-value">{formatValue(value, format)}</p>`,
    `    </article>`,
    `  );`,
    `}`,
    ``,
    `function formatValue(value: number, format: ${name}Props['format']): string {`,
    `  if (format === 'currency') {`,
    `    return new Intl.NumberFormat(undefined, { style: 'currency', currency: 'USD' }).format(value);`,
    `  }`,
    `  if (format === 'percent') {`,
    `    return new Intl.NumberFormat(undefined, { style: 'percent', maximumFractionDigits: 1 }).format(value / 100);`,
    `  }`,
    `  return new Intl.NumberFormat().format(value);`,
    `}`,
    ``,
  ]);
}

function generateLineChart(name: string): string {
  return joinLines([
    `'use client';`,
    ``,
    `import type { DateRange, Row } from '../types';`,
    ``,
    `export interface ${name}Props {`,
    `  id?: string;`,
    `  title?: string;`,
    `  xField?: string;`,
    `  yField?: string;`,
    `  data: Row[];`,
    `  range?: DateRange;`,
    `}`,
    ``,
    `export function ${name}({ id, title = 'Chart', xField = 'date', yField = 'value', data, range }: ${name}Props) {`,
    `  const points = filterByRange(data, range);`,
    `  const max = Math.max(...points.map((row) => Number(row[yField] ?? 0)), 1);`,
    ``,
    `  return (`,
    `    <section className="chart-card" id={id}>`,
    `      <h3>{title}</h3>`,
    `      <svg className="line-chart" viewBox="0 0 320 120" role="img" aria-label={title}>`,
    `        <polyline`,
    `          fill="none"`,
    `          stroke="currentColor"`,
    `          strokeWidth="2"`,
    `          points={points`,
    `            .map((row, index) => {`,
    `              const x = (index / Math.max(points.length - 1, 1)) * 300 + 10;`,
    `              const y = 110 - (Number(row[yField] ?? 0) / max) * 90;`,
    `              return \`\${x},\${y}\`;`,
    `            })`,
    `            .join(' ')}`,
    `        />`,
    `      </svg>`,
    `      <p className="chart-meta">{points.length} points · x={xField} · y={yField}</p>`,
    `    </section>`,
    `  );`,
    `}`,
    ``,
    `function filterByRange(data: Row[], range?: DateRange): Row[] {`,
    `  if (!range) {`,
    `    return data;`,
    `  }`,
    `  return data.filter((row) => {`,
    `    const value = String(row.date ?? row.createdAt ?? '');`,
    `    if (!value) {`,
    `      return true;`,
    `    }`,
    `    return value >= range.start && value <= range.end;`,
    `  });`,
    `}`,
    ``,
  ]);
}

function generateBarChart(name: string): string {
  return joinLines([
    `'use client';`,
    ``,
    `import type { DateRange, Row } from '../types';`,
    ``,
    `export interface ${name}Props {`,
    `  id?: string;`,
    `  title?: string;`,
    `  data: Row[];`,
    `  range?: DateRange;`,
    `}`,
    ``,
    `export function ${name}({ id, title = 'Chart', data, range }: ${name}Props) {`,
    `  const points = filterByRange(data, range);`,
    `  const max = Math.max(...points.map((row) => Number(row.value ?? 0)), 1);`,
    ``,
    `  return (`,
    `    <section className="chart-card" id={id}>`,
    `      <h3>{title}</h3>`,
    `      <div className="bar-chart">`,
    `        {points.map((row, index) => (`,
    `          <div`,
    `            key={String(row.id ?? index)}`,
    `            className="bar"`,
    `            style={{ height: \`\${(Number(row.value ?? 0) / max) * 100}%\` }}`,
    `            title={String(row.label ?? row.id ?? index)}`,
    `          />`,
    `        ))}`,
    `      </div>`,
    `    </section>`,
    `  );`,
    `}`,
    ``,
    `function filterByRange(data: Row[], range?: DateRange): Row[] {`,
    `  if (!range) {`,
    `    return data;`,
    `  }`,
    `  return data.filter((row) => {`,
    `    const value = String(row.date ?? row.createdAt ?? '');`,
    `    if (!value) {`,
    `      return true;`,
    `    }`,
    `    return value >= range.start && value <= range.end;`,
    `  });`,
    `}`,
    ``,
  ]);
}

function generateThreeBarChart(name: string): string {
  return joinLines([
    `'use client';`,
    ``,
    `/** Requires: npm install three @react-three/fiber @react-three/drei */`,
    `import { Canvas } from '@react-three/fiber';`,
    `import { OrbitControls } from '@react-three/drei';`,
    `import type { DateRange, Row } from '../types';`,
    ``,
    `export interface ${name}Props {`,
    `  id?: string;`,
    `  title?: string;`,
    `  xField?: string;`,
    `  yField?: string;`,
    `  backgroundColor?: string;`,
    `  autoRotate?: boolean;`,
    `  data: Row[];`,
    `  range?: DateRange;`,
    `}`,
    ``,
    `export function ${name}({`,
    `  id,`,
    `  title = '3D Bar Chart',`,
    `  xField = 'label',`,
    `  yField = 'value',`,
    `  backgroundColor = '#0f172a',`,
    `  autoRotate = false,`,
    `  data,`,
    `  range,`,
    `}: ${name}Props) {`,
    `  const points = filterByRange(data, range);`,
    `  const max = Math.max(...points.map((row) => Number(row[yField] ?? 0)), 1);`,
    `  const spacing = 1.4;`,
    `  const offset = ((points.length - 1) * spacing) / 2;`,
    ``,
    `  return (`,
    `    <section className="chart-card chart-card--3d" id={id}>`,
    `      <h3>{title}</h3>`,
    `      <div className="three-chart" style={{ background: backgroundColor }}>`,
    `        <Canvas camera={{ position: [8, 6, 8], fov: 45 }}>`,
    `          <color attach="background" args={[backgroundColor]} />`,
    `          <ambientLight intensity={0.65} />`,
    `          <directionalLight position={[6, 10, 4]} intensity={1.1} />`,
    `          {points.map((row, index) => {`,
    `            const value = Number(row[yField] ?? 0);`,
    `            const height = Math.max(0.2, (value / max) * 4);`,
    `            return (`,
    `              <mesh key={String(row.id ?? index)} position={[index * spacing - offset, height / 2, 0]}>`,
    `                <boxGeometry args={[0.9, height, 0.9]} />`,
    `                <meshStandardMaterial color={BAR_COLORS[index % BAR_COLORS.length]} />`,
    `              </mesh>`,
    `            );`,
    `          })}`,
    `          <OrbitControls autoRotate={autoRotate} minDistance={4} maxDistance={40} />`,
    `        </Canvas>`,
    `      </div>`,
    `    </section>`,
    `  );`,
    `}`,
    ``,
    `const BAR_COLORS = ['#38bdf8', '#818cf8', '#34d399', '#fbbf24', '#f472b6', '#fb7185'];`,
    ``,
    `function filterByRange(data: Row[], range?: DateRange): Row[] {`,
    `  if (!range) {`,
    `    return data;`,
    `  }`,
    `  return data.filter((row) => {`,
    `    const value = String(row.date ?? row.createdAt ?? '');`,
    `    if (!value) {`,
    `      return true;`,
    `    }`,
    `    return value >= range.start && value <= range.end;`,
    `  });`,
    `}`,
    ``,
  ]);
}

function generateThreeScatterPlot(name: string): string {
  return joinLines([
    `'use client';`,
    ``,
    `/** Requires: npm install three @react-three/fiber @react-three/drei */`,
    `import { Canvas } from '@react-three/fiber';`,
    `import { OrbitControls } from '@react-three/drei';`,
    `import type { DateRange, Row } from '../types';`,
    ``,
    `export interface ${name}Props {`,
    `  id?: string;`,
    `  title?: string;`,
    `  xField?: string;`,
    `  yField?: string;`,
    `  zField?: string;`,
    `  backgroundColor?: string;`,
    `  autoRotate?: boolean;`,
    `  data: Row[];`,
    `  range?: DateRange;`,
    `}`,
    ``,
    `export function ${name}({`,
    `  id,`,
    `  title = '3D Scatter Plot',`,
    `  xField = 'date',`,
    `  yField = 'amount',`,
    `  zField = 'id',`,
    `  backgroundColor = '#0f172a',`,
    `  autoRotate = false,`,
    `  data,`,
    `  range,`,
    `}: ${name}Props) {`,
    `  const rows = filterByRange(data, range);`,
    `  const points = mapScatterPoints(rows, { xField, yField, zField });`,
    ``,
    `  return (`,
    `    <section className="chart-card chart-card--3d" id={id}>`,
    `      <h3>{title}</h3>`,
    `      <div className="three-chart" style={{ background: backgroundColor }}>`,
    `        <Canvas camera={{ position: [8, 6, 8], fov: 45 }}>`,
    `          <color attach="background" args={[backgroundColor]} />`,
    `          <ambientLight intensity={0.65} />`,
    `          <directionalLight position={[6, 10, 4]} intensity={1.1} />`,
    `          {points.map((point, index) => (`,
    `            <mesh key={point.label ?? index} position={[point.x, point.y, point.z]}>`,
    `              <sphereGeometry args={[0.18, 16, 16]} />`,
    `              <meshStandardMaterial color={BAR_COLORS[index % BAR_COLORS.length]} />`,
    `            </mesh>`,
    `          ))}`,
    `          <OrbitControls autoRotate={autoRotate} minDistance={4} maxDistance={40} />`,
    `        </Canvas>`,
    `      </div>`,
    `    </section>`,
    `  );`,
    `}`,
    ``,
    `const BAR_COLORS = ['#38bdf8', '#818cf8', '#34d399', '#fbbf24', '#f472b6', '#fb7185'];`,
    ``,
    `interface ScatterPoint {`,
    `  x: number;`,
    `  y: number;`,
    `  z: number;`,
    `  label?: string;`,
    `}`,
    ``,
    `function mapScatterPoints(`,
    `  rows: Row[],`,
    `  fields: { xField: string; yField: string; zField: string },`,
    `): ScatterPoint[] {`,
    `  if (rows.length === 0) {`,
    `    return [`,
    `      { x: -2, y: 1.2, z: -2, label: 'A' },`,
    `      { x: 0, y: 2.4, z: 1, label: 'B' },`,
    `      { x: 2, y: 0.8, z: 2, label: 'C' },`,
    `    ];`,
    `  }`,
    ``,
    `  const raw = rows.slice(0, 48).map((row, index) => ({`,
    `    x: readNumericField(row, fields.xField, index),`,
    `    y: readNumericField(row, fields.yField, index + 1),`,
    `    z: readNumericField(row, fields.zField, index * 0.75 + 1),`,
    `    label: String(row.name ?? row.id ?? index + 1),`,
    `  }));`,
    ``,
    `  return normalizeScatterPoints(raw);`,
    `}`,
    ``,
    `function readNumericField(row: Row, field: string, fallback: number): number {`,
    `  const value = row[field];`,
    `  if (typeof value === 'number' && Number.isFinite(value)) {`,
    `    return value;`,
    `  }`,
    `  if (typeof value === 'string') {`,
    `    const parsed = Number(value);`,
    `    if (Number.isFinite(parsed)) {`,
    `      return parsed;`,
    `    }`,
    `    const timestamp = Date.parse(value);`,
    `    if (Number.isFinite(timestamp)) {`,
    `      return timestamp / 86400000;`,
    `    }`,
    `  }`,
    `  return fallback;`,
    `}`,
    ``,
    `function normalizeScatterPoints(points: ScatterPoint[]): ScatterPoint[] {`,
    `  const normalizeAxis = (values: number[], spread = 8, floor = 0.2) => {`,
    `    const min = Math.min(...values);`,
    `    const max = Math.max(...values);`,
    `    const span = max - min || 1;`,
    `    return values.map((value) => ((value - min) / span) * spread + floor);`,
    `  };`,
    ``,
    `  const xs = normalizeAxis(`,
    `    points.map((point) => point.x),`,
    `    8,`,
    `    -4,`,
    `  );`,
    `  const ys = normalizeAxis(points.map((point) => point.y));`,
    `  const zs = normalizeAxis(`,
    `    points.map((point) => point.z),`,
    `    8,`,
    `    -4,`,
    `  );`,
    ``,
    `  return points.map((point, index) => ({`,
    `    ...point,`,
    `    x: xs[index] ?? point.x,`,
    `    y: ys[index] ?? point.y,`,
    `    z: zs[index] ?? point.z,`,
    `  }));`,
    `}`,
    ``,
    `function filterByRange(data: Row[], range?: DateRange): Row[] {`,
    `  if (!range) {`,
    `    return data;`,
    `  }`,
    `  return data.filter((row) => {`,
    `    const value = String(row.date ?? row.createdAt ?? '');`,
    `    if (!value) {`,
    `      return true;`,
    `    }`,
    `    return value >= range.start && value <= range.end;`,
    `  });`,
    `}`,
    ``,
  ]);
}

function generateThreeScenePointCloud(name: string): string {
  return joinLines([
    `'use client';`,
    ``,
    `/** Requires: npm install three @react-three/fiber @react-three/drei */`,
    `import { Canvas } from '@react-three/fiber';`,
    `import { Grid, OrbitControls } from '@react-three/drei';`,
    `import type { DateRange, Row } from '../types';`,
    ``,
    `export interface ${name}Props {`,
    `  id?: string;`,
    `  title?: string;`,
    `  xField?: string;`,
    `  yField?: string;`,
    `  zField?: string;`,
    `  backgroundColor?: string;`,
    `  autoRotate?: boolean;`,
    `  showGrid?: boolean;`,
    `  data: Row[];`,
    `  range?: DateRange;`,
    `}`,
    ``,
    `export function ${name}({`,
    `  id,`,
    `  title = '3D Scene',`,
    `  xField = 'date',`,
    `  yField = 'amount',`,
    `  zField = 'id',`,
    `  backgroundColor = '#0f172a',`,
    `  autoRotate = false,`,
    `  showGrid = true,`,
    `  data,`,
    `  range,`,
    `}: ${name}Props) {`,
    `  const rows = filterByRange(data, range);`,
    `  const points = mapScatterPoints(rows, { xField, yField, zField });`,
    ``,
    `  return (`,
    `    <section className="chart-card chart-card--3d" id={id}>`,
    `      <h3>{title}</h3>`,
    `      <div className="three-chart" style={{ background: backgroundColor }}>`,
    `        <Canvas camera={{ position: [8, 6, 8], fov: 45 }}>`,
    `          <color attach="background" args={[backgroundColor]} />`,
    `          <ambientLight intensity={0.65} />`,
    `          <directionalLight position={[6, 10, 4]} intensity={1.1} />`,
    `          {showGrid ? (`,
    `            <Grid args={[12, 12]} cellColor="#334155" sectionColor="#475569" position={[0, -0.01, 0]} />`,
    `          ) : null}`,
    `          {points.map((point, index) => (`,
    `            <mesh key={point.label ?? index} position={[point.x, point.y, point.z]}>`,
    `              <sphereGeometry args={[0.1, 10, 10]} />`,
    `              <meshStandardMaterial color={BAR_COLORS[index % BAR_COLORS.length]} />`,
    `            </mesh>`,
    `          ))}`,
    `          <OrbitControls autoRotate={autoRotate} minDistance={4} maxDistance={40} />`,
    `        </Canvas>`,
    `      </div>`,
    `    </section>`,
    `  );`,
    `}`,
    ``,
    `const BAR_COLORS = ['#38bdf8', '#818cf8', '#34d399', '#fbbf24', '#f472b6', '#fb7185'];`,
    ``,
    `interface ScatterPoint {`,
    `  x: number;`,
    `  y: number;`,
    `  z: number;`,
    `  label?: string;`,
    `}`,
    ``,
    `function mapScatterPoints(`,
    `  rows: Row[],`,
    `  fields: { xField: string; yField: string; zField: string },`,
    `): ScatterPoint[] {`,
    `  if (rows.length === 0) {`,
    `    return [`,
    `      { x: -2, y: 1.2, z: -2, label: 'A' },`,
    `      { x: 0, y: 2.4, z: 1, label: 'B' },`,
    `      { x: 2, y: 0.8, z: 2, label: 'C' },`,
    `    ];`,
    `  }`,
    ``,
    `  const raw = rows.slice(0, 48).map((row, index) => ({`,
    `    x: readNumericField(row, fields.xField, index),`,
    `    y: readNumericField(row, fields.yField, index + 1),`,
    `    z: readNumericField(row, fields.zField, index * 0.75 + 1),`,
    `    label: String(row.name ?? row.id ?? index + 1),`,
    `  }));`,
    ``,
    `  return normalizeScatterPoints(raw);`,
    `}`,
    ``,
    `function readNumericField(row: Row, field: string, fallback: number): number {`,
    `  const value = row[field];`,
    `  if (typeof value === 'number' && Number.isFinite(value)) {`,
    `    return value;`,
    `  }`,
    `  if (typeof value === 'string') {`,
    `    const parsed = Number(value);`,
    `    if (Number.isFinite(parsed)) {`,
    `      return parsed;`,
    `    }`,
    `    const timestamp = Date.parse(value);`,
    `    if (Number.isFinite(timestamp)) {`,
    `      return timestamp / 86400000;`,
    `    }`,
    `  }`,
    `  return fallback;`,
    `}`,
    ``,
    `function normalizeScatterPoints(points: ScatterPoint[]): ScatterPoint[] {`,
    `  const normalizeAxis = (values: number[], spread = 8, floor = 0.2) => {`,
    `    const min = Math.min(...values);`,
    `    const max = Math.max(...values);`,
    `    const span = max - min || 1;`,
    `    return values.map((value) => ((value - min) / span) * spread + floor);`,
    `  };`,
    ``,
    `  const xs = normalizeAxis(`,
    `    points.map((point) => point.x),`,
    `    8,`,
    `    -4,`,
    `  );`,
    `  const ys = normalizeAxis(points.map((point) => point.y));`,
    `  const zs = normalizeAxis(`,
    `    points.map((point) => point.z),`,
    `    8,`,
    `    -4,`,
    `  );`,
    ``,
    `  return points.map((point, index) => ({`,
    `    ...point,`,
    `    x: xs[index] ?? point.x,`,
    `    y: ys[index] ?? point.y,`,
    `    z: zs[index] ?? point.z,`,
    `  }));`,
    `}`,
    ``,
    `function filterByRange(data: Row[], range?: DateRange): Row[] {`,
    `  if (!range) {`,
    `    return data;`,
    `  }`,
    `  return data.filter((row) => {`,
    `    const value = String(row.date ?? row.createdAt ?? '');`,
    `    if (!value) {`,
    `      return true;`,
    `    }`,
    `    return value >= range.start && value <= range.end;`,
    `  });`,
    `}`,
    ``,
  ]);
}

function generateThreeGltfModel(name: string): string {
  return joinLines([
    `'use client';`,
    ``,
    `/** Requires: npm install three @react-three/fiber @react-three/drei */`,
    `import { Suspense, useMemo } from 'react';`,
    `import { Canvas } from '@react-three/fiber';`,
    `import { Grid, OrbitControls, useGLTF } from '@react-three/drei';`,
    ``,
    `export interface ${name}Props {`,
    `  id?: string;`,
    `  title?: string;`,
    `  modelUrl?: string;`,
    `  modelScale?: number;`,
    `  backgroundColor?: string;`,
    `  autoRotate?: boolean;`,
    `  showGrid?: boolean;`,
    `}`,
    ``,
    `const DEFAULT_MODEL_URL =`,
    `  'https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/Duck/glTF-Binary/Duck.glb';`,
    ``,
    `function GltfModel({ url, scale }: { url: string; scale: number }) {`,
    `  const { scene } = useGLTF(url);`,
    `  const model = useMemo(() => scene.clone(true), [scene]);`,
    `  return <primitive object={model} scale={scale} />;`,
    `}`,
    ``,
    `export function ${name}({`,
    `  id,`,
    `  title = '3D Model',`,
    `  modelUrl = DEFAULT_MODEL_URL,`,
    `  modelScale = 1.5,`,
    `  backgroundColor = '#0f172a',`,
    `  autoRotate = false,`,
    `  showGrid = true,`,
    `}: ${name}Props) {`,
    `  return (`,
    `    <section className="chart-card chart-card--3d" id={id}>`,
    `      <h3>{title}</h3>`,
    `      <div className="three-chart" style={{ background: backgroundColor }}>`,
    `        <Canvas camera={{ position: [8, 6, 8], fov: 45 }}>`,
    `          <color attach="background" args={[backgroundColor]} />`,
    `          <ambientLight intensity={0.65} />`,
    `          <directionalLight position={[6, 10, 4]} intensity={1.1} />`,
    `          {showGrid ? (`,
    `            <Grid args={[12, 12]} cellColor="#334155" sectionColor="#475569" position={[0, -0.01, 0]} />`,
    `          ) : null}`,
    `          <Suspense fallback={null}>`,
    `            <GltfModel url={modelUrl} scale={modelScale} />`,
    `          </Suspense>`,
    `          <OrbitControls autoRotate={autoRotate} minDistance={4} maxDistance={40} />`,
    `        </Canvas>`,
    `      </div>`,
    `    </section>`,
    `  );`,
    `}`,
    ``,
  ]);
}

function generateThreeGeoGlobe(name: string): string {
  return joinLines([
    `'use client';`,
    ``,
    `/** Requires: npm install three @react-three/fiber @react-three/drei */`,
    `import { Suspense, useMemo } from 'react';`,
    `import { Canvas } from '@react-three/fiber';`,
    `import { OrbitControls, Sphere, useTexture } from '@react-three/drei';`,
    `import type { DateRange, Row } from '../types';`,
    ``,
    `export interface ${name}Props {`,
    `  id?: string;`,
    `  title?: string;`,
    `  textureUrl?: string;`,
    `  latField?: string;`,
    `  lngField?: string;`,
    `  labelField?: string;`,
    `  globeRadius?: number;`,
    `  backgroundColor?: string;`,
    `  autoRotate?: boolean;`,
    `  data: Row[];`,
    `  range?: DateRange;`,
    `}`,
    ``,
    `const DEFAULT_TEXTURE_URL =`,
    `  'https://unpkg.com/three-globe/example/img/earth-blue-marble.jpg';`,
    ``,
    `function TexturedGlobe({ radius, textureUrl }: { radius: number; textureUrl: string }) {`,
    `  const texture = useTexture(textureUrl);`,
    `  return (`,
    `    <Sphere args={[radius, 48, 48]}>`,
    `      <meshStandardMaterial map={texture} />`,
    `    </Sphere>`,
    `  );`,
    `}`,
    ``,
    `export function ${name}({`,
    `  id,`,
    `  title = 'Geo Globe',`,
    `  textureUrl = DEFAULT_TEXTURE_URL,`,
    `  latField = 'lat',`,
    `  lngField = 'lng',`,
    `  labelField = 'name',`,
    `  globeRadius = 2,`,
    `  backgroundColor = '#0f172a',`,
    `  autoRotate = true,`,
    `  data,`,
    `  range,`,
    `}: ${name}Props) {`,
    `  const rows = filterByRange(data, range);`,
    `  const markers = useMemo(`,
    `    () => mapGlobeMarkers(rows, { latField, lngField, labelField }),`,
    `    [rows, latField, lngField, labelField],`,
    `  );`,
    ``,
    `  return (`,
    `    <section className="chart-card chart-card--3d" id={id}>`,
    `      <h3>{title}</h3>`,
    `      <div className="three-chart" style={{ background: backgroundColor }}>`,
    `        <Canvas camera={{ position: [0, 0, 7], fov: 45 }}>`,
    `          <color attach="background" args={[backgroundColor]} />`,
    `          <ambientLight intensity={0.65} />`,
    `          <directionalLight position={[6, 10, 4]} intensity={1.1} />`,
    `          <Suspense`,
    `            fallback={`,
    `              <Sphere args={[globeRadius, 48, 48]}>`,
    `                <meshStandardMaterial color="#1d4ed8" />`,
    `              </Sphere>`,
    `            }`,
    `          >`,
    `            <TexturedGlobe radius={globeRadius} textureUrl={textureUrl} />`,
    `          </Suspense>`,
    `          {markers.map((marker, index) => {`,
    `            const position = latLngToGlobePosition(marker.lat, marker.lng, globeRadius);`,
    `            return (`,
    `              <mesh key={marker.label ?? index} position={[position.x, position.y, position.z]}>`,
    `                <sphereGeometry args={[0.08, 10, 10]} />`,
    `                <meshStandardMaterial color={BAR_COLORS[index % BAR_COLORS.length]} />`,
    `              </mesh>`,
    `            );`,
    `          })}`,
    `          <OrbitControls autoRotate={autoRotate} minDistance={4} maxDistance={40} />`,
    `        </Canvas>`,
    `      </div>`,
    `    </section>`,
    `  );`,
    `}`,
    ``,
    `const BAR_COLORS = ['#38bdf8', '#818cf8', '#34d399', '#fbbf24', '#f472b6', '#fb7185'];`,
    ``,
    `interface GlobeMarker { lat: number; lng: number; label?: string }`,
    ``,
    `function latLngToGlobePosition(lat: number, lng: number, radius: number) {`,
    `  const phi = ((90 - lat) * Math.PI) / 180;`,
    `  const theta = ((lng + 180) * Math.PI) / 180;`,
    `  const surfaceRadius = radius + 0.06;`,
    `  return {`,
    `    x: -surfaceRadius * Math.sin(phi) * Math.cos(theta),`,
    `    y: surfaceRadius * Math.cos(phi),`,
    `    z: surfaceRadius * Math.sin(phi) * Math.sin(theta),`,
    `  };`,
    `}`,
    ``,
    `function mapGlobeMarkers(`,
    `  rows: Row[],`,
    `  fields: { latField: string; lngField: string; labelField: string },`,
    `): GlobeMarker[] {`,
    `  if (rows.length === 0) {`,
    `    return [`,
    `      { lat: 40.7128, lng: -74.006, label: 'New York' },`,
    `      { lat: 51.5074, lng: -0.1278, label: 'London' },`,
    `      { lat: 35.6762, lng: 139.6503, label: 'Tokyo' },`,
    `    ];`,
    `  }`,
    `  return rows.slice(0, 48).map((row, index) => ({`,
    `    lat: Number(row[fields.latField] ?? 0),`,
    `    lng: Number(row[fields.lngField] ?? 0),`,
    `    label: String(row[fields.labelField] ?? row.id ?? index + 1),`,
    `  }));`,
    `}`,
    ``,
    `function filterByRange(data: Row[], range?: DateRange): Row[] {`,
    `  if (!range) return data;`,
    `  return data.filter((row) => {`,
    `    const value = String(row.date ?? row.createdAt ?? '');`,
    `    if (!value) return true;`,
    `    return value >= range.start && value <= range.end;`,
    `  });`,
    `}`,
    ``,
  ]);
}

function generatePieChart(name: string): string {
  return joinLines([
    `'use client';`,
    ``,
    `import type { DateRange, Row } from '../types';`,
    ``,
    `export interface ${name}Props {`,
    `  id?: string;`,
    `  title?: string;`,
    `  labelField?: string;`,
    `  valueField?: string;`,
    `  donut?: boolean;`,
    `  data: Row[];`,
    `  range?: DateRange;`,
    `}`,
    ``,
    `export function ${name}({`,
    `  id,`,
    `  title = 'Chart',`,
    `  labelField = 'label',`,
    `  valueField = 'value',`,
    `  donut = false,`,
    `  data,`,
    `  range,`,
    `}: ${name}Props) {`,
    `  const points = filterByRange(data, range);`,
    `  const total = points.reduce((sum, row) => sum + Number(row[valueField] ?? 0), 0) || 1;`,
    `  const colors = ['#3b82f6', '#10b981', '#f59e0b', '#ef4444', '#8b5cf6'];`,
    `  let cumulative = 0;`,
    `  const gradient = points`,
    `    .map((row, index) => {`,
    `      const value = Number(row[valueField] ?? 0);`,
    `      const percent = (value / total) * 100;`,
    `      const start = cumulative;`,
    `      cumulative += percent;`,
    `      return \`\${colors[index % colors.length]} \${start}% \${cumulative}%\`;`,
    `    })`,
    `    .join(', ');`,
    ``,
    `  return (`,
    `    <section className="chart-card" id={id}>`,
    `      <h3>{title}</h3>`,
    `      <div`,
    `        className={donut ? 'pie-chart pie-chart--donut' : 'pie-chart'}`,
    `        style={{ background: \`conic-gradient(\${gradient || '#d1d5db 0 100%'})\` }}`,
    `      />`,
    `      <ul className="pie-chart__legend">`,
    `        {points.map((row, index) => (`,
    `          <li key={String(row.id ?? index)}>`,
    `            <span style={{ background: colors[index % colors.length] }} />`,
    `            {String(row[labelField] ?? row.id ?? index)}`,
    `          </li>`,
    `        ))}`,
    `      </ul>`,
    `    </section>`,
    `  );`,
    `}`,
    ``,
    `function filterByRange(data: Row[], range?: DateRange): Row[] {`,
    `  if (!range) {`,
    `    return data;`,
    `  }`,
    `  return data.filter((row) => {`,
    `    const value = String(row.date ?? row.createdAt ?? '');`,
    `    if (!value) {`,
    `      return true;`,
    `    }`,
    `    return value >= range.start && value <= range.end;`,
    `  });`,
    `}`,
    ``,
  ]);
}

function generatePersonInvite(name: string): string {
  return joinLines([
    `'use client';`,
    ``,
    `export interface ${name}Props {`,
    `  id?: string;`,
    `  title?: string;`,
    `  emailPlaceholder?: string;`,
    `  submitLabel?: string;`,
    `  onSubmit?: (email: string) => void;`,
    `}`,
    ``,
    `export function ${name}({`,
    `  id,`,
    `  title = 'Invite team member',`,
    `  emailPlaceholder = 'name@company.com',`,
    `  submitLabel = 'Send invite',`,
    `  onSubmit,`,
    `}: ${name}Props) {`,
    `  return (`,
    `    <section className="onboarding-step" id={id}>`,
    `      <h3>{title}</h3>`,
    `      <label className="field">`,
    `        <input className="input" type="email" placeholder={emailPlaceholder} />`,
    `      </label>`,
    `      <button type="button" className="button" onClick={() => onSubmit?.('')}>`,
    `        {submitLabel}`,
    `      </button>`,
    `    </section>`,
    `  );`,
    `}`,
    ``,
  ]);
}

function generateRoleAssign(name: string): string {
  return joinLines([
    `'use client';`,
    ``,
    `export interface ${name}Props {`,
    `  id?: string;`,
    `  title?: string;`,
    `  confirmLabel?: string;`,
    `  summaryLabel?: string;`,
    `  roles?: Array<{ id: string; name: string }>;`,
    `  onConfirm?: (roleId: string) => void;`,
    `}`,
    ``,
    `export function ${name}({`,
    `  id,`,
    `  title = 'Assign role',`,
    `  confirmLabel = 'Confirm access',`,
    `  summaryLabel = 'Review access before confirming',`,
    `  roles = [],`,
    `  onConfirm,`,
    `}: ${name}Props) {`,
    `  return (`,
    `    <section className="onboarding-step" id={id}>`,
    `      <h3>{title}</h3>`,
    `      <p className="onboarding-step__summary">{summaryLabel}</p>`,
    `      <label className="field">`,
    `        <select className="input" defaultValue={roles[0]?.id ?? ''}>`,
    `          {roles.map((role) => (`,
    `            <option key={role.id} value={role.id}>`,
    `              {role.name}`,
    `            </option>`,
    `          ))}`,
    `        </select>`,
    `      </label>`,
    `      <button type="button" className="button" onClick={() => onConfirm?.(roles[0]?.id ?? '')}>`,
    `        {confirmLabel}`,
    `      </button>`,
    `    </section>`,
    `  );`,
    `}`,
    ``,
  ]);
}

function generateTimer(name: string): string {
  return joinLines([
    `'use client';`,
    ``,
    `import { useEffect, useState } from 'react';`,
    ``,
    `export interface ${name}Props {`,
    `  id?: string;`,
    `  label?: string;`,
    `  mode?: 'interval' | 'countdown';`,
    `  intervalMs?: number;`,
    `  durationMs?: number;`,
    `  autoStart?: boolean;`,
    `  value?: number;`,
    `  onChange?: (value: number) => void;`,
    `}`,
    ``,
    `export function ${name}({`,
    `  id,`,
    `  label = 'Timer',`,
    `  mode = 'interval',`,
    `  intervalMs = 5000,`,
    `  durationMs = 30000,`,
    `  autoStart = true,`,
    `  value = 0,`,
    `  onChange,`,
    `}: ${name}Props) {`,
    `  const [elapsed, setElapsed] = useState(value);`,
    `  const [remaining, setRemaining] = useState(`,
    `    Math.max(1, Math.ceil(durationMs / 1000)),`,
    `  );`,
    ``,
    `  useEffect(() => {`,
    `    setElapsed(value);`,
    `  }, [value]);`,
    ``,
    `  useEffect(() => {`,
    `    if (!autoStart) {`,
    `      return;`,
    `    }`,
    ``,
    `    const stepMs = mode === 'countdown' ? 1000 : intervalMs;`,
    `    const id = window.setInterval(() => {`,
    `      setElapsed((current) => {`,
    `        const next = current + 1;`,
    `        onChange?.(next);`,
    `        return next;`,
    `      });`,
    `      if (mode === 'countdown') {`,
    `        setRemaining((current) => Math.max(0, current - 1));`,
    `      }`,
    `    }, stepMs);`,
    ``,
    `    return () => window.clearInterval(id);`,
    `  }, [autoStart, intervalMs, mode, onChange]);`,
    ``,
    `  return (`,
    `    <section className="timer" id={id}>`,
    `      <div className="timer__header">`,
    `        <span className="timer__label">{label}</span>`,
    `        <span className="timer__mode">{mode}</span>`,
    `      </div>`,
    `      <p className="timer__value">`,
    `        {mode === 'countdown' ? \`\${remaining}s remaining\` : \`\${elapsed} ticks\`}`,
    `      </p>`,
    `    </section>`,
    `  );`,
    `}`,
    ``,
  ]);
}

function generateRoleGate(name: string): string {
  return joinLines([
    `'use client';`,
    ``,
    `import { useCurrentRole } from '../auth/useCurrentRole';`,
    ``,
    `export interface ${name}Props {`,
    `  id?: string;`,
    `  label?: string;`,
    `  allowedRoles?: string[];`,
    `  children?: React.ReactNode;`,
    `}`,
    ``,
    `export function ${name}({ id, label = 'Protected section', allowedRoles = [], children }: ${name}Props) {`,
    `  const role = useCurrentRole();`,
    `  const visible = allowedRoles.length === 0 || allowedRoles.includes(role);`,
    ``,
    `  if (!visible) {`,
    `    return null;`,
    `  }`,
    ``,
    `  return (`,
    `    <section className="role-gate" id={id} data-allowed-roles={allowedRoles.join(',')}>`,
    `      <header className="role-gate__header">`,
    `        <h3>{label}</h3>`,
    `        <span className="role-gate__badge">Role: {role}</span>`,
    `      </header>`,
    `      <div className="role-gate__content">{children ?? <p>Protected content</p>}</div>`,
    `    </section>`,
    `  );`,
    `}`,
    ``,
  ]);
}
