import type { IRComponent } from '@dashbuilder/core';
import { ReactExportError } from './types';
import { joinLines } from './utils';

const SUPPORTED_TYPES = new Set([
  'visual.input.text',
  'visual.input.select',
  'visual.input.date-range',
  'visual.table',
  'visual.kpi',
  'visual.chart.line',
  'visual.chart.bar',
  'domain.role-gate',
]);

export function generateComponentFile(component: IRComponent, exportName: string): string {
  if (!SUPPORTED_TYPES.has(component.type)) {
    throw new ReactExportError(`Unsupported React export component type: ${component.type}`);
  }

  switch (component.type) {
    case 'visual.input.text':
      return generateTextInput(exportName);
    case 'visual.input.select':
      return generateSelectInput(exportName);
    case 'visual.input.date-range':
      return generateDateRangeFilter(exportName);
    case 'visual.table':
      return generateDataTable(exportName);
    case 'visual.kpi':
      return generateKpiCard(exportName);
    case 'visual.chart.line':
      return generateLineChart(exportName);
    case 'visual.chart.bar':
      return generateBarChart(exportName);
    case 'domain.role-gate':
      return generateRoleGate(exportName);
    default:
      throw new ReactExportError(`Missing React template for ${component.type}`);
  }
}

function generateTextInput(name: string): string {
  return joinLines([
    `'use client';`,
    ``,
    `export interface ${name}Props {`,
    `  id?: string;`,
    `  placeholder?: string;`,
    `  required?: boolean;`,
    `  value?: string;`,
    `  onChange?: (value: string) => void;`,
    `}`,
    ``,
    `export function ${name}({ id, placeholder = '', required = false, value = '', onChange }: ${name}Props) {`,
    `  return (`,
    `    <label className="field" htmlFor={id}>`,
    `      <input`,
    `        id={id}`,
    `        className="input"`,
    `        type="text"`,
    `        placeholder={placeholder}`,
    `        required={required}`,
    `        value={value}`,
    `        onChange={(event) => onChange?.(event.target.value)}`,
    `      />`,
    `    </label>`,
    `  );`,
    `}`,
    ``,
  ]);
}

function generateSelectInput(name: string): string {
  return joinLines([
    `'use client';`,
    ``,
    `import type { Row } from '../types';`,
    ``,
    `export interface ${name}Props {`,
    `  id?: string;`,
    `  placeholder?: string;`,
    `  options?: Row[];`,
    `  value?: string;`,
    `  onChange?: (value: string) => void;`,
    `}`,
    ``,
    `export function ${name}({ id, placeholder = 'Select…', options = [], value = '', onChange }: ${name}Props) {`,
    `  return (`,
    `    <label className="field" htmlFor={id}>`,
    `      <select`,
    `        id={id}`,
    `        className="select"`,
    `        value={value}`,
    `        onChange={(event) => onChange?.(event.target.value)}`,
    `      >`,
    `        <option value="">{placeholder}</option>`,
    `        {options.map((option, index) => (`,
    `          <option key={String(option.id ?? index)} value={String(option.id ?? option.label ?? index)}>`,
    `            {String(option.label ?? option.id ?? index)}`,
    `          </option>`,
    `        ))}`,
    `      </select>`,
    `    </label>`,
    `  );`,
    `}`,
    ``,
  ]);
}

function generateDateRangeFilter(name: string): string {
  return joinLines([
    `'use client';`,
    ``,
    `import type { DateRange } from '../types';`,
    ``,
    `export interface ${name}Props {`,
    `  id?: string;`,
    `  preset?: string;`,
    `  value?: DateRange;`,
    `  onChange?: (range: DateRange) => void;`,
    `}`,
    ``,
    `export function ${name}({ id, preset = 'last-7-days', value, onChange }: ${name}Props) {`,
    `  const current = value ?? defaultRangeForPreset(preset);`,
    ``,
    `  return (`,
    `    <div className="date-range" id={id}>`,
    `      <label className="field">`,
    `        <span>Start</span>`,
    `        <input`,
    `          className="input"`,
    `          type="date"`,
    `          value={current.start}`,
    `          onChange={(event) => onChange?.({ ...current, start: event.target.value })}`,
    `        />`,
    `      </label>`,
    `      <label className="field">`,
    `        <span>End</span>`,
    `        <input`,
    `          className="input"`,
    `          type="date"`,
    `          value={current.end}`,
    `          onChange={(event) => onChange?.({ ...current, end: event.target.value })}`,
    `        />`,
    `      </label>`,
    `    </div>`,
    `  );`,
    `}`,
    ``,
    `function defaultRangeForPreset(preset: string): DateRange {`,
    `  const end = new Date();`,
    `  const start = new Date(end);`,
    `  if (preset === 'last-30-days') {`,
    `    start.setDate(end.getDate() - 30);`,
    `  } else if (preset === 'qtd') {`,
    `    start.setMonth(Math.floor(end.getMonth() / 3) * 3, 1);`,
    `  } else {`,
    `    start.setDate(end.getDate() - 7);`,
    `  }`,
    `  return { start: formatDate(start), end: formatDate(end) };`,
    `}`,
    ``,
    `function formatDate(date: Date): string {`,
    `  return date.toISOString().slice(0, 10);`,
    `}`,
    ``,
  ]);
}

function generateDataTable(name: string): string {
  return joinLines([
    `'use client';`,
    ``,
    `import type { DateRange, Row } from '../types';`,
    ``,
    `export interface ${name}Props {`,
    `  id?: string;`,
    `  data: Row[];`,
    `  filter?: DateRange;`,
    `  pageSize?: number;`,
    `  sortable?: boolean;`,
    `  filterable?: boolean;`,
    `}`,
    ``,
    `export function ${name}({ id, data, filter, pageSize = 25, sortable = true, filterable = true }: ${name}Props) {`,
    `  const rows = filterRows(data, filter).slice(0, pageSize);`,
    `  const columns = rows.length > 0 ? Object.keys(rows[0]) : ['id', 'label', 'value'];`,
    ``,
    `  return (`,
    `    <section className="table-card" id={id} data-sortable={sortable} data-filterable={filterable}>`,
    `      <table className="table">`,
    `        <thead>`,
    `          <tr>`,
    `            {columns.map((column) => (`,
    `              <th key={column}>{column}</th>`,
    `            ))}`,
    `          </tr>`,
    `        </thead>`,
    `        <tbody>`,
    `          {rows.map((row, index) => (`,
    `            <tr key={String(row.id ?? index)}>`,
    `              {columns.map((column) => (`,
    `                <td key={column}>{String(row[column] ?? '')}</td>`,
    `              ))}`,
    `            </tr>`,
    `          ))}`,
    `        </tbody>`,
    `      </table>`,
    `    </section>`,
    `  );`,
    `}`,
    ``,
    `function filterRows(data: Row[], filter?: DateRange): Row[] {`,
    `  if (!filter) {`,
    `    return data;`,
    `  }`,
    `  return data.filter((row) => {`,
    `    const value = String(row.date ?? row.createdAt ?? '');`,
    `    if (!value) {`,
    `      return true;`,
    `    }`,
    `    return value >= filter.start && value <= filter.end;`,
    `  });`,
    `}`,
    ``,
  ]);
}

function generateKpiCard(name: string): string {
  return joinLines([
    `'use client';`,
    ``,
    `export interface ${name}Props {`,
    `  id?: string;`,
    `  title?: string;`,
    `  format?: 'number' | 'currency' | 'percent';`,
    `  value?: number;`,
    `}`,
    ``,
    `export function ${name}({ id, title = 'Metric', format = 'number', value = 0 }: ${name}Props) {`,
    `  return (`,
    `    <article className="kpi-card" id={id}>`,
    `      <h3>{title}</h3>`,
    `      <p className="kpi-value">{formatValue(value, format)}</p>`,
    `    </article>`,
    `  );`,
    `}`,
    ``,
    `function formatValue(value: number, format: ${name}Props['format']): string {`,
    `  if (format === 'currency') {`,
    `    return new Intl.NumberFormat(undefined, { style: 'currency', currency: 'USD' }).format(value);`,
    `  }`,
    `  if (format === 'percent') {`,
    `    return new Intl.NumberFormat(undefined, { style: 'percent', maximumFractionDigits: 1 }).format(value / 100);`,
    `  }`,
    `  return new Intl.NumberFormat().format(value);`,
    `}`,
    ``,
  ]);
}

function generateLineChart(name: string): string {
  return joinLines([
    `'use client';`,
    ``,
    `import type { DateRange, Row } from '../types';`,
    ``,
    `export interface ${name}Props {`,
    `  id?: string;`,
    `  title?: string;`,
    `  xField?: string;`,
    `  yField?: string;`,
    `  data: Row[];`,
    `  range?: DateRange;`,
    `}`,
    ``,
    `export function ${name}({ id, title = 'Chart', xField = 'date', yField = 'value', data, range }: ${name}Props) {`,
    `  const points = filterByRange(data, range);`,
    `  const max = Math.max(...points.map((row) => Number(row[yField] ?? 0)), 1);`,
    ``,
    `  return (`,
    `    <section className="chart-card" id={id}>`,
    `      <h3>{title}</h3>`,
    `      <svg className="line-chart" viewBox="0 0 320 120" role="img" aria-label={title}>`,
    `        <polyline`,
    `          fill="none"`,
    `          stroke="currentColor"`,
    `          strokeWidth="2"`,
    `          points={points`,
    `            .map((row, index) => {`,
    `              const x = (index / Math.max(points.length - 1, 1)) * 300 + 10;`,
    `              const y = 110 - (Number(row[yField] ?? 0) / max) * 90;`,
    `              return \`\${x},\${y}\`;`,
    `            })`,
    `            .join(' ')}`,
    `        />`,
    `      </svg>`,
    `      <p className="chart-meta">{points.length} points · x={xField} · y={yField}</p>`,
    `    </section>`,
    `  );`,
    `}`,
    ``,
    `function filterByRange(data: Row[], range?: DateRange): Row[] {`,
    `  if (!range) {`,
    `    return data;`,
    `  }`,
    `  return data.filter((row) => {`,
    `    const value = String(row.date ?? row.createdAt ?? '');`,
    `    if (!value) {`,
    `      return true;`,
    `    }`,
    `    return value >= range.start && value <= range.end;`,
    `  });`,
    `}`,
    ``,
  ]);
}

function generateBarChart(name: string): string {
  return joinLines([
    `'use client';`,
    ``,
    `import type { DateRange, Row } from '../types';`,
    ``,
    `export interface ${name}Props {`,
    `  id?: string;`,
    `  title?: string;`,
    `  data: Row[];`,
    `  range?: DateRange;`,
    `}`,
    ``,
    `export function ${name}({ id, title = 'Chart', data, range }: ${name}Props) {`,
    `  const points = filterByRange(data, range);`,
    `  const max = Math.max(...points.map((row) => Number(row.value ?? 0)), 1);`,
    ``,
    `  return (`,
    `    <section className="chart-card" id={id}>`,
    `      <h3>{title}</h3>`,
    `      <div className="bar-chart">`,
    `        {points.map((row, index) => (`,
    `          <div`,
    `            key={String(row.id ?? index)}`,
    `            className="bar"`,
    `            style={{ height: \`\${(Number(row.value ?? 0) / max) * 100}%\` }}`,
    `            title={String(row.label ?? row.id ?? index)}`,
    `          />`,
    `        ))}`,
    `      </div>`,
    `    </section>`,
    `  );`,
    `}`,
    ``,
    `function filterByRange(data: Row[], range?: DateRange): Row[] {`,
    `  if (!range) {`,
    `    return data;`,
    `  }`,
    `  return data.filter((row) => {`,
    `    const value = String(row.date ?? row.createdAt ?? '');`,
    `    if (!value) {`,
    `      return true;`,
    `    }`,
    `    return value >= range.start && value <= range.end;`,
    `  });`,
    `}`,
    ``,
  ]);
}

function generateRoleGate(name: string): string {
  return joinLines([
    `'use client';`,
    ``,
    `import { useCurrentRole } from '../auth/useCurrentRole';`,
    ``,
    `export interface ${name}Props {`,
    `  id?: string;`,
    `  label?: string;`,
    `  allowedRoles?: string[];`,
    `  children?: React.ReactNode;`,
    `}`,
    ``,
    `export function ${name}({ id, label = 'Protected section', allowedRoles = [], children }: ${name}Props) {`,
    `  const role = useCurrentRole();`,
    `  const visible = allowedRoles.length === 0 || allowedRoles.includes(role);`,
    ``,
    `  if (!visible) {`,
    `    return null;`,
    `  }`,
    ``,
    `  return (`,
    `    <section className="role-gate" id={id} data-allowed-roles={allowedRoles.join(',')}>`,
    `      <header className="role-gate__header">`,
    `        <h3>{label}</h3>`,
    `        <span className="role-gate__badge">Role: {role}</span>`,
    `      </header>`,
    `      <div className="role-gate__content">{children ?? <p>Protected content</p>}</div>`,
    `    </section>`,
    `  );`,
    `}`,
    ``,
  ]);
}
