import { joinLines } from './utils';

/** Inlined into exported React apps (mirrors @rosettadash/core media helpers). */
export function generateEquirectFilterHelperFile(): string {
  return joinLines([
    `export interface EquirectFlatCropOptions {`,
    `  cropX: number;`,
    `  cropY: number;`,
    `  cropWidth: number;`,
    `  cropHeight: number;`,
    `  outputWidth: number;`,
    `  outputHeight: number;`,
    `}`,
    ``,
    `export function buildEquirectFlatCropFilter(options: EquirectFlatCropOptions): string {`,
    `  const cropX = Math.max(0, Math.round(options.cropX));`,
    `  const cropY = Math.max(0, Math.round(options.cropY));`,
    `  const cropWidth = Math.max(2, Math.round(options.cropWidth));`,
    `  const cropHeight = Math.max(2, Math.round(options.cropHeight));`,
    `  const outputWidth = Math.max(2, Math.round(options.outputWidth));`,
    `  const outputHeight = Math.max(2, Math.round(options.outputHeight));`,
    `  return \`crop=\${cropWidth}:\${cropHeight}:\${cropX}:\${cropY},scale=\${outputWidth}:\${outputHeight}\`;`,
    `}`,
    ``,
    `export function buildEquirectRectilinearFilter(options: {`,
    `  yaw: number;`,
    `  pitch: number;`,
    `  roll?: number;`,
    `  horizontalFov: number;`,
    `  outputWidth: number;`,
    `  outputHeight: number;`,
    `}): string {`,
    `  const yaw = Number(options.yaw) || 0;`,
    `  const pitch = Number(options.pitch) || 0;`,
    `  const roll = Number(options.roll ?? 0) || 0;`,
    `  const horizontalFov = Math.max(1, Number(options.horizontalFov) || 90);`,
    `  const outputWidth = Math.max(2, Math.round(options.outputWidth));`,
    `  const outputHeight = Math.max(2, Math.round(options.outputHeight));`,
    `  return [`,
    `    \`v360=input=equirect:output=rectilinear:yaw=\${yaw}:pitch=\${pitch}:roll=\${roll}:d_fov=\${horizontalFov}\`,`,
    `    \`scale=\${outputWidth}:\${outputHeight}\`,`,
    `  ].join(',');`,
    `}`,
    ``,
    `export function buildEquirectExtractFilter(`,
    `  mode: 'flat-crop' | 'rectilinear',`,
    `  options: EquirectFlatCropOptions & {`,
    `    yaw?: number;`,
    `    pitch?: number;`,
    `    roll?: number;`,
    `    horizontalFov?: number;`,
    `  },`,
    `): string {`,
    `  if (mode === 'rectilinear') {`,
    `    return buildEquirectRectilinearFilter({`,
    `      yaw: options.yaw ?? 0,`,
    `      pitch: options.pitch ?? 0,`,
    `      roll: options.roll ?? 0,`,
    `      horizontalFov: options.horizontalFov ?? 90,`,
    `      outputWidth: options.outputWidth,`,
    `      outputHeight: options.outputHeight,`,
    `    });`,
    `  }`,
    `  return buildEquirectFlatCropFilter(options);`,
    `}`,
    ``,
  ]);
}

export function generateVideoSource(name: string): string {
  return joinLines([
    `'use client';`,
    ``,
    `import { useRef, useState } from 'react';`,
    `import type { Row } from '../types';`,
    ``,
    `export interface ${name}Props {`,
    `  id?: string;`,
    `  label?: string;`,
    `  accept?: string;`,
    `  url?: string;`,
    `  sourceWidth?: number;`,
    `  sourceHeight?: number;`,
    `  captureBlob?: Blob;`,
    `  onVideoFile?: (file: File) => void;`,
    `  onMetadata?: (row: Row) => void;`,
    `}`,
    ``,
    `export function ${name}({`,
    `  id,`,
    `  label = 'Video source',`,
    `  accept = 'video/*',`,
    `  url = '',`,
    `  sourceWidth = 4096,`,
    `  sourceHeight = 2048,`,
    `  captureBlob,`,
    `  onVideoFile,`,
    `  onMetadata,`,
    `}: ${name}Props) {`,
    `  const inputRef = useRef<HTMLInputElement>(null);`,
    `  const [fileName, setFileName] = useState('');`,
    ``,
    `  const emitFile = (file: File) => {`,
    `    setFileName(file.name);`,
    `    onVideoFile?.(file);`,
    `    onMetadata?.({`,
    `      name: file.name,`,
    `      sourceWidth,`,
    `      sourceHeight,`,
    `      size: file.size,`,
    `    });`,
    `  };`,
    ``,
    `  return (`,
    `    <section className="media-source" id={id}>`,
    `      <header className="media-source__header">`,
    `        <h3>{label}</h3>`,
    `        <span>{sourceWidth}×{sourceHeight}</span>`,
    `      </header>`,
    `      <label className="media-source__upload">`,
    `        <input`,
    `          ref={inputRef}`,
    `          type="file"`,
    `          accept={accept}`,
    `          onChange={(event) => {`,
    `            const file = event.target.files?.[0];`,
    `            if (file) emitFile(file);`,
    `          }}`,
    `        />`,
    `        <span>{fileName || 'Choose video file'}</span>`,
    `      </label>`,
    `      {url ? <p className="media-source__url">URL: {url}</p> : null}`,
    `      {captureBlob ? <p className="media-source__capture">Live capture attached</p> : null}`,
    `    </section>`,
    `  );`,
    `}`,
    ``,
  ]);
}

export function generateEquirectViewport(name: string): string {
  return joinLines([
    `'use client';`,
    ``,
    `import type { Row } from '../types';`,
    ``,
    `export interface ${name}Props {`,
    `  id?: string;`,
    `  label?: string;`,
    `  sourceWidth?: number;`,
    `  sourceHeight?: number;`,
    `  cropX?: number;`,
    `  cropY?: number;`,
    `  cropWidth?: number;`,
    `  cropHeight?: number;`,
    `  outputWidth?: number;`,
    `  outputHeight?: number;`,
    `  onCropRegion?: (region: Row) => void;`,
    `}`,
    ``,
    `export function ${name}({`,
    `  id,`,
    `  label = 'Equirect viewport',`,
    `  sourceWidth = 4096,`,
    `  sourceHeight = 2048,`,
    `  cropX = 1508,`,
    `  cropY = 664,`,
    `  cropWidth = 1080,`,
    `  cropHeight = 720,`,
    `  outputWidth = 720,`,
    `  outputHeight = 480,`,
    `  onCropRegion,`,
    `}: ${name}Props) {`,
    `  const cropStyle = {`,
    `    left: \`\${(cropX / sourceWidth) * 100}%\`,`,
    `    top: \`\${(cropY / sourceHeight) * 100}%\`,`,
    `    width: \`\${(cropWidth / sourceWidth) * 100}%\`,`,
    `    height: \`\${(cropHeight / sourceHeight) * 100}%\`,`,
    `  };`,
    ``,
    `  const region = { cropX, cropY, cropWidth, cropHeight, outputWidth, outputHeight };`,
    ``,
    `  return (`,
    `    <section className="media-viewport" id={id}>`,
    `      <header className="media-viewport__header">`,
    `        <h3>{label}</h3>`,
    `        <button type="button" onClick={() => onCropRegion?.(region)}>`,
    `          Emit crop region`,
    `        </button>`,
    `      </header>`,
    `      <div className="media-viewport__frame">`,
    `        <div className="media-viewport__crop" style={cropStyle} />`,
    `      </div>`,
    `      <p className="media-viewport__meta">`,
    `        Crop {cropWidth}×{cropHeight} → Output {outputWidth}×{outputHeight}`,
    `      </p>`,
    `    </section>`,
    `  );`,
    `}`,
    ``,
  ]);
}

export function generateLiveCapture(name: string): string {
  return joinLines([
    `'use client';`,
    ``,
    `import { useEffect, useRef, useState } from 'react';`,
    ``,
    `export interface ${name}Props {`,
    `  id?: string;`,
    `  label?: string;`,
    `  includeInExport?: boolean;`,
    `  facingMode?: 'user' | 'environment';`,
    `  audio?: boolean;`,
    `  onCaptureBlob?: (blob: Blob) => void;`,
    `  onPreviewUrl?: (url: string) => void;`,
    `}`,
    ``,
    `export function ${name}({`,
    `  id,`,
    `  label = 'Live capture',`,
    `  includeInExport = false,`,
    `  facingMode = 'environment',`,
    `  audio = true,`,
    `  onCaptureBlob,`,
    `  onPreviewUrl,`,
    `}: ${name}Props) {`,
    `  const videoRef = useRef<HTMLVideoElement>(null);`,
    `  const [active, setActive] = useState(false);`,
    `  const streamRef = useRef<MediaStream | null>(null);`,
    ``,
    `  useEffect(() => () => {`,
    `    streamRef.current?.getTracks().forEach((track) => track.stop());`,
    `  }, []);`,
    ``,
    `  const startCapture = async () => {`,
    `    const stream = await navigator.mediaDevices.getUserMedia({`,
    `      video: { facingMode },`,
    `      audio,`,
    `    });`,
    `    streamRef.current = stream;`,
    `    if (videoRef.current) {`,
    `      videoRef.current.srcObject = stream;`,
    `      await videoRef.current.play();`,
    `    }`,
    `    setActive(true);`,
    `    onPreviewUrl?.('live');`,
    `  };`,
    ``,
    `  if (!includeInExport) {`,
    `    return (`,
    `      <section className="media-capture media-capture--authoring" id={id}>`,
    `        <p>{label} (authoring only — enable includeInExport for runtime capture)</p>`,
    `      </section>`,
    `    );`,
    `  }`,
    ``,
    `  return (`,
    `    <section className="media-capture" id={id}>`,
    `      <header><h3>{label}</h3></header>`,
    `      <video ref={videoRef} className="media-capture__video" muted playsInline />`,
    `      <button type="button" onClick={() => void startCapture()}>`,
    `        {active ? 'Camera active' : 'Start camera'}`,
    `      </button>`,
    `    </section>`,
    `  );`,
    `}`,
    ``,
  ]);
}

export function generateWasmMediaEquirect(name: string): string {
  return joinLines([
    `'use client';`,
    ``,
    `/** Requires: npm install @ffmpeg/ffmpeg @ffmpeg/util */`,
    `import { useCallback, useRef, useState } from 'react';`,
    `import { FFmpeg } from '@ffmpeg/ffmpeg';`,
    `import { fetchFile, toBlobURL } from '@ffmpeg/util';`,
    `import type { Row } from '../types';`,
    `import { buildEquirectExtractFilter } from '../media/equirect-filter';`,
    ``,
    `export interface ${name}Props {`,
    `  id?: string;`,
    `  label?: string;`,
    `  operation?: string;`,
    `  extractionMode?: 'flat-crop' | 'rectilinear';`,
    `  outputFormat?: string;`,
    `  cropX?: number;`,
    `  cropY?: number;`,
    `  cropWidth?: number;`,
    `  cropHeight?: number;`,
    `  outputWidth?: number;`,
    `  outputHeight?: number;`,
    `  yaw?: number;`,
    `  pitch?: number;`,
    `  horizontalFov?: number;`,
    `  showProgress?: boolean;`,
    `  inputFile?: File | Blob;`,
    `  cropRegion?: Row;`,
    `  onOutputBlob?: (blob: Blob) => void;`,
    `  onProgress?: (value: number) => void;`,
    `  onMetadata?: (rows: Row[]) => void;`,
    `}`,
    ``,
    `export function ${name}({`,
    `  id,`,
    `  label = 'Media transcode',`,
    `  operation = 'transcode',`,
    `  extractionMode = 'flat-crop',`,
    `  outputFormat = 'mp4',`,
    `  cropX = 1508,`,
    `  cropY = 664,`,
    `  cropWidth = 1080,`,
    `  cropHeight = 720,`,
    `  outputWidth = 720,`,
    `  outputHeight = 480,`,
    `  yaw = 0,`,
    `  pitch = 0,`,
    `  horizontalFov = 90,`,
    `  showProgress = true,`,
    `  inputFile,`,
    `  cropRegion,`,
    `  onOutputBlob,`,
    `  onProgress,`,
    `  onMetadata,`,
    `}: ${name}Props) {`,
    `  const ffmpegRef = useRef<FFmpeg | null>(null);`,
    `  const [progress, setProgress] = useState(0);`,
    `  const [busy, setBusy] = useState(false);`,
    `  const [error, setError] = useState<string | null>(null);`,
    ``,
    `  const resolveCrop = useCallback(() => ({`,
    `    cropX: Number(cropRegion?.cropX ?? cropX),`,
    `    cropY: Number(cropRegion?.cropY ?? cropY),`,
    `    cropWidth: Number(cropRegion?.cropWidth ?? cropWidth),`,
    `    cropHeight: Number(cropRegion?.cropHeight ?? cropHeight),`,
    `    outputWidth: Number(cropRegion?.outputWidth ?? outputWidth),`,
    `    outputHeight: Number(cropRegion?.outputHeight ?? outputHeight),`,
    `  }), [cropRegion, cropX, cropY, cropWidth, cropHeight, outputWidth, outputHeight]);`,
    ``,
    `  const ensureFfmpeg = useCallback(async () => {`,
    `    if (ffmpegRef.current) return ffmpegRef.current;`,
    `    const ffmpeg = new FFmpeg();`,
    `    ffmpeg.on('progress', ({ progress: ratio }) => {`,
    `      const next = Math.round(ratio * 100);`,
    `      setProgress(next);`,
    `      onProgress?.(next);`,
    `    });`,
    `    const baseURL = 'https://unpkg.com/@ffmpeg/core@0.12.6/dist/umd';`,
    `    await ffmpeg.load({`,
    `      coreURL: await toBlobURL(\`\${baseURL}/ffmpeg-core.js\`, 'text/javascript'),`,
    `      wasmURL: await toBlobURL(\`\${baseURL}/ffmpeg-core.wasm\`, 'application/wasm'),`,
    `    });`,
    `    ffmpegRef.current = ffmpeg;`,
    `    return ffmpeg;`,
    `  }, [onProgress]);`,
    ``,
    `  const runEquirectExtract = useCallback(async () => {`,
    `    if (!inputFile) {`,
    `      setError('Attach a video file before extracting.');`,
    `      return;`,
    `    }`,
    `    setBusy(true);`,
    `    setError(null);`,
    `    try {`,
    `      const ffmpeg = await ensureFfmpeg();`,
    `      const inputName = 'input.mp4';`,
    `      const outputName = \`output.\${outputFormat}\`;`,
    `      await ffmpeg.writeFile(inputName, await fetchFile(inputFile));`,
    `      const crop = resolveCrop();`,
    `      const filter = buildEquirectExtractFilter(extractionMode, {`,
    `        ...crop,`,
    `        yaw,`,
    `        pitch,`,
    `        horizontalFov,`,
    `      });`,
    `      await ffmpeg.exec(['-i', inputName, '-vf', filter, '-c:a', 'copy', outputName]);`,
    `      const data = await ffmpeg.readFile(outputName);`,
    `      const blob = new Blob([data], { type: \`video/\${outputFormat}\` });`,
    `      onOutputBlob?.(blob);`,
    `      onMetadata?.([{`,
    `        filter,`,
    `        outputWidth: crop.outputWidth,`,
    `        outputHeight: crop.outputHeight,`,
    `        format: outputFormat,`,
    `      }]);`,
    `    } catch (nextError) {`,
    `      setError(nextError instanceof Error ? nextError.message : 'Extract failed');`,
    `    } finally {`,
    `      setBusy(false);`,
    `    }`,
    `  }, [`,
    `    ensureFfmpeg,`,
    `    extractionMode,`,
    `    horizontalFov,`,
    `    inputFile,`,
    `    onMetadata,`,
    `    onOutputBlob,`,
    `    onProgress,`,
    `    outputFormat,`,
    `    pitch,`,
    `    resolveCrop,`,
    `    yaw,`,
    `  ]);`,
    ``,
    `  const filterPreview =`,
    `    operation === 'equirect-extract'`,
    `      ? buildEquirectExtractFilter(extractionMode, {`,
    `          ...resolveCrop(),`,
    `          yaw,`,
    `          pitch,`,
    `          horizontalFov,`,
    `        })`,
    `      : '';`,
    ``,
    `  return (`,
    `    <section className="wasm-media" id={id}>`,
    `      <header className="wasm-media__header">`,
    `        <h3>{label}</h3>`,
    `        <span>{operation} → {outputFormat}</span>`,
    `      </header>`,
    `      {filterPreview ? <code className="wasm-media__filter">{filterPreview}</code> : null}`,
    `      {showProgress ? (`,
    `        <div className="wasm-media__progress" role="progressbar" aria-valuenow={progress}>`,
    `          <span style={{ width: \`\${progress}%\` }} />`,
    `        </div>`,
    `      ) : null}`,
    `      {operation === 'equirect-extract' ? (`,
    `        <button type="button" disabled={busy || !inputFile} onClick={() => void runEquirectExtract()}>`,
    `          {busy ? 'Extracting…' : 'Extract subsection'}`,
    `        </button>`,
    `      ) : (`,
    `        <p className="wasm-media__hint">Wire input file and choose equirect-extract operation.</p>`,
    `      )}`,
    `      {error ? <p className="wasm-media__error">{error}</p> : null}`,
    `    </section>`,
    `  );`,
    `}`,
    ``,
  ]);
}
