import type { ExportIR, IRDataSource, IRRoute, QueryScope } from '@dashbuilder/core';
import { appendScopeEnvLines } from '@dashbuilder/core';
import type { TableResource } from './types';

export function joinLines(lines: string[]): string {
  return `${lines.filter((line) => line !== undefined).join('\n')}\n`;
}

export function assertSafeTableName(table: string): string {
  if (!/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(table)) {
    throw new Error(`Unsafe MySQL table identifier: ${table}`);
  }
  return table;
}

export function resolveMysqlSources(ir: ExportIR): IRDataSource[] {
  return ir.dataSources.filter((source) => source.type === 'infra.mysql');
}

export function resolveConnectionEnvKey(ir: ExportIR): string {
  const mysql = resolveMysqlSources(ir)[0];
  return mysql?.connectionEnvKey ?? 'MYSQL_URL';
}

export function routeResourceName(route: IRRoute): string {
  const normalized = route.path.replace(/^\/+|\/+$/g, '');
  const segments = normalized.split('/').filter(Boolean);
  return segments[segments.length - 1] ?? 'records';
}

export function resolveTableResources(ir: ExportIR): TableResource[] {
  const mysqlSources = resolveMysqlSources(ir);
  const defaultTable = mysqlSources[0]?.table ?? 'records';

  return ir.routes.map((route) => {
    const resourceName = routeResourceName(route);
    const tableName = assertSafeTableName(
      mysqlSources.find((source) => source.table)?.table || defaultTable || 'records',
    );

    return {
      routeId: route.id,
      resourceName,
      tableName,
      method: route.method,
    };
  });
}

export function generateEnvExample(
  ir: ExportIR,
  connectionEnvKey: string,
  scope?: QueryScope,
): string {
  const lines = ['# Generated by DashBuilder — fill in values before running queries', ''];

  if (ir.envVars.length === 0) {
    lines.push(`${connectionEnvKey}=mysql://user:password@localhost:3306/mydb`);
  } else {
    for (const envVar of ir.envVars) {
      const example =
        envVar.example ??
        (envVar.key === connectionEnvKey
          ? 'mysql://user:password@localhost:3306/mydb'
          : 'your-value-here');
      lines.push(`${envVar.key}=${example}`);
    }
  }

  return joinLines(appendScopeEnvLines(lines, scope));
}
