import { joinLines } from './utils';

export function generateVideoSourceStandalone(exportName: string, tag: string): string {
  return joinLines([
    `import { defineDashElement } from '../define-element';`,
    ``,
    `const STYLES = \`:host { display: block; font-family: system-ui, sans-serif; }\`;`,
    ``,
    `export class ${exportName} extends HTMLElement {`,
    `  static readonly tagName = '${tag}';`,
    `  label = 'Video source';`,
    `  accept = 'video/*';`,
    `  sourceWidth = 4096;`,
    `  sourceHeight = 2048;`,
    ``,
    `  connectedCallback(): void { this.render(); }`,
    `  setProperty(name: string, value: unknown): void {`,
    `    (this as Record<string, unknown>)[name] = value;`,
    `    this.render();`,
    `  }`,
    `  private render(): void {`,
    `    if (!this.shadowRoot) this.attachShadow({ mode: 'open' });`,
    `    this.shadowRoot!.innerHTML = \`<style>\${STYLES}</style><section><h3>\${this.label}</h3><label><input type="file" accept="\${this.accept}" /><span>Choose video</span></label></section>\`;`,
    `    this.shadowRoot!.querySelector('input')?.addEventListener('change', (event) => {`,
    `      const file = (event.target as HTMLInputElement).files?.[0];`,
    `      if (!file) return;`,
    `      this.dispatchEvent(new CustomEvent('video-file', { detail: { file, metadata: { name: file.name, sourceWidth: this.sourceWidth, sourceHeight: this.sourceHeight, size: file.size } }, bubbles: true, composed: true }));`,
    `    });`,
    `  }`,
    `}`,
    ``,
    `export function register${exportName}(): void {`,
    `  defineDashElement(${exportName}.tagName, ${exportName});`,
    `}`,
    ``,
  ]);
}

export function generateEquirectViewportStandalone(exportName: string, tag: string): string {
  return joinLines([
    `import { buildEquirectExtractFilter } from '@dashbuilder/core';`,
    `import { defineDashElement } from '../define-element';`,
    ``,
    `export class ${exportName} extends HTMLElement {`,
    `  static readonly tagName = '${tag}';`,
    `  label = 'Equirect viewport';`,
    `  previewMode: 'flat-crop' | 'rectilinear' = 'flat-crop';`,
    `  sourceWidth = 4096;`,
    `  sourceHeight = 2048;`,
    `  cropX = 1508;`,
    `  cropY = 664;`,
    `  cropWidth = 1080;`,
    `  cropHeight = 720;`,
    `  outputWidth = 720;`,
    `  outputHeight = 480;`,
    `  yaw = 0;`,
    `  pitch = 0;`,
    `  horizontalFov = 90;`,
    ``,
    `  connectedCallback(): void { this.render(); this.emitCropRegion(); }`,
    `  setProperty(name: string, value: unknown): void {`,
    `    (this as Record<string, unknown>)[name] = value;`,
    `    this.render();`,
    `    this.emitCropRegion();`,
    `  }`,
    `  private emitCropRegion(): void {`,
    `    const detail = {`,
    `      cropX: this.cropX, cropY: this.cropY, cropWidth: this.cropWidth, cropHeight: this.cropHeight,`,
    `      outputWidth: this.outputWidth, outputHeight: this.outputHeight,`,
    `      yaw: this.yaw, pitch: this.pitch, horizontalFov: this.horizontalFov, previewMode: this.previewMode,`,
    `      filter: buildEquirectExtractFilter(this.previewMode, {`,
    `        cropX: this.cropX, cropY: this.cropY, cropWidth: this.cropWidth, cropHeight: this.cropHeight,`,
    `        outputWidth: this.outputWidth, outputHeight: this.outputHeight,`,
    `        yaw: this.yaw, pitch: this.pitch, horizontalFov: this.horizontalFov,`,
    `      }),`,
    `    };`,
    `    this.dispatchEvent(new CustomEvent('crop-region', { detail, bubbles: true, composed: true }));`,
    `  }`,
    `  private render(): void {`,
    `    if (!this.shadowRoot) this.attachShadow({ mode: 'open' });`,
    `    const left = (this.cropX / this.sourceWidth) * 100;`,
    `    const top = (this.cropY / this.sourceHeight) * 100;`,
    `    const width = (this.cropWidth / this.sourceWidth) * 100;`,
    `    const height = (this.cropHeight / this.sourceHeight) * 100;`,
    `    this.shadowRoot!.innerHTML = \`<style>:host{display:block;font:system-ui,sans-serif}.frame{aspect-ratio:2/1;background:#0f172a;position:relative}.crop{position:absolute;border:2px solid #38bdf8;box-shadow:0 0 0 9999px rgb(15 23 42/55%)}</style><section><h3>\${this.label}</h3>\${this.previewMode === 'flat-crop' ? \`<div class="frame"><div class="crop" style="left:\${left}%;top:\${top}%;width:\${width}%;height:\${height}%"></div></div>\` : \`<p>Rectilinear yaw \${this.yaw}° pitch \${this.pitch}° fov \${this.horizontalFov}°</p>\`}</section>\`;`,
    `  }`,
    `}`,
    ``,
    `export function register${exportName}(): void {`,
    `  defineDashElement(${exportName}.tagName, ${exportName});`,
    `}`,
    ``,
  ]);
}

export function generateWasmMediaEquirectStandalone(exportName: string, tag: string): string {
  return joinLines([
    `/** Standalone export — install @ffmpeg/ffmpeg @ffmpeg/util for runtime extract. */`,
    `import { buildEquirectExtractFilter } from '@dashbuilder/core';`,
    `import { defineDashElement } from '../define-element';`,
    ``,
    `export class ${exportName} extends HTMLElement {`,
    `  static readonly tagName = '${tag}';`,
    `  label = 'Media transcode';`,
    `  operation = 'equirect-extract';`,
    `  extractionMode: 'flat-crop' | 'rectilinear' = 'flat-crop';`,
    `  outputFormat = 'mp4';`,
    `  cropX = 1508;`,
    `  cropY = 664;`,
    `  cropWidth = 1080;`,
    `  cropHeight = 720;`,
    `  outputWidth = 720;`,
    `  outputHeight = 480;`,
    `  yaw = 0;`,
    `  pitch = 0;`,
    `  horizontalFov = 90;`,
    `  inputFile: File | Blob | null = null;`,
    `  cropRegion: Record<string, unknown> | null = null;`,
    ``,
    `  connectedCallback(): void { this.render(); }`,
    `  setProperty(name: string, value: unknown): void {`,
    `    (this as Record<string, unknown>)[name] = value;`,
    `    this.render();`,
    `  }`,
    `  private filterPreview(): string {`,
    `    const crop = this.cropRegion ?? { cropX: this.cropX, cropY: this.cropY, cropWidth: this.cropWidth, cropHeight: this.cropHeight, outputWidth: this.outputWidth, outputHeight: this.outputHeight };`,
    `    return buildEquirectExtractFilter(this.extractionMode, { ...crop, yaw: this.yaw, pitch: this.pitch, horizontalFov: this.horizontalFov });`,
    `  }`,
    `  private render(): void {`,
    `    if (!this.shadowRoot) this.attachShadow({ mode: 'open' });`,
    `    this.shadowRoot!.innerHTML = \`<style>:host{display:block;font:system-ui,sans-serif}code{display:block;margin:0.5rem 0;font-size:0.75rem}</style><section><h3>\${this.label}</h3><code>\${this.filterPreview()}</code><button type="button" data-role="extract" \${this.inputFile ? '' : 'disabled'}>Extract subsection</button></section>\`;`,
    `    this.shadowRoot!.querySelector('[data-role="extract"]')?.addEventListener('click', () => void this.runExtract());`,
    `  }`,
    `  private async runExtract(): Promise<void> {`,
    `    if (!this.inputFile) return;`,
    `    const { FFmpeg } = await import('@ffmpeg/ffmpeg');`,
    `    const { fetchFile, toBlobURL } = await import('@ffmpeg/util');`,
    `    const ffmpeg = new FFmpeg();`,
    `    const baseURL = 'https://unpkg.com/@ffmpeg/core@0.12.6/dist/umd';`,
    `    await ffmpeg.load({ coreURL: await toBlobURL(\`\${baseURL}/ffmpeg-core.js\`, 'text/javascript'), wasmURL: await toBlobURL(\`\${baseURL}/ffmpeg-core.wasm\`, 'application/wasm') });`,
    `    const filter = this.filterPreview();`,
    `    await ffmpeg.writeFile('input.mp4', await fetchFile(this.inputFile));`,
    `    await ffmpeg.exec(['-i', 'input.mp4', '-vf', filter, '-c:a', 'copy', 'output.mp4']);`,
    `    const data = await ffmpeg.readFile('output.mp4');`,
    `    const blob = new Blob([data], { type: 'video/mp4' });`,
    `    this.dispatchEvent(new CustomEvent('extract-complete', { detail: { blob, metadata: { filter } }, bubbles: true, composed: true }));`,
    `  }`,
    `}`,
    ``,
    `export function register${exportName}(): void {`,
    `  defineDashElement(${exportName}.tagName, ${exportName});`,
    `}`,
    ``,
  ]);
}
