import { joinLines } from './utils';

function threeVisualHelpers(): string[] {
  return [
    `const BAR_COLORS = ['#38bdf8', '#818cf8', '#34d399', '#fbbf24', '#f472b6', '#fb7185'];`,
    ``,
    `interface ScatterPoint {`,
    `  x: number;`,
    `  y: number;`,
    `  z: number;`,
    `  label?: string;`,
    `}`,
    ``,
    `function filterByRange(data: Row[], range?: DateRange): Row[] {`,
    `  if (!range) {`,
    `    return data;`,
    `  }`,
    `  return data.filter((row) => {`,
    `    const value = String(row.date ?? row.createdAt ?? '');`,
    `    if (!value) {`,
    `      return true;`,
    `    }`,
    `    return value >= range.start && value <= range.end;`,
    `  });`,
    `}`,
    ``,
    `function mapScatterPoints(`,
    `  rows: Row[],`,
    `  fields: { xField: string; yField: string; zField: string },`,
    `): ScatterPoint[] {`,
    `  if (rows.length === 0) {`,
    `    return [`,
    `      { x: -2, y: 1.2, z: -2, label: 'A' },`,
    `      { x: 0, y: 2.4, z: 1, label: 'B' },`,
    `      { x: 2, y: 0.8, z: 2, label: 'C' },`,
    `    ];`,
    `  }`,
    ``,
    `  const raw = rows.slice(0, 48).map((row, index) => ({`,
    `    x: readNumericField(row, fields.xField, index),`,
    `    y: readNumericField(row, fields.yField, index + 1),`,
    `    z: readNumericField(row, fields.zField, index * 0.75 + 1),`,
    `    label: String(row.name ?? row.id ?? index + 1),`,
    `  }));`,
    ``,
    `  return normalizeScatterPoints(raw);`,
    `}`,
    ``,
    `function readNumericField(row: Row, field: string, fallback: number): number {`,
    `  const value = row[field];`,
    `  if (typeof value === 'number' && Number.isFinite(value)) {`,
    `    return value;`,
    `  }`,
    `  if (typeof value === 'string') {`,
    `    const parsed = Number(value);`,
    `    if (Number.isFinite(parsed)) {`,
    `      return parsed;`,
    `    }`,
    `    const timestamp = Date.parse(value);`,
    `    if (Number.isFinite(timestamp)) {`,
    `      return timestamp / 86400000;`,
    `    }`,
    `  }`,
    `  return fallback;`,
    `}`,
    ``,
    `function normalizeScatterPoints(points: ScatterPoint[]): ScatterPoint[] {`,
    `  const normalizeAxis = (values: number[], spread = 8, floor = 0.2) => {`,
    `    const min = Math.min(...values);`,
    `    const max = Math.max(...values);`,
    `    const span = max - min || 1;`,
    `    return values.map((value) => ((value - min) / span) * spread + floor);`,
    `  };`,
    ``,
    `  const xs = normalizeAxis(`,
    `    points.map((point) => point.x),`,
    `    8,`,
    `    -4,`,
    `  );`,
    `  const ys = normalizeAxis(points.map((point) => point.y));`,
    `  const zs = normalizeAxis(`,
    `    points.map((point) => point.z),`,
    `    8,`,
    `    -4,`,
    `  );`,
    ``,
    `  return points.map((point, index) => ({`,
    `    ...point,`,
    `    x: xs[index] ?? point.x,`,
    `    y: ys[index] ?? point.y,`,
    `    z: zs[index] ?? point.z,`,
    `  }));`,
    `}`,
    ``,
  ];
}

export function generateThreeBarChart(name: string): string {
  return joinLines([
    `<script setup lang="ts">`,
    `/** Requires: npm install three @tresjs/core @tresjs/cientos */`,
    `import { TresCanvas } from '@tresjs/core';`,
    `import { OrbitControls } from '@tresjs/cientos';`,
    `import { computed } from 'vue';`,
    `import type { DateRange, Row } from '../types';`,
    ``,
    `const props = withDefaults(`,
    `  defineProps<{`,
    `    id?: string;`,
    `    title?: string;`,
    `    yField?: string;`,
    `    backgroundColor?: string;`,
    `    autoRotate?: boolean;`,
    `    data: Row[];`,
    `    range?: DateRange;`,
    `  }>(),`,
    `  { title: '3D Bar Chart', yField: 'value', backgroundColor: '#0f172a', autoRotate: false },`,
    `);`,
    ``,
    `const bars = computed(() => {`,
    `  const rows = filterByRange(props.data, props.range);`,
    `  const max = Math.max(...rows.map((row) => Number(row[props.yField ?? 'value'] ?? 0)), 1);`,
    `  const spacing = 1.4;`,
    `  const offset = ((rows.length - 1) * spacing) / 2;`,
    `  return rows.map((row, index) => {`,
    `    const value = Number(row[props.yField ?? 'value'] ?? 0);`,
    `    const height = Math.max(0.2, (value / max) * 4);`,
    `    return {`,
    `      key: String(row.id ?? index),`,
    `      height,`,
    `      x: index * spacing - offset,`,
    `      color: BAR_COLORS[index % BAR_COLORS.length],`,
    `    };`,
    `  });`,
    `});`,
    ``,
    ...threeVisualHelpers(),
    `</script>`,
    ``,
    `<template>`,
    `  <section class="chart-card chart-card--3d" :id="id">`,
    `    <h3>{{ title }}</h3>`,
    `    <div class="three-chart" :style="{ background: backgroundColor }">`,
    `      <TresCanvas>`,
    `        <TresPerspectiveCamera :position="[8, 6, 8]" />`,
    `        <TresAmbientLight :intensity="0.65" />`,
    `        <TresDirectionalLight :position="[6, 10, 4]" :intensity="1.1" />`,
    `        <TresMesh`,
    `          v-for="bar in bars"`,
    `          :key="bar.key"`,
    `          :position="[bar.x, bar.height / 2, 0]"`,
    `        >`,
    `          <TresBoxGeometry :args="[0.9, bar.height, 0.9]" />`,
    `          <TresMeshStandardMaterial :color="bar.color" />`,
    `        </TresMesh>`,
    `        <OrbitControls :auto-rotate="autoRotate" :min-distance="4" :max-distance="40" />`,
    `      </TresCanvas>`,
    `    </div>`,
    `  </section>`,
    `</template>`,
    ``,
  ]);
}

export function generateThreeScatterPlot(name: string): string {
  return joinLines([
    `<script setup lang="ts">`,
    `/** Requires: npm install three @tresjs/core @tresjs/cientos */`,
    `import { TresCanvas } from '@tresjs/core';`,
    `import { OrbitControls } from '@tresjs/cientos';`,
    `import { computed } from 'vue';`,
    `import type { DateRange, Row } from '../types';`,
    ``,
    `const props = withDefaults(`,
    `  defineProps<{`,
    `    id?: string;`,
    `    title?: string;`,
    `    xField?: string;`,
    `    yField?: string;`,
    `    zField?: string;`,
    `    backgroundColor?: string;`,
    `    autoRotate?: boolean;`,
    `    data: Row[];`,
    `    range?: DateRange;`,
    `  }>(),`,
    `  {`,
    `    title: '3D Scatter Plot',`,
    `    xField: 'date',`,
    `    yField: 'amount',`,
    `    zField: 'id',`,
    `    backgroundColor: '#0f172a',`,
    `    autoRotate: false,`,
    `  },`,
    `);`,
    ``,
    `const points = computed(() =>`,
    `  mapScatterPoints(filterByRange(props.data, props.range), {`,
    `    xField: props.xField ?? 'date',`,
    `    yField: props.yField ?? 'amount',`,
    `    zField: props.zField ?? 'id',`,
    `  }),`,
    `);`,
    ``,
    ...threeVisualHelpers(),
    `</script>`,
    ``,
    `<template>`,
    `  <section class="chart-card chart-card--3d" :id="id">`,
    `    <h3>{{ title }}</h3>`,
    `    <div class="three-chart" :style="{ background: backgroundColor }">`,
    `      <TresCanvas>`,
    `        <TresPerspectiveCamera :position="[8, 6, 8]" />`,
    `        <TresAmbientLight :intensity="0.65" />`,
    `        <TresDirectionalLight :position="[6, 10, 4]" :intensity="1.1" />`,
    `        <TresMesh`,
    `          v-for="(point, index) in points"`,
    `          :key="point.label ?? index"`,
    `          :position="[point.x, point.y, point.z]"`,
    `        >`,
    `          <TresSphereGeometry :args="[0.18, 16, 16]" />`,
    `          <TresMeshStandardMaterial :color="BAR_COLORS[index % BAR_COLORS.length]" />`,
    `        </TresMesh>`,
    `        <OrbitControls :auto-rotate="autoRotate" :min-distance="4" :max-distance="40" />`,
    `      </TresCanvas>`,
    `    </div>`,
    `  </section>`,
    `</template>`,
    ``,
  ]);
}

export function generateThreeScenePointCloud(name: string): string {
  return joinLines([
    `<script setup lang="ts">`,
    `/** Requires: npm install three @tresjs/core @tresjs/cientos */`,
    `import { TresCanvas } from '@tresjs/core';`,
    `import { Grid, OrbitControls } from '@tresjs/cientos';`,
    `import { computed } from 'vue';`,
    `import type { DateRange, Row } from '../types';`,
    ``,
    `const props = withDefaults(`,
    `  defineProps<{`,
    `    id?: string;`,
    `    title?: string;`,
    `    xField?: string;`,
    `    yField?: string;`,
    `    zField?: string;`,
    `    backgroundColor?: string;`,
    `    autoRotate?: boolean;`,
    `    showGrid?: boolean;`,
    `    data: Row[];`,
    `    range?: DateRange;`,
    `  }>(),`,
    `  {`,
    `    title: '3D Scene',`,
    `    xField: 'date',`,
    `    yField: 'amount',`,
    `    zField: 'id',`,
    `    backgroundColor: '#0f172a',`,
    `    autoRotate: false,`,
    `    showGrid: true,`,
    `  },`,
    `);`,
    ``,
    `const points = computed(() =>`,
    `  mapScatterPoints(filterByRange(props.data, props.range), {`,
    `    xField: props.xField ?? 'date',`,
    `    yField: props.yField ?? 'amount',`,
    `    zField: props.zField ?? 'id',`,
    `  }),`,
    `);`,
    ``,
    ...threeVisualHelpers(),
    `</script>`,
    ``,
    `<template>`,
    `  <section class="chart-card chart-card--3d" :id="id">`,
    `    <h3>{{ title }}</h3>`,
    `    <div class="three-chart" :style="{ background: backgroundColor }">`,
    `      <TresCanvas>`,
    `        <TresPerspectiveCamera :position="[8, 6, 8]" />`,
    `        <TresAmbientLight :intensity="0.65" />`,
    `        <TresDirectionalLight :position="[6, 10, 4]" :intensity="1.1" />`,
    `        <Grid v-if="showGrid" :args="[12, 12]" :cell-color="'#334155'" :section-color="'#475569'" :position="[0, -0.01, 0]" />`,
    `        <TresMesh`,
    `          v-for="(point, index) in points"`,
    `          :key="point.label ?? index"`,
    `          :position="[point.x, point.y, point.z]"`,
    `        >`,
    `          <TresSphereGeometry :args="[0.1, 10, 10]" />`,
    `          <TresMeshStandardMaterial :color="BAR_COLORS[index % BAR_COLORS.length]" />`,
    `        </TresMesh>`,
    `        <OrbitControls :auto-rotate="autoRotate" :min-distance="4" :max-distance="40" />`,
    `      </TresCanvas>`,
    `    </div>`,
    `  </section>`,
    `</template>`,
    ``,
  ]);
}

export function generateThreeGltfModel(name: string): string {
  return joinLines([
    `<script setup lang="ts">`,
    `/** Requires: npm install three @tresjs/core @tresjs/cientos */`,
    `import { TresCanvas } from '@tresjs/core';`,
    `import { Grid, OrbitControls, useGLTF } from '@tresjs/cientos';`,
    ``,
    `const DEFAULT_MODEL_URL =`,
    `  'https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/Duck/glTF-Binary/Duck.glb';`,
    ``,
    `const props = withDefaults(`,
    `  defineProps<{`,
    `    id?: string;`,
    `    title?: string;`,
    `    modelUrl?: string;`,
    `    modelScale?: number;`,
    `    backgroundColor?: string;`,
    `    autoRotate?: boolean;`,
    `    showGrid?: boolean;`,
    `  }>(),`,
    `  {`,
    `    title: '3D Model',`,
    `    modelUrl: DEFAULT_MODEL_URL,`,
    `    modelScale: 1.5,`,
    `    backgroundColor: '#0f172a',`,
    `    autoRotate: false,`,
    `    showGrid: true,`,
    `  },`,
    `);`,
    ``,
    `const { scene } = await useGLTF(props.modelUrl);`,
    `</script>`,
    ``,
    `<template>`,
    `  <section class="chart-card chart-card--3d" :id="id">`,
    `    <h3>{{ title }}</h3>`,
    `    <div class="three-chart" :style="{ background: backgroundColor }">`,
    `      <TresCanvas>`,
    `        <TresPerspectiveCamera :position="[8, 6, 8]" />`,
    `        <TresAmbientLight :intensity="0.65" />`,
    `        <TresDirectionalLight :position="[6, 10, 4]" :intensity="1.1" />`,
    `        <Grid v-if="showGrid" :args="[12, 12]" :cell-color="'#334155'" :section-color="'#475569'" :position="[0, -0.01, 0]" />`,
    `        <primitive :object="scene" :scale="modelScale" />`,
    `        <OrbitControls :auto-rotate="autoRotate" :min-distance="4" :max-distance="40" />`,
    `      </TresCanvas>`,
    `    </div>`,
    `  </section>`,
    `</template>`,
    ``,
  ]);
}
