import type { ExportIR, IRDataSource, IRRoute, QueryScope } from '@dashbuilder/core';
import { appendScopeEnvLines } from '@dashbuilder/core';
import type { RouteResource } from './types';

export function joinLines(lines: string[]): string {
  return `${lines.filter((line) => line !== undefined).join('\n')}\n`;
}

export function pascalCase(value: string): string {
  return value
    .replace(/[^a-zA-Z0-9]+/g, ' ')
    .trim()
    .split(/\s+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1).toLowerCase())
    .join('');
}

export function assertSafeTableName(table: string): string {
  if (!/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(table)) {
    throw new Error(`Unsafe SQL table identifier: ${table}`);
  }
  return table;
}

export function resolveGlobalPrefix(ir: ExportIR): string {
  const serverSource = ir.dataSources.find((source) => source.type === 'infra.server.nest');
  const configured =
    serverSource &&
    typeof serverSource.properties['globalPrefix'] === 'string' &&
    serverSource.properties['globalPrefix'].length > 0
      ? serverSource.properties['globalPrefix']
      : 'api';
  return configured.replace(/^\/+|\/+$/g, '');
}

export function resolvePostgresSources(ir: ExportIR): IRDataSource[] {
  return ir.dataSources.filter((source) => source.type === 'infra.postgresql');
}

export function resolvePrimaryConnectionEnvKey(ir: ExportIR): string {
  const postgres = resolvePostgresSources(ir)[0];
  return postgres?.connectionEnvKey ?? 'DATABASE_URL';
}

export function routeResourceName(route: IRRoute, globalPrefix: string): string {
  const normalized = route.path.replace(/^\/+|\/+$/g, '');
  const prefix = globalPrefix.replace(/^\/+|\/+$/g, '');
  const segments = normalized.split('/').filter(Boolean);
  if (prefix && segments[0] === prefix) {
    segments.shift();
  }
  return segments[segments.length - 1] ?? 'records';
}

export function resolveRouteResources(ir: ExportIR): RouteResource[] {
  const globalPrefix = resolveGlobalPrefix(ir);
  const postgresSources = resolvePostgresSources(ir);
  const defaultTable = postgresSources[0]?.table ?? 'records';

  return ir.routes.map((route) => {
    const resourceName = routeResourceName(route, globalPrefix);
    const tableName = assertSafeTableName(
      postgresSources.find((source) => source.table)?.table || defaultTable || 'records',
    );

    return {
      routeId: route.id,
      resourceName,
      controllerName: `${pascalCase(resourceName)}Controller`,
      moduleName: `${pascalCase(resourceName)}Module`,
      tableName,
      method: route.method,
      globalPrefix,
    };
  });
}

export function generateEnvExample(ir: ExportIR, scope?: QueryScope): string {
  const lines = ['# Generated by DashBuilder — fill in values before running the server', ''];

  if (ir.envVars.length === 0) {
    lines.push('DATABASE_URL=postgresql://user:password@localhost:5432/mydb', 'PORT=3000');
  } else {
    for (const envVar of ir.envVars) {
      const example =
        envVar.example ??
        (envVar.key === 'DATABASE_URL'
          ? 'postgresql://user:password@localhost:5432/mydb'
          : 'your-value-here');
      lines.push(`${envVar.key}=${example}`);
    }
    if (!ir.envVars.some((envVar) => envVar.key === 'PORT')) {
      lines.push('PORT=3000');
    }
  }

  return joinLines(appendScopeEnvLines(lines, scope));
}
