import type { IRComponent } from '@dashbuilder/core';
import { SvelteExportError } from './types';
import { joinLines } from './utils';

const SUPPORTED_TYPES = new Set([
  'visual.input.text',
  'visual.input.select',
  'visual.input.date-range',
  'visual.table',
  'visual.kpi',
  'visual.chart.line',
  'visual.chart.bar',
]);

export function generateComponentFile(component: IRComponent, exportName: string): string {
  if (!SUPPORTED_TYPES.has(component.type)) {
    throw new SvelteExportError(`Unsupported Svelte export component type: ${component.type}`);
  }

  switch (component.type) {
    case 'visual.input.text':
      return generateTextInput();
    case 'visual.input.select':
      return generateSelectInput();
    case 'visual.input.date-range':
      return generateDateRangeFilter();
    case 'visual.table':
      return generateDataTable();
    case 'visual.kpi':
      return generateKpiCard();
    case 'visual.chart.line':
      return generateLineChart();
    case 'visual.chart.bar':
      return generateBarChart();
    default:
      throw new SvelteExportError(`Missing Svelte template for ${component.type}`);
  }
}

function generateTextInput(): string {
  return joinLines([
    `<script lang="ts">`,
    `  let {`,
    `    id,`,
    `    placeholder,`,
    `    required = false,`,
    `    value = $bindable(''),`,
    `  }: {`,
    `    id?: string;`,
    `    placeholder?: string;`,
    `    required?: boolean;`,
    `    value?: string;`,
    `  } = $props();`,
    `</script>`,
    ``,
    `<label class="field" for={id}>`,
    `  <input class="input" type="text" {id} {placeholder} {required} bind:value />`,
    `</label>`,
    ``,
  ]);
}

function generateSelectInput(): string {
  return joinLines([
    `<script lang="ts">`,
    `  import type { Row } from '../types';`,
    `  let {`,
    `    id,`,
    `    placeholder = 'Select…',`,
    `    options = [] as Row[],`,
    `    value = $bindable(''),`,
    `  }: {`,
    `    id?: string;`,
    `    placeholder?: string;`,
    `    options?: Row[];`,
    `    value?: string;`,
    `  } = $props();`,
    `</script>`,
    ``,
    `<label class="field" for={id}>`,
    `  <select class="select" {id} bind:value>`,
    `    <option value="">{placeholder}</option>`,
    `    {#each options as option, index (String(option.id ?? index))}`,
    `      <option value={String(option.id ?? option.label ?? index)}>`,
    `        {option.label ?? option.id ?? index}`,
    `      </option>`,
    `    {/each}`,
    `  </select>`,
    `</label>`,
    ``,
  ]);
}

function generateDateRangeFilter(): string {
  return joinLines([
    `<script lang="ts">`,
    `  import type { DateRange } from '../types';`,
    `  let {`,
    `    id,`,
    `    preset = 'last-7-days',`,
    `    range = $bindable<DateRange>(),`,
    `  }: {`,
    `    id?: string;`,
    `    preset?: string;`,
    `    range?: DateRange;`,
    `  } = $props();`,
    ``,
    `  const current = $derived(range ?? defaultRangeForPreset(preset));`,
    ``,
    `  function onStartChange(start: string) {`,
    `    range = { ...current, start };`,
    `  }`,
    ``,
    `  function onEndChange(end: string) {`,
    `    range = { ...current, end };`,
    `  }`,
    ``,
    `  function defaultRangeForPreset(value: string): DateRange {`,
    `    const end = new Date();`,
    `    const start = new Date(end);`,
    `    if (value === 'last-30-days') start.setDate(end.getDate() - 30);`,
    `    else if (value === 'qtd') start.setMonth(Math.floor(end.getMonth() / 3) * 3, 1);`,
    `    else start.setDate(end.getDate() - 7);`,
    `    return { start: formatDate(start), end: formatDate(end) };`,
    `  }`,
    ``,
    `  function formatDate(date: Date): string {`,
    `    return date.toISOString().slice(0, 10);`,
    `  }`,
    `</script>`,
    ``,
    `<div class="date-range" {id}>`,
    `  <label class="field">`,
    `    <span>Start</span>`,
    `    <input`,
    `      class="input"`,
    `      type="date"`,
    `      value={current.start}`,
    `      oninput={(event) => onStartChange((event.currentTarget as HTMLInputElement).value)}`,
    `    />`,
    `  </label>`,
    `  <label class="field">`,
    `    <span>End</span>`,
    `    <input`,
    `      class="input"`,
    `      type="date"`,
    `      value={current.end}`,
    `      oninput={(event) => onEndChange((event.currentTarget as HTMLInputElement).value)}`,
    `    />`,
    `  </label>`,
    `</div>`,
    ``,
  ]);
}

function generateDataTable(): string {
  return joinLines([
    `<script lang="ts">`,
    `  import type { DateRange, Row } from '../types';`,
    `  let {`,
    `    id,`,
    `    data = [] as Row[],`,
    `    filter,`,
    `    pageSize = 25,`,
    `    sortable = true,`,
    `    filterable = true,`,
    `  }: {`,
    `    id?: string;`,
    `    data?: Row[];`,
    `    filter?: DateRange;`,
    `    pageSize?: number;`,
    `    sortable?: boolean;`,
    `    filterable?: boolean;`,
    `  } = $props();`,
    ``,
    `  const rows = $derived(filterRows(data, filter).slice(0, pageSize));`,
    `  const columns = $derived.by(() => {`,
    `    const first = rows[0];`,
    `    return first ? Object.keys(first) : ['id', 'label', 'value'];`,
    `  });`,
    ``,
    `  function filterRows(source: Row[], value?: DateRange): Row[] {`,
    `    if (!value) return source;`,
    `    return source.filter((row) => {`,
    `      const dateValue = String(row.date ?? row.createdAt ?? '');`,
    `      if (!dateValue) return true;`,
    `      return dateValue >= value.start && dateValue <= value.end;`,
    `    });`,
    `  }`,
    `</script>`,
    ``,
    `<section class="table-card" {id} data-sortable={sortable} data-filterable={filterable}>`,
    `  <table class="table">`,
    `    <thead>`,
    `      <tr>`,
    `        {#each columns as column (column)}`,
    `          <th>{column}</th>`,
    `        {/each}`,
    `      </tr>`,
    `    </thead>`,
    `    <tbody>`,
    `      {#each rows as row, index (String(row.id ?? index))}`,
    `        <tr>`,
    `          {#each columns as column (column)}`,
    `            <td>{row[column] ?? ''}</td>`,
    `          {/each}`,
    `        </tr>`,
    `      {/each}`,
    `    </tbody>`,
    `  </table>`,
    `</section>`,
    ``,
  ]);
}

function generateKpiCard(): string {
  return joinLines([
    `<script lang="ts">`,
    `  let {`,
    `    id,`,
    `    title = 'Metric',`,
    `    format = 'number' as 'number' | 'currency' | 'percent',`,
    `    value = 0,`,
    `  }: {`,
    `    id?: string;`,
    `    title?: string;`,
    `    format?: 'number' | 'currency' | 'percent';`,
    `    value?: number;`,
    `  } = $props();`,
    ``,
    `  function formatValue(amount: number, style: 'number' | 'currency' | 'percent'): string {`,
    `    if (style === 'currency') {`,
    `      return new Intl.NumberFormat(undefined, { style: 'currency', currency: 'USD' }).format(amount);`,
    `    }`,
    `    if (style === 'percent') {`,
    `      return new Intl.NumberFormat(undefined, { style: 'percent', maximumFractionDigits: 1 }).format(`,
    `        amount / 100,`,
    `      );`,
    `    }`,
    `    return new Intl.NumberFormat().format(amount);`,
    `  }`,
    `</script>`,
    ``,
    `<article class="kpi-card" {id}>`,
    `  <h3>{title}</h3>`,
    `  <p class="kpi-value">{formatValue(value ?? 0, format ?? 'number')}</p>`,
    `</article>`,
    ``,
  ]);
}

function generateLineChart(): string {
  return joinLines([
    `<script lang="ts">`,
    `  import type { DateRange, Row } from '../types';`,
    `  let {`,
    `    id,`,
    `    title = 'Chart',`,
    `    xField = 'date',`,
    `    yField = 'value',`,
    `    data = [] as Row[],`,
    `    range,`,
    `  }: {`,
    `    id?: string;`,
    `    title?: string;`,
    `    xField?: string;`,
    `    yField?: string;`,
    `    data?: Row[];`,
    `    range?: DateRange;`,
    `  } = $props();`,
    ``,
    `  const filtered = $derived(filterByRange(data, range));`,
    `  const points = $derived.by(() => {`,
    `    const max = Math.max(...filtered.map((row) => Number(row[yField] ?? 0)), 1);`,
    `    return filtered`,
    `      .map((row, index) => {`,
    `        const x = (index / Math.max(filtered.length - 1, 1)) * 300 + 10;`,
    `        const y = 110 - (Number(row[yField] ?? 0) / max) * 90;`,
    `        return \`\${x},\${y}\`;`,
    `      })`,
    `      .join(' ');`,
    `  });`,
    ``,
    `  function filterByRange(source: Row[], value?: DateRange): Row[] {`,
    `    if (!value) return source;`,
    `    return source.filter((row) => {`,
    `      const dateValue = String(row.date ?? row.createdAt ?? '');`,
    `      if (!dateValue) return true;`,
    `      return dateValue >= value.start && dateValue <= value.end;`,
    `    });`,
    `  }`,
    `</script>`,
    ``,
    `<section class="chart-card" {id}>`,
    `  <h3>{title}</h3>`,
    `  <svg class="line-chart" viewBox="0 0 320 120" role="img" aria-label={title}>`,
    `    <polyline fill="none" stroke="currentColor" stroke-width="2" points={points} />`,
    `  </svg>`,
    `  <p class="chart-meta">{filtered.length} points · x={xField} · y={yField}</p>`,
    `</section>`,
    ``,
  ]);
}

function generateBarChart(): string {
  return joinLines([
    `<script lang="ts">`,
    `  import type { DateRange, Row } from '../types';`,
    `  let {`,
    `    id,`,
    `    title = 'Chart',`,
    `    data = [] as Row[],`,
    `    range,`,
    `  }: {`,
    `    id?: string;`,
    `    title?: string;`,
    `    data?: Row[];`,
    `    range?: DateRange;`,
    `  } = $props();`,
    ``,
    `  const filtered = $derived(filterByRange(data, range));`,
    ``,
    `  function barHeight(row: Row): number {`,
    `    const max = Math.max(...filtered.map((entry) => Number(entry.value ?? 0)), 1);`,
    `    return (Number(row.value ?? 0) / max) * 100;`,
    `  }`,
    ``,
    `  function filterByRange(source: Row[], value?: DateRange): Row[] {`,
    `    if (!value) return source;`,
    `    return source.filter((row) => {`,
    `      const dateValue = String(row.date ?? row.createdAt ?? '');`,
    `      if (!dateValue) return true;`,
    `      return dateValue >= value.start && dateValue <= value.end;`,
    `    });`,
    `  }`,
    `</script>`,
    ``,
    `<section class="chart-card" {id}>`,
    `  <h3>{title}</h3>`,
    `  <div class="bar-chart">`,
    `    {#each filtered as row, index (String(row.id ?? index))}`,
    `      <div`,
    `        class="bar"`,
    `        style:height="{barHeight(row)}%"`,
    `        title={String(row.label ?? row.id ?? index)}`,
    `      ></div>`,
    `    {/each}`,
    `  </div>`,
    `</section>`,
    ``,
  ]);
}
