import { joinLines } from './utils';

function threeVisualHelpers(): string[] {
  return [
    `  const BAR_COLORS = ['#38bdf8', '#818cf8', '#34d399', '#fbbf24', '#f472b6', '#fb7185'];`,
    ``,
    `  interface ScatterPoint {`,
    `    x: number;`,
    `    y: number;`,
    `    z: number;`,
    `    label?: string;`,
    `  }`,
    ``,
    `  function filterByRange(data: Row[], range?: DateRange): Row[] {`,
    `    if (!range) {`,
    `      return data;`,
    `    }`,
    `    return data.filter((row) => {`,
    `      const value = String(row.date ?? row.createdAt ?? '');`,
    `      if (!value) {`,
    `        return true;`,
    `      }`,
    `      return value >= range.start && value <= range.end;`,
    `    });`,
    `  }`,
    ``,
    `  function mapScatterPoints(`,
    `    rows: Row[],`,
    `    fields: { xField: string; yField: string; zField: string },`,
    `  ): ScatterPoint[] {`,
    `    if (rows.length === 0) {`,
    `      return [`,
    `        { x: -2, y: 1.2, z: -2, label: 'A' },`,
    `        { x: 0, y: 2.4, z: 1, label: 'B' },`,
    `        { x: 2, y: 0.8, z: 2, label: 'C' },`,
    `      ];`,
    `    }`,
    ``,
    `    const raw = rows.slice(0, 48).map((row, index) => ({`,
    `      x: readNumericField(row, fields.xField, index),`,
    `      y: readNumericField(row, fields.yField, index + 1),`,
    `      z: readNumericField(row, fields.zField, index * 0.75 + 1),`,
    `      label: String(row.name ?? row.id ?? index + 1),`,
    `    }));`,
    ``,
    `    return normalizeScatterPoints(raw);`,
    `  }`,
    ``,
    `  function readNumericField(row: Row, field: string, fallback: number): number {`,
    `    const value = row[field];`,
    `    if (typeof value === 'number' && Number.isFinite(value)) {`,
    `      return value;`,
    `    }`,
    `    if (typeof value === 'string') {`,
    `      const parsed = Number(value);`,
    `      if (Number.isFinite(parsed)) {`,
    `        return parsed;`,
    `      }`,
    `      const timestamp = Date.parse(value);`,
    `      if (Number.isFinite(timestamp)) {`,
    `        return timestamp / 86400000;`,
    `      }`,
    `    }`,
    `    return fallback;`,
    `  }`,
    ``,
    `  function normalizeScatterPoints(points: ScatterPoint[]): ScatterPoint[] {`,
    `    const normalizeAxis = (values: number[], spread = 8, floor = 0.2) => {`,
    `      const min = Math.min(...values);`,
    `      const max = Math.max(...values);`,
    `      const span = max - min || 1;`,
    `      return values.map((value) => ((value - min) / span) * spread + floor);`,
    `    };`,
    ``,
    `    const xs = normalizeAxis(`,
    `      points.map((point) => point.x),`,
    `      8,`,
    `      -4,`,
    `    );`,
    `    const ys = normalizeAxis(points.map((point) => point.y));`,
    `    const zs = normalizeAxis(`,
    `      points.map((point) => point.z),`,
    `      8,`,
    `      -4,`,
    `    );`,
    ``,
    `    return points.map((point, index) => ({`,
    `      ...point,`,
    `      x: xs[index] ?? point.x,`,
    `      y: ys[index] ?? point.y,`,
    `      z: zs[index] ?? point.z,`,
    `    }));`,
    `  }`,
    ``,
  ];
}

export function generateThreeBarChart(): string {
  return joinLines([
    `<script lang="ts">`,
    `  /** Requires: npm install three @threlte/core @threlte/extras */`,
    `  import { Canvas, T } from '@threlte/core';`,
    `  import { OrbitControls } from '@threlte/extras';`,
    `  import type { DateRange, Row } from '../types';`,
    ``,
    `  let {`,
    `    id,`,
    `    title = '3D Bar Chart',`,
    `    yField = 'value',`,
    `    backgroundColor = '#0f172a',`,
    `    autoRotate = false,`,
    `    data,`,
    `    range,`,
    `  }: {`,
    `    id?: string;`,
    `    title?: string;`,
    `    yField?: string;`,
    `    backgroundColor?: string;`,
    `    autoRotate?: boolean;`,
    `    data: Row[];`,
    `    range?: DateRange;`,
    `  } = $props();`,
    ``,
    `  const bars = $derived.by(() => {`,
    `    const rows = filterByRange(data, range);`,
    `    const max = Math.max(...rows.map((row) => Number(row[yField] ?? 0)), 1);`,
    `    const spacing = 1.4;`,
    `    const offset = ((rows.length - 1) * spacing) / 2;`,
    `    return rows.map((row, index) => {`,
    `      const value = Number(row[yField] ?? 0);`,
    `      const height = Math.max(0.2, (value / max) * 4);`,
    `      return {`,
    `        key: String(row.id ?? index),`,
    `        height,`,
    `        x: index * spacing - offset,`,
    `        color: BAR_COLORS[index % BAR_COLORS.length],`,
    `      };`,
    `    });`,
    `  });`,
    ``,
    ...threeVisualHelpers(),
    `</script>`,
    ``,
    `<section class="chart-card chart-card--3d" {id}>`,
    `  <h3>{title}</h3>`,
    `  <div class="three-chart" style:background={backgroundColor}>`,
    `    <Canvas>`,
    `      <T.PerspectiveCamera makeDefault position={[8, 6, 8]} />`,
    `      <T.AmbientLight intensity={0.65} />`,
    `      <T.DirectionalLight position={[6, 10, 4]} intensity={1.1} />`,
    `      {#each bars as bar (bar.key)}`,
    `        <T.Mesh position.x={bar.x} position.y={bar.height / 2} position.z={0}>`,
    `          <T.BoxGeometry args={[0.9, bar.height, 0.9]} />`,
    `          <T.MeshStandardMaterial color={bar.color} />`,
    `        </T.Mesh>`,
    `      {/each}`,
    `      <OrbitControls {autoRotate} minDistance={4} maxDistance={40} />`,
    `    </Canvas>`,
    `  </div>`,
    `</section>`,
    ``,
  ]);
}

export function generateThreeScatterPlot(): string {
  return joinLines([
    `<script lang="ts">`,
    `  /** Requires: npm install three @threlte/core @threlte/extras */`,
    `  import { Canvas, T } from '@threlte/core';`,
    `  import { OrbitControls } from '@threlte/extras';`,
    `  import type { DateRange, Row } from '../types';`,
    ``,
    `  let {`,
    `    id,`,
    `    title = '3D Scatter Plot',`,
    `    xField = 'date',`,
    `    yField = 'amount',`,
    `    zField = 'id',`,
    `    backgroundColor = '#0f172a',`,
    `    autoRotate = false,`,
    `    data,`,
    `    range,`,
    `  }: {`,
    `    id?: string;`,
    `    title?: string;`,
    `    xField?: string;`,
    `    yField?: string;`,
    `    zField?: string;`,
    `    backgroundColor?: string;`,
    `    autoRotate?: boolean;`,
    `    data: Row[];`,
    `    range?: DateRange;`,
    `  } = $props();`,
    ``,
    `  const points = $derived.by(() =>`,
    `    mapScatterPoints(filterByRange(data, range), { xField, yField, zField }),`,
    `  );`,
    ``,
    ...threeVisualHelpers(),
    `</script>`,
    ``,
    `<section class="chart-card chart-card--3d" {id}>`,
    `  <h3>{title}</h3>`,
    `  <div class="three-chart" style:background={backgroundColor}>`,
    `    <Canvas>`,
    `      <T.PerspectiveCamera makeDefault position={[8, 6, 8]} />`,
    `      <T.AmbientLight intensity={0.65} />`,
    `      <T.DirectionalLight position={[6, 10, 4]} intensity={1.1} />`,
    `      {#each points as point, index (point.label ?? index)}`,
    `        <T.Mesh position.x={point.x} position.y={point.y} position.z={point.z}>`,
    `          <T.SphereGeometry args={[0.18, 16, 16]} />`,
    `          <T.MeshStandardMaterial color={BAR_COLORS[index % BAR_COLORS.length]} />`,
    `        </T.Mesh>`,
    `      {/each}`,
    `      <OrbitControls {autoRotate} minDistance={4} maxDistance={40} />`,
    `    </Canvas>`,
    `  </div>`,
    `</section>`,
    ``,
  ]);
}

export function generateThreeScenePointCloud(): string {
  return joinLines([
    `<script lang="ts">`,
    `  /** Requires: npm install three @threlte/core @threlte/extras */`,
    `  import { Canvas, T } from '@threlte/core';`,
    `  import { Grid, OrbitControls } from '@threlte/extras';`,
    `  import type { DateRange, Row } from '../types';`,
    ``,
    `  let {`,
    `    id,`,
    `    title = '3D Scene',`,
    `    xField = 'date',`,
    `    yField = 'amount',`,
    `    zField = 'id',`,
    `    backgroundColor = '#0f172a',`,
    `    autoRotate = false,`,
    `    showGrid = true,`,
    `    data,`,
    `    range,`,
    `  }: {`,
    `    id?: string;`,
    `    title?: string;`,
    `    xField?: string;`,
    `    yField?: string;`,
    `    zField?: string;`,
    `    backgroundColor?: string;`,
    `    autoRotate?: boolean;`,
    `    showGrid?: boolean;`,
    `    data: Row[];`,
    `    range?: DateRange;`,
    `  } = $props();`,
    ``,
    `  const points = $derived.by(() =>`,
    `    mapScatterPoints(filterByRange(data, range), { xField, yField, zField }),`,
    `  );`,
    ``,
    ...threeVisualHelpers(),
    `</script>`,
    ``,
    `<section class="chart-card chart-card--3d" {id}>`,
    `  <h3>{title}</h3>`,
    `  <div class="three-chart" style:background={backgroundColor}>`,
    `    <Canvas>`,
    `      <T.PerspectiveCamera makeDefault position={[8, 6, 8]} />`,
    `      <T.AmbientLight intensity={0.65} />`,
    `      <T.DirectionalLight position={[6, 10, 4]} intensity={1.1} />`,
    `      {#if showGrid}`,
    `        <Grid cellColor="#334155" sectionColor="#475569" position.y={-0.01} />`,
    `      {/if}`,
    `      {#each points as point, index (point.label ?? index)}`,
    `        <T.Mesh position.x={point.x} position.y={point.y} position.z={point.z}>`,
    `          <T.SphereGeometry args={[0.1, 10, 10]} />`,
    `          <T.MeshStandardMaterial color={BAR_COLORS[index % BAR_COLORS.length]} />`,
    `        </T.Mesh>`,
    `      {/each}`,
    `      <OrbitControls {autoRotate} minDistance={4} maxDistance={40} />`,
    `    </Canvas>`,
    `  </div>`,
    `</section>`,
    ``,
  ]);
}

export function generateThreeGltfModel(): string {
  return joinLines([
    `<script lang="ts">`,
    `  /** Requires: npm install three @threlte/core @threlte/extras */`,
    `  import { Canvas, T } from '@threlte/core';`,
    `  import { GLTF, Grid, OrbitControls } from '@threlte/extras';`,
    ``,
    `  const DEFAULT_MODEL_URL =`,
    `    'https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/Duck/glTF-Binary/Duck.glb';`,
    ``,
    `  let {`,
    `    id,`,
    `    title = '3D Model',`,
    `    modelUrl = DEFAULT_MODEL_URL,`,
    `    modelScale = 1.5,`,
    `    backgroundColor = '#0f172a',`,
    `    autoRotate = false,`,
    `    showGrid = true,`,
    `  }: {`,
    `    id?: string;`,
    `    title?: string;`,
    `    modelUrl?: string;`,
    `    modelScale?: number;`,
    `    backgroundColor?: string;`,
    `    autoRotate?: boolean;`,
    `    showGrid?: boolean;`,
    `  } = $props();`,
    `</script>`,
    ``,
    `<section class="chart-card chart-card--3d" {id}>`,
    `  <h3>{title}</h3>`,
    `  <div class="three-chart" style:background={backgroundColor}>`,
    `    <Canvas>`,
    `      <T.PerspectiveCamera makeDefault position={[8, 6, 8]} />`,
    `      <T.AmbientLight intensity={0.65} />`,
    `      <T.DirectionalLight position={[6, 10, 4]} intensity={1.1} />`,
    `      {#if showGrid}`,
    `        <Grid cellColor="#334155" sectionColor="#475569" position.y={-0.01} />`,
    `      {/if}`,
    `      <GLTF url={modelUrl} scale={modelScale} />`,
    `      <OrbitControls {autoRotate} minDistance={4} maxDistance={40} />`,
    `    </Canvas>`,
    `  </div>`,
    `</section>`,
    ``,
  ]);
}
