import type { ComponentDefinition } from '../model/types';

export const P0_COMPONENT_DEFINITIONS: ComponentDefinition[] = [
  {
    type: 'visual.input.text',
    category: 'visual',
    label: 'Text Input',
    description: 'Single-line text field',
    isVisual: true,
    inputs: [],
    outputs: [{ id: 'value', name: 'value', dataType: 'string' }],
    properties: [
      { key: 'placeholder', label: 'Placeholder', type: 'string', default: '' },
      { key: 'required', label: 'Required', type: 'boolean', default: false },
    ],
  },
  {
    type: 'visual.input.select',
    category: 'visual',
    label: 'Select',
    description: 'Dropdown selection',
    isVisual: true,
    inputs: [{ id: 'options', name: 'options', dataType: 'rowset' }],
    outputs: [{ id: 'value', name: 'value', dataType: 'string' }],
    properties: [
      { key: 'placeholder', label: 'Placeholder', type: 'string', default: 'Select…' },
    ],
  },
  {
    type: 'visual.input.number',
    category: 'visual',
    label: 'Number Input',
    description: 'Numeric input with optional min, max, and step',
    isVisual: true,
    inputs: [],
    outputs: [{ id: 'value', name: 'value', dataType: 'number' }],
    properties: [
      { key: 'placeholder', label: 'Placeholder', type: 'string', default: '' },
      { key: 'required', label: 'Required', type: 'boolean', default: false },
      { key: 'min', label: 'Minimum', type: 'number', default: 0 },
      { key: 'max', label: 'Maximum', type: 'number', default: 100 },
      { key: 'step', label: 'Step', type: 'number', default: 1 },
    ],
  },
  {
    type: 'visual.input.checkbox',
    category: 'visual',
    label: 'Checkbox',
    description: 'Boolean toggle input',
    isVisual: true,
    inputs: [],
    outputs: [{ id: 'value', name: 'value', dataType: 'boolean' }],
    properties: [
      { key: 'label', label: 'Label', type: 'string', default: '' },
      { key: 'defaultChecked', label: 'Default checked', type: 'boolean', default: false },
    ],
  },
  {
    type: 'visual.input.textarea',
    category: 'visual',
    label: 'Textarea',
    description: 'Multi-line text field',
    isVisual: true,
    inputs: [],
    outputs: [{ id: 'value', name: 'value', dataType: 'string' }],
    properties: [
      { key: 'placeholder', label: 'Placeholder', type: 'string', default: '' },
      { key: 'required', label: 'Required', type: 'boolean', default: false },
      { key: 'rows', label: 'Rows', type: 'number', default: 4 },
    ],
  },
  {
    type: 'visual.input.date-range',
    category: 'visual',
    label: 'Date Range',
    description: 'Start/end date filter',
    isVisual: true,
    inputs: [],
    outputs: [{ id: 'range', name: 'range', dataType: 'date-range' }],
    properties: [
      {
        key: 'preset',
        label: 'Default preset',
        type: 'select',
        default: 'last-7-days',
        options: [
          { label: 'Last 7 days', value: 'last-7-days' },
          { label: 'Last 30 days', value: 'last-30-days' },
          { label: 'Quarter to date', value: 'qtd' },
        ],
      },
    ],
  },
  {
    type: 'visual.table',
    category: 'visual',
    label: 'Data Table',
    description: 'Sortable, filterable table',
    isVisual: true,
    inputs: [
      { id: 'data', name: 'data', dataType: 'rowset', required: true },
      { id: 'filter', name: 'filter', dataType: 'date-range' },
    ],
    outputs: [
      { id: 'row-select', name: 'rowSelect', dataType: 'event' },
      { id: 'selected-row', name: 'selectedRow', dataType: 'row' },
    ],
    properties: [
      { key: 'pageSize', label: 'Page size', type: 'number', default: 25 },
      { key: 'sortable', label: 'Sortable', type: 'boolean', default: true },
      { key: 'filterable', label: 'Filterable', type: 'boolean', default: true },
    ],
  },
  {
    type: 'visual.detail',
    category: 'visual',
    label: 'Detail Panel',
    description: 'Displays fields for a selected table row',
    isVisual: true,
    inputs: [{ id: 'row', name: 'row', dataType: 'row' }],
    outputs: [],
    properties: [
      { key: 'title', label: 'Title', type: 'string', default: 'Details' },
      {
        key: 'emptyMessage',
        label: 'Empty message',
        type: 'string',
        default: 'Select a row to view details',
      },
    ],
  },
  {
    type: 'visual.skeleton',
    category: 'visual',
    label: 'Loading Skeleton',
    description: 'Placeholder shimmer while bound content loads',
    isVisual: true,
    inputs: [{ id: 'loading', name: 'loading', dataType: 'boolean' }],
    outputs: [],
    properties: [
      {
        key: 'variant',
        label: 'Variant',
        type: 'select',
        default: 'table',
        options: [
          { label: 'Table', value: 'table' },
          { label: 'Chart', value: 'chart' },
          { label: 'KPI', value: 'kpi' },
          { label: 'Card', value: 'card' },
        ],
      },
      { key: 'lines', label: 'Lines', type: 'number', default: 4 },
      { key: 'defaultLoading', label: 'Show by default', type: 'boolean', default: true },
    ],
  },
  {
    type: 'logic.timer',
    category: 'logic',
    label: 'Timer',
    description: 'Interval or countdown ticks for polling and refresh triggers',
    isVisual: true,
    inputs: [],
    outputs: [
      { id: 'tick', name: 'tick', dataType: 'event' },
      { id: 'elapsed', name: 'elapsed', dataType: 'number' },
    ],
    properties: [
      { key: 'label', label: 'Label', type: 'string', default: 'Timer' },
      {
        key: 'mode',
        label: 'Mode',
        type: 'select',
        default: 'interval',
        options: [
          { label: 'Interval', value: 'interval' },
          { label: 'Countdown', value: 'countdown' },
        ],
      },
      { key: 'intervalMs', label: 'Interval (ms)', type: 'number', default: 5000 },
      { key: 'durationMs', label: 'Countdown duration (ms)', type: 'number', default: 30000 },
      { key: 'autoStart', label: 'Auto start', type: 'boolean', default: true },
    ],
  },
  {
    type: 'visual.kpi',
    category: 'visual',
    label: 'KPI Card',
    description: 'Single metric with optional delta',
    isVisual: true,
    inputs: [{ id: 'value', name: 'value', dataType: 'number' }],
    outputs: [],
    properties: [
      { key: 'title', label: 'Title', type: 'string', default: 'Metric' },
      { key: 'format', label: 'Format', type: 'select', default: 'number', options: [
        { label: 'Number', value: 'number' },
        { label: 'Currency', value: 'currency' },
        { label: 'Percent', value: 'percent' },
      ]},
    ],
  },
  {
    type: 'visual.chart.line',
    category: 'visual',
    label: 'Line Chart',
    description: 'Time-series line chart',
    isVisual: true,
    inputs: [
      { id: 'data', name: 'data', dataType: 'rowset', required: true },
      { id: 'range', name: 'range', dataType: 'date-range' },
    ],
    outputs: [],
    properties: [
      { key: 'title', label: 'Title', type: 'string', default: 'Chart' },
      { key: 'xField', label: 'X field', type: 'string', default: 'date' },
      { key: 'yField', label: 'Y field', type: 'string', default: 'value' },
    ],
  },
  {
    type: 'visual.chart.bar',
    category: 'visual',
    label: 'Bar Chart',
    isVisual: true,
    inputs: [
      { id: 'data', name: 'data', dataType: 'rowset', required: true },
      { id: 'range', name: 'range', dataType: 'date-range' },
    ],
    outputs: [],
    properties: [
      { key: 'title', label: 'Title', type: 'string', default: 'Chart' },
    ],
  },
  {
    type: 'visual.chart.pie',
    category: 'visual',
    label: 'Pie Chart',
    description: 'Category breakdown pie or donut chart',
    isVisual: true,
    inputs: [
      { id: 'data', name: 'data', dataType: 'rowset', required: true },
      { id: 'range', name: 'range', dataType: 'date-range' },
    ],
    outputs: [],
    properties: [
      { key: 'title', label: 'Title', type: 'string', default: 'Chart' },
      { key: 'labelField', label: 'Label field', type: 'string', default: 'label' },
      { key: 'valueField', label: 'Value field', type: 'string', default: 'value' },
      { key: 'donut', label: 'Donut style', type: 'boolean', default: false },
    ],
  },
  {
    type: 'layout.grid',
    category: 'layout',
    label: 'Grid',
    description: 'Responsive grid layout',
    isVisual: true,
    inputs: [],
    outputs: [{ id: 'slot', name: 'slot', dataType: 'any' }],
    properties: [
      { key: 'columns', label: 'Columns', type: 'number', default: 12 },
      { key: 'gap', label: 'Gap (px)', type: 'number', default: 16 },
    ],
  },
  {
    type: 'layout.flex',
    category: 'layout',
    label: 'Flex',
    description: 'Flex row or column layout container',
    isVisual: true,
    inputs: [],
    outputs: [{ id: 'slot', name: 'slot', dataType: 'any' }],
    properties: [
      {
        key: 'direction',
        label: 'Direction',
        type: 'select',
        default: 'row',
        options: [
          { label: 'Row', value: 'row' },
          { label: 'Column', value: 'column' },
        ],
      },
      { key: 'gap', label: 'Gap (px)', type: 'number', default: 16 },
      {
        key: 'align',
        label: 'Align items',
        type: 'select',
        default: 'stretch',
        options: [
          { label: 'Stretch', value: 'stretch' },
          { label: 'Start', value: 'flex-start' },
          { label: 'Center', value: 'center' },
        ],
      },
    ],
  },
  {
    type: 'layout.tabs',
    category: 'layout',
    label: 'Tabs',
    isVisual: true,
    inputs: [],
    outputs: [{ id: 'slot', name: 'slot', dataType: 'any' }],
    properties: [
      { key: 'defaultTab', label: 'Default tab index', type: 'number', default: 0 },
    ],
  },
  {
    type: 'layout.modal',
    category: 'layout',
    label: 'Modal',
    isVisual: true,
    inputs: [{ id: 'open', name: 'open', dataType: 'event' }],
    outputs: [{ id: 'slot', name: 'slot', dataType: 'any' }],
    properties: [
      { key: 'title', label: 'Title', type: 'string', default: 'Dialog' },
    ],
  },
  {
    type: 'layout.collapsible',
    category: 'layout',
    label: 'Collapsible',
    description: 'Expand/collapse section with title and summary',
    isVisual: true,
    inputs: [],
    outputs: [{ id: 'slot', name: 'slot', dataType: 'any' }],
    properties: [
      { key: 'title', label: 'Title', type: 'string', default: 'Section' },
      { key: 'summary', label: 'Summary', type: 'string', default: '' },
      { key: 'expanded', label: 'Expanded by default', type: 'boolean', default: false },
    ],
  },
  {
    type: 'domain.role-gate',
    category: 'domain',
    label: 'Role Gate',
    description: 'Show children only for allowed roles',
    isVisual: true,
    inputs: [],
    outputs: [{ id: 'visible', name: 'visible', dataType: 'boolean' }],
    properties: [
      {
        key: 'roles',
        label: 'Allowed roles',
        type: 'json',
        default: ['admin', 'editor'],
      },
    ],
  },
  {
    type: 'domain.person-invite',
    category: 'domain',
    label: 'Person Invite',
    description: 'Onboarding step to invite a person by email',
    isVisual: true,
    inputs: [],
    outputs: [
      { id: 'email', name: 'email', dataType: 'string' },
      { id: 'submit', name: 'submit', dataType: 'event' },
    ],
    properties: [
      { key: 'title', label: 'Title', type: 'string', default: 'Invite team member' },
      {
        key: 'emailPlaceholder',
        label: 'Email placeholder',
        type: 'string',
        default: 'name@company.com',
      },
      { key: 'submitLabel', label: 'Submit label', type: 'string', default: 'Send invite' },
    ],
  },
  {
    type: 'domain.role-assign',
    category: 'domain',
    label: 'Role Assign',
    description: 'Onboarding step to assign a role and confirm access',
    isVisual: true,
    inputs: [{ id: 'roles', name: 'roles', dataType: 'rowset' }],
    outputs: [
      { id: 'roleId', name: 'roleId', dataType: 'string' },
      { id: 'confirm', name: 'confirm', dataType: 'event' },
    ],
    properties: [
      { key: 'title', label: 'Title', type: 'string', default: 'Assign role' },
      { key: 'confirmLabel', label: 'Confirm label', type: 'string', default: 'Confirm access' },
      {
        key: 'summaryLabel',
        label: 'Summary label',
        type: 'string',
        default: 'Review access before confirming',
      },
    ],
  },
  {
    type: 'domain.time-preset',
    category: 'domain',
    label: 'Time Preset',
    description: 'Relative period shortcuts for dashboard filters',
    isVisual: true,
    inputs: [],
    outputs: [{ id: 'range', name: 'range', dataType: 'date-range' }],
    properties: [
      { key: 'label', label: 'Label', type: 'string', default: 'Period' },
      {
        key: 'defaultPreset',
        label: 'Default preset',
        type: 'select',
        default: 'last-7-days',
        options: [
          { label: 'Last 7 days', value: 'last-7-days' },
          { label: 'Last 30 days', value: 'last-30-days' },
          { label: 'Quarter to date', value: 'qtd' },
        ],
      },
    ],
  },
  {
    type: 'infra.env',
    category: 'infra',
    label: 'Environment Config',
    isVisual: false,
    inputs: [],
    outputs: [{ id: 'config', name: 'config', dataType: 'any' }],
    properties: [
      { key: 'variables', label: 'Variables', type: 'json', default: [] },
    ],
  },
  {
    type: 'infra.postgresql',
    category: 'infra',
    label: 'PostgreSQL',
    isVisual: false,
    inputs: [{ id: 'env', name: 'env', dataType: 'any' }],
    outputs: [{ id: 'rowset', name: 'rowset', dataType: 'rowset' }],
    properties: [
      { key: 'connectionEnvKey', label: 'Connection env key', type: 'string', default: 'DATABASE_URL', required: true },
      { key: 'table', label: 'Table name', type: 'string', default: '' },
    ],
  },
  {
    type: 'infra.mongodb',
    category: 'infra',
    label: 'MongoDB',
    isVisual: false,
    inputs: [{ id: 'env', name: 'env', dataType: 'any' }],
    outputs: [{ id: 'documents', name: 'documents', dataType: 'rowset' }],
    properties: [
      { key: 'connectionEnvKey', label: 'Connection env key', type: 'string', default: 'MONGODB_URI', required: true },
      { key: 'collection', label: 'Collection name', type: 'string', default: '' },
    ],
  },
  {
    type: 'infra.supabase',
    category: 'infra',
    label: 'Supabase',
    isVisual: false,
    inputs: [{ id: 'env', name: 'env', dataType: 'any' }],
    outputs: [{ id: 'rowset', name: 'rowset', dataType: 'rowset' }],
    properties: [
      { key: 'urlEnvKey', label: 'Supabase URL env key', type: 'string', default: 'SUPABASE_URL', required: true },
      { key: 'anonKeyEnvKey', label: 'Anon key env key', type: 'string', default: 'SUPABASE_ANON_KEY', required: true },
      { key: 'table', label: 'Table name', type: 'string', default: '' },
    ],
  },
  {
    type: 'infra.mysql',
    category: 'infra',
    label: 'MySQL',
    isVisual: false,
    inputs: [{ id: 'env', name: 'env', dataType: 'any' }],
    outputs: [{ id: 'rowset', name: 'rowset', dataType: 'rowset' }],
    properties: [
      { key: 'connectionEnvKey', label: 'Connection env key', type: 'string', default: 'MYSQL_URL', required: true },
      { key: 'table', label: 'Table name', type: 'string', default: '' },
    ],
  },
  {
    type: 'infra.server.nest',
    category: 'infra',
    label: 'NestJS Server',
    isVisual: false,
    inputs: [{ id: 'database', name: 'database', dataType: 'any' }],
    outputs: [{ id: 'api', name: 'api', dataType: 'any' }],
    properties: [
      { key: 'globalPrefix', label: 'API prefix', type: 'string', default: 'api' },
    ],
  },
  {
    type: 'infra.server.express',
    category: 'infra',
    label: 'Express Server',
    isVisual: false,
    inputs: [{ id: 'database', name: 'database', dataType: 'any' }],
    outputs: [{ id: 'api', name: 'api', dataType: 'any' }],
    properties: [
      { key: 'globalPrefix', label: 'API prefix', type: 'string', default: 'api' },
    ],
  },
  {
    type: 'infra.server.next',
    category: 'infra',
    label: 'Next.js Server',
    isVisual: false,
    inputs: [{ id: 'database', name: 'database', dataType: 'any' }],
    outputs: [{ id: 'api', name: 'api', dataType: 'any' }],
    properties: [
      { key: 'globalPrefix', label: 'API prefix', type: 'string', default: 'api' },
    ],
  },
  {
    type: 'infra.server.nuxt',
    category: 'infra',
    label: 'Nuxt Server',
    isVisual: false,
    inputs: [{ id: 'database', name: 'database', dataType: 'any' }],
    outputs: [{ id: 'api', name: 'api', dataType: 'any' }],
    properties: [
      { key: 'globalPrefix', label: 'API prefix', type: 'string', default: 'api' },
    ],
  },
];
